// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Andrei Taranik

package vms

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"sync"
	"time"

	"github.com/coder/websocket"
	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/otherix/otherix/internal/api/agentclient"
	"github.com/otherix/otherix/internal/api/response"
	"github.com/otherix/otherix/internal/auth"
	"github.com/otherix/otherix/internal/store"
	"github.com/otherix/otherix/internal/wskeepalive"
)

// consoleSessionRejectedMsg is the single generic message for every
// unauthenticated-reachable rejection on the anonymous console-stream
// endpoint (missing token, unknown VM name, agent-rejected token). All
// three cases must answer 401 unauthenticated with this exact string:
// any divergence between them hands an unauthenticated caller a
// VM-name enumeration oracle.
const consoleSessionRejectedMsg = "invalid or expired console session"

// consoleNode is the resolved owning node for a console session: the node id
// (to detect a cutover flip), the node's cluster-CA identity SAN
// (auth.NodeIdentitySAN, the host buildAgentConsoleURL dials the agent
// console-stream at through the shared geo transport), and the identity
// DialURL (agentclient.DialURL, the endpoint IssueConsoleToken is minted
// against on re-attach). Both drive the geo route resolver, so a NAT'd node
// splices through a gateway exactly as the control path does.
type consoleNode struct {
	id       uuid.UUID
	host     string
	endpoint string
}

// resolveConsoleNode resolves vm -> owning node -> {id, host, endpoint}.
// It prefers PinnedNodeID (flipped by the cutover Txn), falling back to
// the storage pool's node via resolveNodeForVM. host is the node's identity
// SAN and endpoint is its identity DialURL - the same dial the control
// handlers use, not the raw AdvertisedEndpoint.
func (h *Handler) resolveConsoleNode(ctx context.Context, vm store.VM) (consoleNode, error) {
	nodeID, err := h.resolveNodeForVM(ctx, vm)
	if err != nil {
		return consoleNode{}, fmt.Errorf("resolve node: %w", err)
	}
	node, err := h.store.NodeByID(ctx, nodeID)
	if err != nil {
		return consoleNode{}, fmt.Errorf("load node: %w", err)
	}
	return consoleNode{
		id:       nodeID,
		host:     auth.NodeIdentitySAN(node.Name),
		endpoint: agentclient.DialURL(node.Name),
	}, nil
}

// ConsoleStream implements GET /v1/vms/{id}/console-stream — the
// CP-side proxy WebSocket relay for proxy mode.
// The operator's CLI hits this URL with the agent-issued token in the
// query string; the CP resolves the owning agent, opens its own
// WebSocket to the agent's `console-stream` endpoint forwarding the
// token verbatim, and pumps binary frames bidirectionally. The token
// is the auth contract — the agent validates it, the CP only
// transports.
//
// Direct mode operators bypass this handler entirely: the CP's
// `vms.console` response carries the agent's external URL directly,
// so the CLI dials the agent without crossing this handler.
//
// This handler is intentionally anonymous (no Authn middleware): the
// agent token in the query string is the auth credential, and
// requiring a user JWT here would force the CLI to maintain a second
// credential path in parallel.
func (h *Handler) ConsoleStream(w http.ResponseWriter, r *http.Request) {
	if h.consoleDeps.AgentClient == nil {
		response.WriteError(w, r, http.StatusInternalServerError,
			response.CodeInternal, "console client not configured", nil)
		return
	}

	vmName := chi.URLParam(r, "id")
	if vmName == "" {
		// Defensive only - chi does not route an empty {id} segment to
		// this handler, and an empty name can never match a real VM, so
		// the 404 here carries no existence signal. Left as-is.
		response.WriteError(w, r, http.StatusNotFound,
			response.CodeVMNotFound, "vm not found", nil)
		return
	}
	token := r.URL.Query().Get("token")
	if token == "" {
		response.WriteError(w, r, http.StatusUnauthorized,
			response.CodeUnauthenticated, consoleSessionRejectedMsg, nil)
		return
	}

	vm, err := h.store.VMByName(r.Context(), vmName)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			// Anonymous endpoint: an unknown VM name must produce the
			// SAME response a rejected token does. A distinct 404 here
			// would let an unauthenticated caller probe
			// /v1/vms/<name>/console-stream?token=x and enumerate VM
			// names (404 = no such VM, 401 = VM exists). Collapsing to
			// the generic 401 costs no legitimate UX - the URL (with
			// token) is machine-generated by the prior vms.console
			// call, never operator-typed.
			// Residuals (all accepted): (1) an existing-VM bogus-token
			// request still triggers one CP->agent dial before rejection
			// (bounded amplification - closing it would need CP-side
			// token state the architecture deliberately does not keep);
			// (2) the internal 500 (node-resolve) and 502 (agent
			// unreachable) paths below are only reachable for an
			// existing VM, so they remain a weak existence signal - but
			// only while that VM's node is down, and collapsing them to
			// the generic 401 would mislead a legitimate valid-token
			// operator whose node is genuinely unreachable; (3) the
			// no-dial 401 here returns faster than the post-dial 401 for
			// an existing VM (timing delta). Both are far weaker than the
			// status-code oracle this closes and not worth degrading
			// real error reporting or adding artificial delay.
			response.WriteError(w, r, http.StatusUnauthorized,
				response.CodeUnauthenticated, consoleSessionRejectedMsg, nil)
			return
		}
		h.log.ErrorContext(r.Context(), "vms.consoleStream load vm",
			"vm", vmName, "error", err.Error())
		response.WriteError(w, r, http.StatusInternalServerError,
			response.CodeInternal, "load vm", nil)
		return
	}
	// Resolve the owning node ONCE on the happy path: its host builds the
	// upstream URL and the same consoleNode is handed to relayConsoleFollow
	// (which re-resolves only on a re-attach). A resolve failure here is
	// pre-upgrade, so it keeps the 500 envelope shape.
	current, err := h.resolveConsoleNode(r.Context(), vm)
	if err != nil {
		h.log.ErrorContext(r.Context(), "vms.consoleStream resolve node",
			"vm_id", vm.ID, "error", err.Error())
		response.WriteError(w, r, http.StatusInternalServerError,
			response.CodeInternal, "resolve node", nil)
		return
	}
	agentURL := buildAgentConsoleURL(current.host, vmName, token)

	// Dial the agent's WebSocket using the agentclient's mTLS-configured
	// HTTP client. Agent validates the token before completing the
	// handshake; non-101 surfaces as a Dial error here, and we relay
	// the agent's status / body to the operator's client as 5xx
	// (we cannot return 4xx after the upgrade has begun, and agent-
	// reported 401 / 409 should reach the operator with their full
	// fidelity — coder/websocket carries the original response).
	upstream, upstreamResp, err := websocket.Dial(r.Context(), agentURL, &websocket.DialOptions{
		HTTPClient: h.consoleDeps.AgentClient.HTTPClient(),
	})
	if err != nil {
		h.relayUpstreamDialError(w, r, upstreamResp, err)
		return
	}
	defer func() { _ = upstream.Close(websocket.StatusInternalError, "") }()

	// Clear hijacked connection deadlines — http.Server.ReadTimeout /
	// WriteTimeout are applied via SetRead/WriteDeadline at request
	// start, and persist on the net.Conn after coder/websocket.Accept
	// hijacks it. Without these calls, the WebSocket relay drops at
	// ~30s when those deadlines fire. Logged at WARN instead of bailing.
	rc := http.NewResponseController(w)
	if derr := rc.SetReadDeadline(time.Time{}); derr != nil {
		h.log.WarnContext(r.Context(), "vms.consoleStream clear read deadline",
			"vm", vmName, "error", derr.Error())
	}
	if derr := rc.SetWriteDeadline(time.Time{}); derr != nil {
		h.log.WarnContext(r.Context(), "vms.consoleStream clear write deadline",
			"vm", vmName, "error", derr.Error())
	}

	downstream, err := websocket.Accept(w, r, &websocket.AcceptOptions{
		InsecureSkipVerify: true,
	})
	if err != nil {
		// Accept already wrote a response; nothing to do beyond cleaning
		// up the upstream connection (deferred above).
		h.log.ErrorContext(r.Context(), "vms.consoleStream downstream accept",
			"vm", vmName, "error", err.Error())
		return
	}
	defer func() { _ = downstream.Close(websocket.StatusInternalError, "") }()

	h.relayConsoleFollow(r.Context(), vm, current, downstream, upstream)
}

// buildAgentConsoleURL composes the wss:// URL of the owning agent's
// console-stream endpoint that the CP-side relay dials. The VM name is
// path-escaped and the token query-escaped. The token is hex (URL-safe
// by construction, so escaping is a no-op for it today), but a VM name
// is only length-validated (1..255 chars, no charset) today, so a name
// containing URL-special characters (e.g. a space) is creatable and its
// console URL would be malformed without PathEscape - the escaping is a
// real correctness fix for those names, not merely defensive.
func buildAgentConsoleURL(agentHost, vmName, token string) string {
	return fmt.Sprintf("wss://%s/v1/vms/%s/console-stream?token=%s",
		agentHost, url.PathEscape(vmName), url.QueryEscape(token))
}

// relayUpstreamDialError translates failures dialing the agent's
// WebSocket to the operator-facing envelope. WebSocket.Dial preserves
// the upstream HTTP response when available, so the agent's 409 can be
// echoed before we burn through to 502. The agent's 401 deliberately
// collapses to the generic consoleSessionRejectedMsg shape - it must
// stay indistinguishable from the unknown-VM rejection (see
// ConsoleStream's enumeration note).
func (h *Handler) relayUpstreamDialError(w http.ResponseWriter, r *http.Request, upstreamResp *http.Response, err error) {
	if upstreamResp != nil {
		switch upstreamResp.StatusCode {
		case http.StatusUnauthorized:
			response.WriteError(w, r, http.StatusUnauthorized,
				response.CodeUnauthenticated, consoleSessionRejectedMsg, nil)
			return
		case http.StatusConflict:
			response.WriteError(w, r, http.StatusConflict,
				response.CodeConsoleInUse,
				"console session already open or vm not running on the agent", nil)
			return
		case http.StatusNotFound:
			response.WriteError(w, r, http.StatusNotFound,
				response.CodeVMNotFound, "vm not found on agent", nil)
			return
		}
	}
	h.log.ErrorContext(r.Context(), "vms.consoleStream dial upstream",
		"error", err.Error())
	response.WriteError(w, r, http.StatusBadGateway,
		response.CodeAgentUnreachable, "console relay dial failed", nil)
}

const consoleInboundBufferLimit = 32 * 1024

// Re-attach tuning (vars so tests can shrink them; production defaults
// per the design doc). The window is deliberately short (vs logs' 60s):
// per the keystroke policy a slow cutover drops the session rather than
// buffer for a minute.
var (
	consoleReattachWindowVar = 8 * time.Second
	consoleReattachPollVar   = 250 * time.Millisecond
)

// consoleMigratedCloseCode is the application WebSocket close code the CP
// sends the operator when a re-attach gives up (window/overflow/no-flip).
// In the coder/websocket application range (4000-4999). The CLI maps it to
// a reconnect hint - keep this value in sync with cmd/cli/vm/console.go.
const (
	consoleMigratedCloseCode   = websocket.StatusCode(4002)
	consoleMigratedCloseReason = "console moved during migration; reconnect"
)

// relayConsoleFollow bridges the operator (downstream) and agent
// (upstream) console WebSockets and FOLLOWS the VM across a live
// migration. The downstream connection and its reader/keepalive live for
// the whole session; the upstream is swapped per attempt. On an upstream
// break the loop consults trustworthy store signals (decideReattach) and
// either re-attaches to the new owner, ends cleanly, or drops the session
// with consoleMigratedCloseCode.
func (h *Handler) relayConsoleFollow(parent context.Context, vm store.VM, current consoleNode, downstream, upstream *websocket.Conn) {
	ctx, cancel := context.WithCancel(parent)
	defer cancel()

	buf := newConsoleInboundBuffer(consoleInboundBufferLimit)
	defer buf.close()

	go func() {
		defer cancel()
		for {
			_, data, err := downstream.Read(ctx)
			if err != nil {
				return
			}
			if !buf.append(data) {
				return
			}
		}
	}()
	go wskeepalive.Run(ctx, cancel, downstream, wskeepalive.DefaultInterval, wskeepalive.DefaultTimeout)

	for {
		h.bridgeAttempt(ctx, vm.Name, downstream, upstream, buf)
		_ = upstream.Close(websocket.StatusInternalError, "")

		if ctx.Err() != nil {
			_ = downstream.Close(websocket.StatusNormalClosure, "")
			return
		}

		next, decision := h.decideReattach(ctx, vm, current, buf)
		switch decision {
		case reattachOK:
			h.log.InfoContext(ctx, "vms.consoleStream reattach",
				"vm", vm.Name, "from_node", current.id, "to_node", next.node.id)
			current = next.node
			upstream = next.upstream
			continue
		case reattachGiveUp:
			_ = downstream.Close(consoleMigratedCloseCode, consoleMigratedCloseReason)
			return
		default: // reattachClean
			_ = downstream.Close(websocket.StatusNormalClosure, "")
			return
		}
	}
}

// bridgeAttempt pumps frames between downstream and the CURRENT upstream
// until the upstream breaks (read or write error) or the session ctx is
// cancelled. The drain pump replays the buffer (anything typed during a
// gap) and then live keystrokes to upstream. It does NOT close either
// conn - the caller owns lifecycle.
func (h *Handler) bridgeAttempt(sessionCtx context.Context, vmName string, downstream, upstream *websocket.Conn, buf *consoleInboundBuffer) {
	ctx, cancel := context.WithCancel(sessionCtx)
	defer cancel()

	var wg sync.WaitGroup
	wg.Add(3)

	go func() {
		defer wg.Done()
		defer cancel()
		for {
			typ, data, err := upstream.Read(ctx)
			if err != nil {
				return
			}
			if werr := downstream.Write(ctx, typ, data); werr != nil {
				return
			}
		}
	}()
	go func() {
		defer wg.Done()
		defer cancel()
		// inflight is the most recently written-but-unconfirmed frame. A
		// frame is committed (left dropped) only AFTER the NEXT frame writes
		// successfully - a confirmed follow-up write proves the upstream
		// actually processed the prior one. The last frame written before an
		// upstream break is therefore never confirmed, so on teardown it is
		// unshifted back to the buffer head and the next bridge re-delivers
		// it across the swap. This closes the lost-keystroke window: a frame
		// written into a concurrently-closing upstream can be silently
		// dropped even though Write returns nil, and a (possibly
		// non-echoing) console gives no app-level ACK to confirm delivery
		// any other way. At-least-once: the swap can duplicate the last
		// pre-break keystroke, which is harmless on a console; losing it is
		// not.
		var inflight []byte
		for {
			frame, ok := buf.take()
			if !ok {
				select {
				case <-ctx.Done():
					if inflight != nil {
						buf.unshift(inflight)
					}
					return
				case <-buf.signal():
					continue
				}
			}
			if werr := upstream.Write(ctx, websocket.MessageBinary, frame); werr != nil {
				// frame never landed; re-buffer it (and the prior
				// unconfirmed frame) at the head for the next bridge, head
				// order preserved by unshifting frame after inflight.
				buf.unshift(frame)
				if inflight != nil {
					buf.unshift(inflight)
				}
				return
			}
			inflight = frame
		}
	}()
	go func() {
		defer wg.Done()
		wskeepalive.Run(ctx, cancel, upstream, wskeepalive.DefaultInterval, wskeepalive.DefaultTimeout)
	}()

	wg.Wait()
}

// reattachDecision is the outcome of decideReattach.
type reattachDecision int

const (
	reattachClean  reattachDecision = iota // same node, no migration: clean end
	reattachOK                             // re-attached to a new owner
	reattachGiveUp                         // window/overflow/no-flip: drop session
)

// reattachResult carries the new owner + dialed upstream on reattachOK.
type reattachResult struct {
	node     consoleNode
	upstream *websocket.Conn
}

// decideReattach runs after an upstream break (downstream still alive).
// Same node + no migration is a clean end (the VM was stopped / the agent
// closed the console). Otherwise it re-mints a fresh token against the
// current owner and re-dials within consoleReattachWindowVar, retrying
// transient mint/dial failures (the target Running-before-attachMux race
// and a brief console_in_use). Buffer overflow or a never-converging
// migration -> give up. It performs no destructive action: on
// overflow/window/uncertainty it closes the operator session, never
// mutating VM or qemu state.
func (h *Handler) decideReattach(ctx context.Context, vm store.VM, current consoleNode, buf *consoleInboundBuffer) (reattachResult, reattachDecision) {
	fresh, err := h.store.VMByName(ctx, vm.Name)
	if err != nil {
		return reattachResult{}, reattachClean
	}
	owner, err := h.resolveConsoleNode(ctx, fresh)
	if err == nil && owner.id == current.id {
		if _, migrating, merr := h.store.ActiveMigrationForVM(ctx, vm.ID); merr != nil || !migrating {
			return reattachResult{}, reattachClean
		}
	}

	deadline := time.Now().Add(consoleReattachWindowVar)
	ticker := time.NewTicker(consoleReattachPollVar)
	defer ticker.Stop()
	for {
		if buf.overflowed() {
			return reattachResult{}, reattachGiveUp
		}
		owner, err := h.resolveConsoleNode(ctx, h.reReadVM(ctx, vm.Name))
		switch {
		case err != nil:
			// Transient resolve failure: keep polling.
		case owner.id == current.id:
			if _, migrating, _ := h.store.ActiveMigrationForVM(ctx, vm.ID); !migrating {
				return reattachResult{}, reattachClean
			}
		default:
			if up, ok := h.dialReattach(ctx, owner, vm.Name); ok {
				return reattachResult{node: owner, upstream: up}, reattachOK
			}
		}
		select {
		case <-ctx.Done():
			return reattachResult{}, reattachGiveUp
		case <-ticker.C:
			if time.Now().After(deadline) {
				return reattachResult{}, reattachGiveUp
			}
		}
	}
}

// dialReattach mints a fresh serial token against owner and dials its
// console-stream. Any failure is transient (target not Running yet, mux
// not attached, brief console_in_use) -> ok=false, the caller retries. A
// successful dial returns a live upstream the caller (relayConsoleFollow)
// owns and closes; dialReattach never closes it.
func (h *Handler) dialReattach(ctx context.Context, owner consoleNode, vmName string) (*websocket.Conn, bool) {
	tok, err := h.consoleDeps.AgentClient.IssueConsoleToken(ctx, owner.endpoint, vmName, "serial")
	if err != nil {
		return nil, false
	}
	up, _, err := websocket.Dial(ctx, buildAgentConsoleURL(owner.host, vmName, tok.Token), &websocket.DialOptions{
		HTTPClient: h.consoleDeps.AgentClient.HTTPClient(),
	})
	if err != nil {
		return nil, false
	}
	return up, true
}

// reReadVM re-reads the VM by name. On error it returns a zero VM whose
// resolve fails, which decideReattach treats as a transient (it keeps
// polling rather than ending the loop early on a re-read error while a
// migration is in flight).
func (h *Handler) reReadVM(ctx context.Context, name string) store.VM {
	vm, err := h.store.VMByName(ctx, name)
	if err != nil {
		return store.VM{}
	}
	return vm
}
