// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Andrei Taranik

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// agentConfigTemplateText is the hybrid γ shape per SL2: operator
// inputs + auto-detected values are written explicitly; tunables stay
// as commented hints. text/template (not yaml.Marshal) preserves the
// comments — Marshal would strip them on every regeneration.
//
// This is the canonical agent runtime config. cfg.NodeID is gone
// (name-keyed identity derives от cert CN); cfg.Bootstrap is gone
// (bootstrap is now the standalone subcommand).
const agentConfigTemplateText = `# Otherix agent configuration — generated by ` + "`otherix-agent bootstrap`" + `.
# DO NOT hand-edit. Re-run ` + "`otherix-agent bootstrap --force`" + ` to regenerate
# с fresh values.

server:
  listen: "{{.ListenAddr}}"            # bootstrap --listen
  # read_timeout: 30s                   # uncomment к override default
  # write_timeout: 30s
  # shutdown_grace: 30s

logger:
  level: "info"                        # default; "debug" для local debugging
  format: "json"

state_path: "/opt/otherix/vms"

control_plane:
  url: "{{.CPURL}}"                    # bootstrap --cp-url
  heartbeat_interval: "{{.HeartbeatInterval}}"

tls:
  ca_cert_path: "{{.CAPath}}"          # written by bootstrap.Persist
  cert_path:    "{{.CertPath}}"
  key_path:     "{{.KeyPath}}"

migration:
  host: "{{.MigrationHost}}"           # bootstrap --migration-host
  port_range_start: {{.MigrationPortRangeStart}}
  port_range_end:   {{.MigrationPortRangeEnd}}

qemu:
  aarch64_firmware_path: "/usr/share/AAVMF/AAVMF_CODE.fd"
`

// agentConfigTemplate is parsed once at process startup; rendering
// cost is dominated by file IO.
var agentConfigTemplate = template.Must(template.New("agent-config").Parse(agentConfigTemplateText))

// writeAgentConfig renders agentConfigTemplate against in и writes the
// result atomically (tempfile + rename in the destination directory)
// at mode 0644. The parent directory is created с mode 0755 if absent
// — `/etc/otherix/` is world-traversable but file contents are not
// secret (cert paths are pointers, не cert material).
func writeAgentConfig(destPath string, in agentConfigInputs) error {
	var buf bytes.Buffer
	if err := agentConfigTemplate.Execute(&buf, in); err != nil {
		return fmt.Errorf("render agent-config template: %v", err)
	}

	dir := filepath.Dir(destPath)
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return fmt.Errorf("ensure parent dir %s: %v", dir, err)
	}

	tmp, err := os.CreateTemp(dir, ".agent-config-*.tmp")
	if err != nil {
		return fmt.Errorf("create temp file in %s: %v", dir, err)
	}
	tmpName := tmp.Name()
	cleanup := func() { _ = os.Remove(tmpName) }

	if err := tmp.Chmod(0o644); err != nil {
		_ = tmp.Close()
		cleanup()
		return fmt.Errorf("chmod temp: %v", err)
	}
	if _, err := tmp.Write(buf.Bytes()); err != nil {
		_ = tmp.Close()
		cleanup()
		return fmt.Errorf("write temp: %v", err)
	}
	if err := tmp.Close(); err != nil {
		cleanup()
		return fmt.Errorf("close temp: %v", err)
	}
	if err := os.Rename(tmpName, destPath); err != nil {
		cleanup()
		return fmt.Errorf("rename %s -> %s: %v", tmpName, destPath, err)
	}
	return nil
}
