// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_certs.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAgentCert = `-- name: CreateAgentCert :one
insert into agent_certs (
    id, node_id, serial, fingerprint_sha256,
    subject_dn, not_before, not_after
)
values (
    $1, $2, $3, $4,
    $5, $6, $7
)
returning id, node_id, serial, fingerprint_sha256, subject_dn, not_before, not_after, issued_at, revoked_at, revocation_reason
`

type CreateAgentCertParams struct {
	ID                uuid.UUID
	NodeID            uuid.UUID
	Serial            []byte
	FingerprintSha256 []byte
	SubjectDn         string
	NotBefore         time.Time
	NotAfter          time.Time
}

// Inserts agent cert metadata after Step 2 redemption signs a CSR.
// The cert PEM itself is NOT stored — returned to the agent in the
// redemption response, agent persists locally on disk. CP keeps only
// the metadata (serial, fingerprint, subject DN, validity) for
// AgentMTLS fingerprint lookup and future revocation tracking. The
// caller passes serial as DER big-endian bytes (big.Int.Bytes() of
// the cert's SerialNumber).
func (q *Queries) CreateAgentCert(ctx context.Context, arg CreateAgentCertParams) (AgentCert, error) {
	row := q.db.QueryRow(ctx, createAgentCert,
		arg.ID,
		arg.NodeID,
		arg.Serial,
		arg.FingerprintSha256,
		arg.SubjectDn,
		arg.NotBefore,
		arg.NotAfter,
	)
	var i AgentCert
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Serial,
		&i.FingerprintSha256,
		&i.SubjectDn,
		&i.NotBefore,
		&i.NotAfter,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.RevocationReason,
	)
	return i, err
}

const lookupAgentCertByFingerprint = `-- name: LookupAgentCertByFingerprint :one
select node_id, revoked_at
from agent_certs
where fingerprint_sha256 = $1
`

type LookupAgentCertByFingerprintRow struct {
	NodeID    uuid.UUID
	RevokedAt *time.Time
}

// Backs the agentMTLS middleware's identity-binding step. Resolves a
// SHA-256 fingerprint (32 raw bytes) to its bound node and revocation
// status. The middleware enforces revocation policy in Go; this query
// returns the row as recorded.
func (q *Queries) LookupAgentCertByFingerprint(ctx context.Context, fingerprintSha256 []byte) (LookupAgentCertByFingerprintRow, error) {
	row := q.db.QueryRow(ctx, lookupAgentCertByFingerprint, fingerprintSha256)
	var i LookupAgentCertByFingerprintRow
	err := row.Scan(&i.NodeID, &i.RevokedAt)
	return i, err
}

const nodeHasActiveCert = `-- name: NodeHasActiveCert :one
select exists(
    select 1
    from agent_certs
    where node_id = $1
      and revoked_at is null
)::boolean
`

// Used by the Step 2 redemption handler to detect node-name conflicts
// before signing a fresh cert. "Active" means revoked_at IS NULL —
// a revoked cert does NOT block reuse of the node row (the operator
// already invalidated it, fresh bootstrap is the recovery path).
// Returns false when either no cert row exists for the node OR all
// existing certs have been revoked.
func (q *Queries) NodeHasActiveCert(ctx context.Context, nodeID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, nodeHasActiveCert, nodeID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
