// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createApiToken = `-- name: CreateApiToken :one
insert into api_tokens (
    id, user_id, name,
    token_hash, prefix,
    expires_at
)
values (
    $1, $2, $3,
    $4, $5,
    $6
)
returning id, user_id, name, token_hash, prefix, scopes, last_used_at, expires_at, revoked_at, created_at
`

type CreateApiTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	TokenHash []byte
	Prefix    string
	ExpiresAt *time.Time
}

func (q *Queries) CreateApiToken(ctx context.Context, arg CreateApiTokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createApiToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getApiTokenByHash = `-- name: GetApiTokenByHash :one
select id, user_id, name, token_hash, prefix, scopes, last_used_at, expires_at, revoked_at, created_at
from api_tokens
where token_hash = $1
  and revoked_at is null
  and (expires_at is null or expires_at > now())
`

// Used by the authn middleware on every API-token request. Excludes
// revoked and expired tokens at the SQL layer — a hit means the token
// is presently usable. The caller still type-checks pgx.ErrNoRows and
// maps it to ErrInvalidToken.
func (q *Queries) GetApiTokenByHash(ctx context.Context, tokenHash []byte) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getApiTokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getApiTokenByID = `-- name: GetApiTokenByID :one
select id, user_id, name, token_hash, prefix, scopes, last_used_at, expires_at, revoked_at, created_at
from api_tokens
where id = $1
`

// Includes revoked and expired rows; the caller decides what to do.
// Used by the self-service DELETE handler to scope by id+owner.
func (q *Queries) GetApiTokenByID(ctx context.Context, id uuid.UUID) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getApiTokenByID, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listApiTokensByUser = `-- name: ListApiTokensByUser :many
select id, user_id, name, token_hash, prefix, scopes, last_used_at, expires_at, revoked_at, created_at
from api_tokens
where user_id = $1
  and ($2::boolean or revoked_at is null)
  and (
    $3::timestamptz is null
    or (created_at, id) > (
      $3::timestamptz,
      $4::uuid
    )
  )
order by created_at, id
limit $5
`

type ListApiTokensByUserParams struct {
	UserID          uuid.UUID
	IncludeRevoked  bool
	CursorCreatedAt *time.Time
	CursorID        *uuid.UUID
	LimitCount      int32
}

// Cursor pagination. include_revoked toggles whether revoked
// rows are surfaced (default false at the API edge); expired-but-not-revoked
// rows are always included so the UI can explain why a token stopped
// working. Both /v1/users/me/api-tokens and /v1/users/{id}/api-tokens use
// this query.
// Caller passes limit_count = clamp(limit, 1, 200).
func (q *Queries) ListApiTokensByUser(ctx context.Context, arg ListApiTokensByUserParams) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listApiTokensByUser,
		arg.UserID,
		arg.IncludeRevoked,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.Scopes,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiToken = `-- name: RevokeApiToken :exec
update api_tokens
set revoked_at = now()
where id = $1
  and revoked_at is null
`

// Idempotent: re-revoking a token is a no-op.
func (q *Queries) RevokeApiToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeApiToken, id)
	return err
}

const revokeApiTokensForUser = `-- name: RevokeApiTokensForUser :exec
update api_tokens
set revoked_at = now()
where user_id = $1
  and revoked_at is null
`

// Bulk-revokes every still-active token belonging to a user. Used by
// the user-delete handler so a soft-deleted user cannot continue to
// authenticate via a long-lived API token.
func (q *Queries) RevokeApiTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeApiTokensForUser, userID)
	return err
}

const touchApiToken = `-- name: TouchApiToken :exec
update api_tokens
set last_used_at = now()
where id = $1
`

func (q *Queries) TouchApiToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchApiToken, id)
	return err
}
