// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ca_certs.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCACert = `-- name: CreateCACert :one
insert into ca_certs (
    id, cert_pem, key_pem, fingerprint_sha256,
    not_before, not_after, active
)
values (
    $1, $2, $3, $4,
    $5, $6, true
)
returning id, cert_pem, key_pem, fingerprint_sha256, not_before, not_after, active, created_at
`

type CreateCACertParams struct {
	ID                uuid.UUID
	CertPem           []byte
	KeyPem            []byte
	FingerprintSha256 []byte
	NotBefore         time.Time
	NotAfter          time.Time
}

// Idempotent at the row level via the uq_ca_certs_active partial
// unique index — a second active row insert returns 23505, which the
// CA bootstrap hook traps to fetch the winner race-
// safety semantics.
func (q *Queries) CreateCACert(ctx context.Context, arg CreateCACertParams) (CaCert, error) {
	row := q.db.QueryRow(ctx, createCACert,
		arg.ID,
		arg.CertPem,
		arg.KeyPem,
		arg.FingerprintSha256,
		arg.NotBefore,
		arg.NotAfter,
	)
	var i CaCert
	err := row.Scan(
		&i.ID,
		&i.CertPem,
		&i.KeyPem,
		&i.FingerprintSha256,
		&i.NotBefore,
		&i.NotAfter,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateCACerts = `-- name: DeactivateCACerts :exec
update ca_certs set active = false where active = true
`

// Future rotation step (not invoked in Step 1). Marks every active row
// inactive so a new active row can be inserted under the partial
// unique index. Held in Step 1 as Step 2/3 dependency.
func (q *Queries) DeactivateCACerts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateCACerts)
	return err
}

const getActiveCACert = `-- name: GetActiveCACert :one
select id, cert_pem, key_pem, fingerprint_sha256, not_before, not_after, active, created_at
from ca_certs
where active = true
`

// Returns the single active cluster CA row. /v1/ca handler uses this
// to project to the public ClusterCA view (cert_pem + fingerprint
// only — key_pem stays server-side). Step 2 CSR signing path uses
// this to load the signer keypair into memory at request time.
func (q *Queries) GetActiveCACert(ctx context.Context) (CaCert, error) {
	row := q.db.QueryRow(ctx, getActiveCACert)
	var i CaCert
	err := row.Scan(
		&i.ID,
		&i.CertPem,
		&i.KeyPem,
		&i.FingerprintSha256,
		&i.NotBefore,
		&i.NotAfter,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
