// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cluster_settings.sql

package store

import (
	"context"
)

const clearDefaultPoolName = `-- name: ClearDefaultPoolName :exec
update cluster_settings
set default_pool_name = null
where id = 1
`

// Clears the cluster default-pool reference. VM create without --pool
// afterwards returns default_pool_not_set until a new default is set.
func (q *Queries) ClearDefaultPoolName(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearDefaultPoolName)
	return err
}

const getClusterSettings = `-- name: GetClusterSettings :one
select id, default_pool_name, created_at, updated_at
from cluster_settings
where id = 1
`

// Returns the singleton cluster_settings row. The migration seeds the
// row at id=1 with NULL default_pool_name; this query never returns
// pgx.ErrNoRows in a healthy schema.
func (q *Queries) GetClusterSettings(ctx context.Context) (ClusterSetting, error) {
	row := q.db.QueryRow(ctx, getClusterSettings)
	var i ClusterSetting
	err := row.Scan(
		&i.ID,
		&i.DefaultPoolName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setDefaultPoolName = `-- name: SetDefaultPoolName :exec
update cluster_settings
set default_pool_name = $1
where id = 1
`

// Sets the cluster's default pool name. The handler validates beforehand
// that at least one pool instance with this name exists.
func (q *Queries) SetDefaultPoolName(ctx context.Context, defaultPoolName *string) error {
	_, err := q.db.Exec(ctx, setDefaultPoolName, defaultPoolName)
	return err
}
