// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: firmwares.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countTemplatesForFirmware = `-- name: CountTemplatesForFirmware :one
select count(*)::bigint as template_count
from templates
where firmware_id = $1::uuid
  and deleted_at is null
`

// Precheck before DELETE /v1/firmwares/{id}: counts active templates
// that pin the firmware. The FK uses ON DELETE SET NULL — at the DB
// level the delete would succeed and silently null out the templates'
// firmware_id. The CP-level policy is to require the operator to
// explicitly clear the pin first, so we block the delete with a 409
// whenever any active template still references the firmware.
func (q *Queries) CountTemplatesForFirmware(ctx context.Context, firmwareID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTemplatesForFirmware, firmwareID)
	var template_count int64
	err := row.Scan(&template_count)
	return template_count, err
}

const countVMsForFirmware = `-- name: CountVMsForFirmware :one
select count(*)::bigint as vm_count
from vms
where firmware_id = $1::uuid
  and deleted_at is null
`

// Precheck before DELETE /v1/firmwares/{id}: counts active vms that
// still reference the firmware. Soft-deleted vms are excluded — a
// removed VM's firmware pin is no longer load-bearing. The FK uses
// ON DELETE RESTRICT, so this check also avoids the SQL-level error
// path; the handler surfaces 409 with a typed payload instead.
func (q *Queries) CountVMsForFirmware(ctx context.Context, firmwareID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVMsForFirmware, firmwareID)
	var vm_count int64
	err := row.Scan(&vm_count)
	return vm_count, err
}

const createFirmware = `-- name: CreateFirmware :one
insert into firmwares (
    id,
    name,
    architecture,
    type,
    version,
    secure_boot,
    is_default
)
values (
    $1,
    $2,
    $3,
    $4,
    $5::text,
    $6,
    $7
)
returning id, name, architecture, type, version, secure_boot, is_default, created_at, updated_at
`

type CreateFirmwareParams struct {
	ID           uuid.UUID
	Name         string
	Architecture CpuArch
	Type         FirmwareType
	Version      *string
	SecureBoot   bool
	IsDefault    bool
}

// Identity-and-flag columns only. The CP API treats firmwares as flat
// metadata records — per-node availability lives in node_firmwares and
// is populated by the future heartbeat receiver, not by this query.
func (q *Queries) CreateFirmware(ctx context.Context, arg CreateFirmwareParams) (Firmware, error) {
	row := q.db.QueryRow(ctx, createFirmware,
		arg.ID,
		arg.Name,
		arg.Architecture,
		arg.Type,
		arg.Version,
		arg.SecureBoot,
		arg.IsDefault,
	)
	var i Firmware
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Architecture,
		&i.Type,
		&i.Version,
		&i.SecureBoot,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFirmware = `-- name: DeleteFirmware :exec
delete from firmwares
where id = $1
`

// Hard delete (firmwares has no soft-delete column). Callers run the
// vms / templates count prechecks inside the same transaction so a
// delete that would orphan a template firmware reference (FK is SET
// NULL) or fail with a 23503 from vms.firmware_id (FK is RESTRICT) is
// surfaced as a 409 conflict instead.
func (q *Queries) DeleteFirmware(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFirmware, id)
	return err
}

const getDefaultFirmwareForArchAndType = `-- name: GetDefaultFirmwareForArchAndType :one
select id, name, architecture, type, version, secure_boot, is_default, created_at, updated_at
from firmwares
where architecture = $1
  and type = $2
  and is_default = true
`

type GetDefaultFirmwareForArchAndTypeParams struct {
	Architecture CpuArch
	Type         FirmwareType
}

// Used by the Create / Update precheck when is_default=true: returns
// the existing default firmware for an (architecture, type) pair, or
// pgx.ErrNoRows when none exists. The unique partial index
// uq_firmwares_default also enforces the invariant at the DB level,
// but the precheck gives a nicer 409 path with
// details.existing_firmware_id and avoids racing with the constraint
// at handler-write time.
func (q *Queries) GetDefaultFirmwareForArchAndType(ctx context.Context, arg GetDefaultFirmwareForArchAndTypeParams) (Firmware, error) {
	row := q.db.QueryRow(ctx, getDefaultFirmwareForArchAndType, arg.Architecture, arg.Type)
	var i Firmware
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Architecture,
		&i.Type,
		&i.Version,
		&i.SecureBoot,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFirmwareByID = `-- name: GetFirmwareByID :one
select id, name, architecture, type, version, secure_boot, is_default, created_at, updated_at
from firmwares
where id = $1
`

// firmwares has no soft-delete column; rows are removed via
// DeleteFirmware (hard delete). FK references in vms (RESTRICT) and
// templates (SET NULL) keep dependent state consistent at the DB level;
// the API blocks the operation up-front via DELETE prechecks.
func (q *Queries) GetFirmwareByID(ctx context.Context, id uuid.UUID) (Firmware, error) {
	row := q.db.QueryRow(ctx, getFirmwareByID, id)
	var i Firmware
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Architecture,
		&i.Type,
		&i.Version,
		&i.SecureBoot,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFirmwares = `-- name: ListFirmwares :many
select id, name, architecture, type, version, secure_boot, is_default, created_at, updated_at
from firmwares
where ($1::cpu_arch    is null or architecture = $1::cpu_arch)
  and ($2::firmware_type        is null or type         = $2::firmware_type)
  and (
    $3::timestamptz is null
    or (created_at, id) > (
      $3::timestamptz,
      $4::uuid
    )
  )
order by created_at, id
limit $5
`

type ListFirmwaresParams struct {
	Architecture    *CpuArch
	Type            *FirmwareType
	CursorCreatedAt *time.Time
	CursorID        *uuid.UUID
	LimitCount      int32
}

// Optional ?architecture and ?type filters. Cursor pagination.
func (q *Queries) ListFirmwares(ctx context.Context, arg ListFirmwaresParams) ([]Firmware, error) {
	rows, err := q.db.Query(ctx, listFirmwares,
		arg.Architecture,
		arg.Type,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Firmware{}
	for rows.Next() {
		var i Firmware
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Architecture,
			&i.Type,
			&i.Version,
			&i.SecureBoot,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupFirmwareByCatalog = `-- name: LookupFirmwareByCatalog :one
select id
from firmwares
where name = $1
  and architecture = $2
  and type = $3
`

type LookupFirmwareByCatalogParams struct {
	Name         string
	Architecture CpuArch
	Type         FirmwareType
}

// Backs the heartbeat receiver's firmware-projection step. Resolves a
// (name, architecture, type) triple reported by the agent to a
// firmware_id. ErrNoRows means the operator has not registered this
// firmware in the catalogue; the handler then skips the entry with a
// WARN log instead of auto-registering it.
func (q *Queries) LookupFirmwareByCatalog(ctx context.Context, arg LookupFirmwareByCatalogParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lookupFirmwareByCatalog, arg.Name, arg.Architecture, arg.Type)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateFirmware = `-- name: UpdateFirmware :one
update firmwares
set name        = $1,
    version     = $2::text,
    secure_boot = $3,
    is_default  = $4
where id = $5
returning id, name, architecture, type, version, secure_boot, is_default, created_at, updated_at
`

type UpdateFirmwareParams struct {
	Name       string
	Version    *string
	SecureBoot bool
	IsDefault  bool
	ID         uuid.UUID
}

// Caller merges the patch with the current row before issuing this
// query (the same pattern as UpdateNetwork / UpdateStoragePool). The
// `architecture` and `type` columns are intentionally absent from the
// SET list — they are API-immutable and changing them would invalidate
// the (architecture, type) default-uniqueness invariant.
func (q *Queries) UpdateFirmware(ctx context.Context, arg UpdateFirmwareParams) (Firmware, error) {
	row := q.db.QueryRow(ctx, updateFirmware,
		arg.Name,
		arg.Version,
		arg.SecureBoot,
		arg.IsDefault,
		arg.ID,
	)
	var i Firmware
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Architecture,
		&i.Type,
		&i.Version,
		&i.SecureBoot,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
