// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const beginIdempotencyKey = `-- name: BeginIdempotencyKey :one
insert into idempotency_keys (
    key, user_id, request_method, request_path, request_hash, expires_at
) values (
    $1, $2, $3, $4, $5, $6
)
on conflict (key) do nothing
returning key, user_id, request_method, request_path, request_hash, response_status, response_headers, response_body, state, created_at, completed_at, expires_at
`

type BeginIdempotencyKeyParams struct {
	Key           string
	UserID        *uuid.UUID
	RequestMethod string
	RequestPath   string
	RequestHash   []byte
	ExpiresAt     time.Time
}

// Inserts a fresh in_flight row. Returns pgx.ErrNoRows when another
// caller has already inserted this key — the caller must re-issue
// GetIdempotencyKey to read whatever they ended up with.
func (q *Queries) BeginIdempotencyKey(ctx context.Context, arg BeginIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, beginIdempotencyKey,
		arg.Key,
		arg.UserID,
		arg.RequestMethod,
		arg.RequestPath,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.RequestMethod,
		&i.RequestPath,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.State,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
update idempotency_keys
set state            = 'completed',
    response_status  = $1,
    response_headers = $2,
    response_body    = $3,
    completed_at     = now()
where key = $4
  and state = 'in_flight'
`

type CompleteIdempotencyKeyParams struct {
	ResponseStatus  *int32
	ResponseHeaders []byte
	ResponseBody    []byte
	Key             string
}

// Marks an in_flight row as completed and stores the cached response.
// The state='in_flight' guard prevents a late-arriving Complete from
// clobbering an already-completed (or reclaimed) row.
func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.Key,
	)
	return err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
delete from idempotency_keys
where expires_at < now()
`

// Cleanup hook for the future maintenance loop. Not wired up yet.
func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
delete from idempotency_keys
where key = $1
  and state = 'in_flight'
`

// Removes an in_flight row when the wrapped handler returns a non-2xx
// response. The state guard avoids racing with a Complete that already
// landed (which would mean the row is no longer ours to delete).
func (q *Queries) DeleteIdempotencyKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey, key)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one

select key, user_id, request_method, request_path, request_hash, response_status, response_headers, response_body, state, created_at, completed_at, expires_at
from idempotency_keys
where key = $1
`

// Idempotency-Key middleware queries against the idempotency_keys table
// created in 00001_init.sql. The middleware contract:
//
//  1. Get → check for an existing row keyed by the client-supplied key.
//  2. If absent, Begin atomically inserts an in_flight row. ON CONFLICT
//     DO NOTHING returns no row when a concurrent caller already
//     claimed the key; the middleware then re-runs Get and treats the
//     existing row as authoritative.
//  3. If present and expired, Reclaim overwrites the row in place under
//     WHERE expires_at < now() so a row that just got refreshed by a
//     concurrent caller is never clobbered.
//  4. After the wrapped handler finishes, Complete records the cached
//     response and flips state to 'completed'.
func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.RequestMethod,
		&i.RequestPath,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.State,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const reclaimIdempotencyKey = `-- name: ReclaimIdempotencyKey :one
update idempotency_keys
set user_id          = $1,
    request_method   = $2,
    request_path     = $3,
    request_hash     = $4,
    response_status  = null,
    response_headers = null,
    response_body    = null,
    state            = 'in_flight',
    created_at       = now(),
    completed_at     = null,
    expires_at       = $5
where key = $6
  and expires_at < now()
returning key, user_id, request_method, request_path, request_hash, response_status, response_headers, response_body, state, created_at, completed_at, expires_at
`

type ReclaimIdempotencyKeyParams struct {
	UserID        *uuid.UUID
	RequestMethod string
	RequestPath   string
	RequestHash   []byte
	ExpiresAt     time.Time
	Key           string
}

// Overwrites an expired row in place. Returns pgx.ErrNoRows when a
// concurrent caller already reclaimed (or the row no longer satisfies
// expires_at < now()).
func (q *Queries) ReclaimIdempotencyKey(ctx context.Context, arg ReclaimIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, reclaimIdempotencyKey,
		arg.UserID,
		arg.RequestMethod,
		arg.RequestPath,
		arg.RequestHash,
		arg.ExpiresAt,
		arg.Key,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.RequestMethod,
		&i.RequestPath,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.State,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}
