// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: join_tokens.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const countJoinTokenConsumptions = `-- name: CountJoinTokenConsumptions :one
select count(*)::bigint
from join_token_consumptions
where join_token_id = $1
`

// Used by Step 2 redemption to enforce max_uses + by the get handler
// to surface consumption_count on а single-row lookup.
func (q *Queries) CountJoinTokenConsumptions(ctx context.Context, joinTokenID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countJoinTokenConsumptions, joinTokenID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createJoinToken = `-- name: CreateJoinToken :one
insert into join_tokens (
    id, token_hash, intended_node_name,
    created_by_user_id, expires_at, max_uses
)
values (
    $1, $2, $3,
    $4, $5, $6
)
returning id, token_hash, intended_node_name, created_by_user_id, expires_at, max_uses, created_at
`

type CreateJoinTokenParams struct {
	ID               uuid.UUID
	TokenHash        []byte
	IntendedNodeName *string
	CreatedByUserID  *uuid.UUID
	ExpiresAt        time.Time
	MaxUses          *int32
}

// Persists а freshly minted join token. Plaintext is never stored —
// the caller hashes via auth.HashToken before invoking this query.
// intended_node_name + max_uses are validated at the API edge AND by
// SQL CHECK constraints (defense-in-depth).
func (q *Queries) CreateJoinToken(ctx context.Context, arg CreateJoinTokenParams) (JoinToken, error) {
	row := q.db.QueryRow(ctx, createJoinToken,
		arg.ID,
		arg.TokenHash,
		arg.IntendedNodeName,
		arg.CreatedByUserID,
		arg.ExpiresAt,
		arg.MaxUses,
	)
	var i JoinToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.IntendedNodeName,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.CreatedAt,
	)
	return i, err
}

const createJoinTokenConsumption = `-- name: CreateJoinTokenConsumption :one
insert into join_token_consumptions (
    id, join_token_id, consumed_by_node_id, source_ip
)
values (
    $1, $2, $3, $4
)
returning id, join_token_id, consumed_by_node_id, consumed_at, source_ip
`

type CreateJoinTokenConsumptionParams struct {
	ID               uuid.UUID
	JoinTokenID      uuid.UUID
	ConsumedByNodeID *uuid.UUID
	SourceIp         *netip.Addr
}

// Step 2 dependency: redemption handler inserts а consumption row в
// the same TX as agent_certs INSERT + optional node UPSERT. Pre-
// declared в Step 1 so the signature locks early и Step 2 only
// changes call sites.
func (q *Queries) CreateJoinTokenConsumption(ctx context.Context, arg CreateJoinTokenConsumptionParams) (JoinTokenConsumption, error) {
	row := q.db.QueryRow(ctx, createJoinTokenConsumption,
		arg.ID,
		arg.JoinTokenID,
		arg.ConsumedByNodeID,
		arg.SourceIp,
	)
	var i JoinTokenConsumption
	err := row.Scan(
		&i.ID,
		&i.JoinTokenID,
		&i.ConsumedByNodeID,
		&i.ConsumedAt,
		&i.SourceIp,
	)
	return i, err
}

const getJoinTokenByHash = `-- name: GetJoinTokenByHash :one
select id, token_hash, intended_node_name, created_by_user_id, expires_at, max_uses, created_at
from join_tokens
where token_hash = $1
  and expires_at > now()
`

// Non-locking read for callers that need а token row outside an
// exclusive transaction. Filters expired tokens at SQL так а fresh
// read never returns а usable-but-expired row. Step 2 redemption
// uses GetJoinTokenByHashForUpdate instead (acquires а row lock for
// race-safe max_uses enforcement). pgx.ErrNoRows ⇒ ErrTokenInvalid.
func (q *Queries) GetJoinTokenByHash(ctx context.Context, tokenHash []byte) (JoinToken, error) {
	row := q.db.QueryRow(ctx, getJoinTokenByHash, tokenHash)
	var i JoinToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.IntendedNodeName,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.CreatedAt,
	)
	return i, err
}

const getJoinTokenByHashForUpdate = `-- name: GetJoinTokenByHashForUpdate :one
select id, token_hash, intended_node_name, created_by_user_id, expires_at, max_uses, created_at
from join_tokens
where token_hash = $1
  and expires_at > now()
for update
`

// Row-locking variant used by the Step 2 redemption handler. Acquires
// а FOR UPDATE lock so concurrent redemptions on the same token
// queue, then race-fairly observe each other's consumption count.
// Preserves the expires_at filter — an already-expired token surfaces
// as ErrNoRows и no lock is held. pgx.ErrNoRows ⇒ ErrTokenInvalid.
func (q *Queries) GetJoinTokenByHashForUpdate(ctx context.Context, tokenHash []byte) (JoinToken, error) {
	row := q.db.QueryRow(ctx, getJoinTokenByHashForUpdate, tokenHash)
	var i JoinToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.IntendedNodeName,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.CreatedAt,
	)
	return i, err
}

const getJoinTokenByID = `-- name: GetJoinTokenByID :one
select id, token_hash, intended_node_name, created_by_user_id, expires_at, max_uses, created_at
from join_tokens
where id = $1
`

// Includes expired rows; the caller (admin handler) decides what к do.
func (q *Queries) GetJoinTokenByID(ctx context.Context, id uuid.UUID) (JoinToken, error) {
	row := q.db.QueryRow(ctx, getJoinTokenByID, id)
	var i JoinToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.IntendedNodeName,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.CreatedAt,
	)
	return i, err
}

const listJoinTokenConsumptions = `-- name: ListJoinTokenConsumptions :many
select id, join_token_id, consumed_by_node_id, consumed_at, source_ip
from join_token_consumptions
where join_token_id = $1
  and (
    $2::timestamptz is null
    or (consumed_at, id) > (
      $2::timestamptz,
      $3::uuid
    )
  )
order by consumed_at, id
limit $4
`

type ListJoinTokenConsumptionsParams struct {
	JoinTokenID      uuid.UUID
	CursorConsumedAt *time.Time
	CursorID         *uuid.UUID
	LimitCount       int32
}

// Cursor pagination. Chronologically-ordered audit
// entries for а single token. Empty until Step 2 ships redemption.
func (q *Queries) ListJoinTokenConsumptions(ctx context.Context, arg ListJoinTokenConsumptionsParams) ([]JoinTokenConsumption, error) {
	rows, err := q.db.Query(ctx, listJoinTokenConsumptions,
		arg.JoinTokenID,
		arg.CursorConsumedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JoinTokenConsumption{}
	for rows.Next() {
		var i JoinTokenConsumption
		if err := rows.Scan(
			&i.ID,
			&i.JoinTokenID,
			&i.ConsumedByNodeID,
			&i.ConsumedAt,
			&i.SourceIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJoinTokens = `-- name: ListJoinTokens :many
select
    jt.id, jt.token_hash, jt.intended_node_name, jt.created_by_user_id, jt.expires_at, jt.max_uses, jt.created_at,
    (
        select count(*)
        from join_token_consumptions c
        where c.join_token_id = jt.id
    )::bigint as consumption_count
from join_tokens jt
where ($1::boolean or jt.expires_at > now())
  and (
    $2::timestamptz is null
    or (jt.created_at, jt.id) > (
      $2::timestamptz,
      $3::uuid
    )
  )
order by jt.created_at, jt.id
limit $4
`

type ListJoinTokensParams struct {
	IncludeExpired  bool
	CursorCreatedAt *time.Time
	CursorID        *uuid.UUID
	LimitCount      int32
}

type ListJoinTokensRow struct {
	ID               uuid.UUID
	TokenHash        []byte
	IntendedNodeName *string
	CreatedByUserID  *uuid.UUID
	ExpiresAt        time.Time
	MaxUses          *int32
	CreatedAt        time.Time
	ConsumptionCount int64
}

// Cursor pagination. include_expired toggles whether
// expired rows surface (default false; UI / scripts opt in). The
// consumption_count surfaces via correlated subquery — first slice
// has low cardinality, no perf concern.
func (q *Queries) ListJoinTokens(ctx context.Context, arg ListJoinTokensParams) ([]ListJoinTokensRow, error) {
	rows, err := q.db.Query(ctx, listJoinTokens,
		arg.IncludeExpired,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJoinTokensRow{}
	for rows.Next() {
		var i ListJoinTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.IntendedNodeName,
			&i.CreatedByUserID,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.CreatedAt,
			&i.ConsumptionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeJoinToken = `-- name: RevokeJoinToken :exec
update join_tokens
set expires_at = least(expires_at, now())
where id = $1
`

// Sets expires_at to the lesser of its current value и now() — а
// token already в the past stays where it is, а live token jumps к
// the deadline. Idempotent; repeat calls produce no further effect.
func (q *Queries) RevokeJoinToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeJoinToken, id)
	return err
}
