// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locks.sql

package store

import (
	"context"
)

const acquirePlacementLock = `-- name: AcquirePlacementLock :exec

select pg_advisory_xact_lock($1::bigint)
`

// Cluster-wide advisory locks. Keys are dispensed by internal/store/locks.go
// so callers reference а typed constant rather than а raw integer. All
// locks below are transaction-scoped (pg_advisory_xact_lock) — callers
// MUST acquire them inside an InTxWithTx callback и MUST NOT use them
// outside а transaction (autocommit acquires + releases on the same
// statement, which serializes nothing). See locks.go for the namespace
// contract.
// Serializes VM placement decisions cluster-wide. Acquired inside the
// vm.create transaction before SchedulePlacement reads candidate state;
// released automatically on transaction commit/rollback. Caller passes
// store.LockKeyPlacement as @lock_key.
func (q *Queries) AcquirePlacementLock(ctx context.Context, lockKey int64) error {
	_, err := q.db.Exec(ctx, acquirePlacementLock, lockKey)
	return err
}
