// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: networks.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countVMNicsOnNetwork = `-- name: CountVMNicsOnNetwork :one
select count(*)::bigint as nic_count
from vm_nics
where network_id = $1::uuid
  and deleted_at is null
`

// Precheck before DELETE /v1/networks/{id}: counts active vm_nics that
// still reference the network. Soft-deleted NICs are excluded — a
// detached NIC has no live attachment and does not block network
// deletion. The FK uses ON DELETE RESTRICT, so this check also avoids
// the SQL-level error path; we surface 409 with a typed payload
// instead.
func (q *Queries) CountVMNicsOnNetwork(ctx context.Context, networkID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVMNicsOnNetwork, networkID)
	var nic_count int64
	err := row.Scan(&nic_count)
	return nic_count, err
}

const createNetwork = `-- name: CreateNetwork :one
insert into networks (
    id,
    name,
    type,
    bridge_name,
    vlan_tag,
    mtu,
    config
)
values (
    $1,
    $2,
    $3,
    $4,
    $5::int,
    $6,
    $7
)
returning id, name, type, bridge_name, vlan_tag, mtu, config, created_at, updated_at, deleted_at
`

type CreateNetworkParams struct {
	ID         uuid.UUID
	Name       string
	Type       NetworkType
	BridgeName string
	VlanTag    *int32
	Mtu        int32
	Config     []byte
}

// Caller materialises mtu to its API default (1500) when not supplied;
// the column carries a DB-level DEFAULT 1500 since migration 00004 so
// a row that bypasses sqlc still gets a sensible value, but we always
// pass through the API surface explicitly to keep the audit trail
// honest.
func (q *Queries) CreateNetwork(ctx context.Context, arg CreateNetworkParams) (Network, error) {
	row := q.db.QueryRow(ctx, createNetwork,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.BridgeName,
		arg.VlanTag,
		arg.Mtu,
		arg.Config,
	)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BridgeName,
		&i.VlanTag,
		&i.Mtu,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNetworkByID = `-- name: GetNetworkByID :one
select id, name, type, bridge_name, vlan_tag, mtu, config, created_at, updated_at, deleted_at
from networks
where id = $1
  and deleted_at is null
`

func (q *Queries) GetNetworkByID(ctx context.Context, id uuid.UUID) (Network, error) {
	row := q.db.QueryRow(ctx, getNetworkByID, id)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BridgeName,
		&i.VlanTag,
		&i.Mtu,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNetworkByName = `-- name: GetNetworkByName :one
select id, name, type, bridge_name, vlan_tag, mtu, config, created_at, updated_at, deleted_at
from networks
where lower(name) = lower($1)
  and deleted_at is null
`

// Case-insensitive on lower(name) to match the uq_networks_name
// functional index that backs the name-based resolver.
// Used to detect rename collisions on PATCH before issuing the UPDATE
// (handler-side dedup also covers it, but checking up front gives a
// nicer 409 path with no half-applied state). Networks are not yet
// wired into the resolver package, but the index and query are kept
// consistent so a follow-up iteration can drop in ResolveNetwork
// without a second schema pass.
func (q *Queries) GetNetworkByName(ctx context.Context, name string) (Network, error) {
	row := q.db.QueryRow(ctx, getNetworkByName, name)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BridgeName,
		&i.VlanTag,
		&i.Mtu,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listNetworks = `-- name: ListNetworks :many
select id, name, type, bridge_name, vlan_tag, mtu, config, created_at, updated_at, deleted_at
from networks
where deleted_at is null
  and ($1::network_type is null or type = $1::network_type)
  and (
    $2::timestamptz is null
    or (created_at, id) > (
      $2::timestamptz,
      $3::uuid
    )
  )
order by created_at, id
limit $4
`

type ListNetworksParams struct {
	Type            *NetworkType
	CursorCreatedAt *time.Time
	CursorID        *uuid.UUID
	LimitCount      int32
}

// Optional ?type filter (only 'bridge' is currently a meaningful value
// but the column is open to future enum extensions). Cursor pagination.
func (q *Queries) ListNetworks(ctx context.Context, arg ListNetworksParams) ([]Network, error) {
	rows, err := q.db.Query(ctx, listNetworks,
		arg.Type,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Network{}
	for rows.Next() {
		var i Network
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.BridgeName,
			&i.VlanTag,
			&i.Mtu,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNetwork = `-- name: SoftDeleteNetwork :exec
update networks
set deleted_at = now()
where id = $1
  and deleted_at is null
`

func (q *Queries) SoftDeleteNetwork(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteNetwork, id)
	return err
}

const updateNetwork = `-- name: UpdateNetwork :one
update networks
set name        = $1,
    bridge_name = $2,
    vlan_tag    = $3::int,
    mtu         = $4,
    config      = $5
where id = $6
  and deleted_at is null
returning id, name, type, bridge_name, vlan_tag, mtu, config, created_at, updated_at, deleted_at
`

type UpdateNetworkParams struct {
	Name       string
	BridgeName string
	VlanTag    *int32
	Mtu        int32
	Config     []byte
	ID         uuid.UUID
}

// Caller merges the patch with the current row before issuing this
// query (the same pattern as UpdateUser). The `type` column is
// intentionally absent from this query — it is API-immutable and
// changing it would require schema-level coordination with vm_nics.
func (q *Queries) UpdateNetwork(ctx context.Context, arg UpdateNetworkParams) (Network, error) {
	row := q.db.QueryRow(ctx, updateNetwork,
		arg.Name,
		arg.BridgeName,
		arg.VlanTag,
		arg.Mtu,
		arg.Config,
		arg.ID,
	)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BridgeName,
		&i.VlanTag,
		&i.Mtu,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
