// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelActiveMigrationsOnNode = `-- name: CancelActiveMigrationsOnNode :execrows
update migrations
set phase         = 'cancelled',
    error_message = $1::text,
    completed_at  = now()
where phase not in ('completed', 'failed', 'cancelled')
  and (source_node_id = $2::uuid or target_node_id = $2::uuid)
`

type CancelActiveMigrationsOnNodeParams struct {
	Reason string
	NodeID uuid.UUID
}

// Force-delete step. Cancels every active migration with the node as
// source or target. error_message names the cause for audit clarity.
func (q *Queries) CancelActiveMigrationsOnNode(ctx context.Context, arg CancelActiveMigrationsOnNodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelActiveMigrationsOnNode, arg.Reason, arg.NodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cordonNode = `-- name: CordonNode :one
update nodes
set status      = 'cordoned',
    cordoned_at = now()
where id = $1
  and deleted_at is null
returning id, name, architecture, advertised_endpoint, migration_host, migration_port_range_start, migration_port_range_end, status, cordoned_at, cpu_cores_total, cpu_cores_available, cpu_model, cpu_flags, memory_total_mib, memory_available_mib, hugepages_2mib_total, hugepages_1gib_total, kernel_version, qemu_version, numa_topology, capabilities, last_heartbeat_at, agent_version, labels, memory_pressure_since, memory_pressure_count, system_disk_total_bytes, system_disk_available_bytes, system_disk_pressure_since, system_disk_pressure_count, created_at, updated_at, deleted_at
`

// Sets status to 'cordoned' and stamps cordoned_at. Caller is expected
// to gate on valid transitions (idempotent no-op for already-cordoned,
// 409 for gone/draining) before issuing this query.
func (q *Queries) CordonNode(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, cordonNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Architecture,
		&i.AdvertisedEndpoint,
		&i.MigrationHost,
		&i.MigrationPortRangeStart,
		&i.MigrationPortRangeEnd,
		&i.Status,
		&i.CordonedAt,
		&i.CPUCoresTotal,
		&i.CPUCoresAvailable,
		&i.CPUModel,
		&i.CpuFlags,
		&i.MemoryTotalMib,
		&i.MemoryAvailableMib,
		&i.Hugepages2mibTotal,
		&i.Hugepages1gibTotal,
		&i.KernelVersion,
		&i.QEMUVersion,
		&i.NumaTopology,
		&i.Capabilities,
		&i.LastHeartbeatAt,
		&i.AgentVersion,
		&i.Labels,
		&i.MemoryPressureSince,
		&i.MemoryPressureCount,
		&i.SystemDiskTotalBytes,
		&i.SystemDiskAvailableBytes,
		&i.SystemDiskPressureSince,
		&i.SystemDiskPressureCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countActiveMigrationsOnNode = `-- name: CountActiveMigrationsOnNode :one
select count(*)::bigint as active_count
from migrations
where phase not in ('completed', 'failed', 'cancelled')
  and (source_node_id = $1::uuid or target_node_id = $1::uuid)
`

// Active migrations involving the node as either source or target.
// "Active" matches the partial-index predicate on migrations:
// phase not in ('completed', 'failed', 'cancelled').
func (q *Queries) CountActiveMigrationsOnNode(ctx context.Context, nodeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveMigrationsOnNode, nodeID)
	var active_count int64
	err := row.Scan(&active_count)
	return active_count, err
}

const countVMRuntimeOnNode = `-- name: CountVMRuntimeOnNode :one
select count(*)::bigint as runtime_count
from vm_runtime
where current_node_id = $1::uuid
`

// VM runtime rows currently bound to the node via vm_runtime.current_node_id.
// Used as a precheck before DELETE /v1/nodes/{id} (without ?force=true).
func (q *Queries) CountVMRuntimeOnNode(ctx context.Context, nodeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVMRuntimeOnNode, nodeID)
	var runtime_count int64
	err := row.Scan(&runtime_count)
	return runtime_count, err
}

const createNode = `-- name: CreateNode :one
insert into nodes (
    id,
    name,
    architecture,
    advertised_endpoint,
    migration_host,
    migration_port_range_start,
    migration_port_range_end,
    status
)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
returning id, name, architecture, advertised_endpoint, migration_host, migration_port_range_start, migration_port_range_end, status, cordoned_at, cpu_cores_total, cpu_cores_available, cpu_model, cpu_flags, memory_total_mib, memory_available_mib, hugepages_2mib_total, hugepages_1gib_total, kernel_version, qemu_version, numa_topology, capabilities, last_heartbeat_at, agent_version, labels, memory_pressure_since, memory_pressure_count, system_disk_total_bytes, system_disk_available_bytes, system_disk_pressure_since, system_disk_pressure_count, created_at, updated_at, deleted_at
`

type CreateNodeParams struct {
	ID                      uuid.UUID
	Name                    string
	Architecture            CPUArch
	AdvertisedEndpoint      string
	MigrationHost           string
	MigrationPortRangeStart int32
	MigrationPortRangeEnd   int32
	Status                  NodeStatus
}

// Used at agent join time. Capabilities and labels start empty; they are
// filled by subsequent UpdateNodeHeartbeat calls once the agent connects.
func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.ID,
		arg.Name,
		arg.Architecture,
		arg.AdvertisedEndpoint,
		arg.MigrationHost,
		arg.MigrationPortRangeStart,
		arg.MigrationPortRangeEnd,
		arg.Status,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Architecture,
		&i.AdvertisedEndpoint,
		&i.MigrationHost,
		&i.MigrationPortRangeStart,
		&i.MigrationPortRangeEnd,
		&i.Status,
		&i.CordonedAt,
		&i.CPUCoresTotal,
		&i.CPUCoresAvailable,
		&i.CPUModel,
		&i.CpuFlags,
		&i.MemoryTotalMib,
		&i.MemoryAvailableMib,
		&i.Hugepages2mibTotal,
		&i.Hugepages1gibTotal,
		&i.KernelVersion,
		&i.QEMUVersion,
		&i.NumaTopology,
		&i.Capabilities,
		&i.LastHeartbeatAt,
		&i.AgentVersion,
		&i.Labels,
		&i.MemoryPressureSince,
		&i.MemoryPressureCount,
		&i.SystemDiskTotalBytes,
		&i.SystemDiskAvailableBytes,
		&i.SystemDiskPressureSince,
		&i.SystemDiskPressureCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNodeByID = `-- name: GetNodeByID :one
select id, name, architecture, advertised_endpoint, migration_host, migration_port_range_start, migration_port_range_end, status, cordoned_at, cpu_cores_total, cpu_cores_available, cpu_model, cpu_flags, memory_total_mib, memory_available_mib, hugepages_2mib_total, hugepages_1gib_total, kernel_version, qemu_version, numa_topology, capabilities, last_heartbeat_at, agent_version, labels, memory_pressure_since, memory_pressure_count, system_disk_total_bytes, system_disk_available_bytes, system_disk_pressure_since, system_disk_pressure_count, created_at, updated_at, deleted_at
from nodes
where id = $1
  and deleted_at is null
`

func (q *Queries) GetNodeByID(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Architecture,
		&i.AdvertisedEndpoint,
		&i.MigrationHost,
		&i.MigrationPortRangeStart,
		&i.MigrationPortRangeEnd,
		&i.Status,
		&i.CordonedAt,
		&i.CPUCoresTotal,
		&i.CPUCoresAvailable,
		&i.CPUModel,
		&i.CpuFlags,
		&i.MemoryTotalMib,
		&i.MemoryAvailableMib,
		&i.Hugepages2mibTotal,
		&i.Hugepages1gibTotal,
		&i.KernelVersion,
		&i.QEMUVersion,
		&i.NumaTopology,
		&i.Capabilities,
		&i.LastHeartbeatAt,
		&i.AgentVersion,
		&i.Labels,
		&i.MemoryPressureSince,
		&i.MemoryPressureCount,
		&i.SystemDiskTotalBytes,
		&i.SystemDiskAvailableBytes,
		&i.SystemDiskPressureSince,
		&i.SystemDiskPressureCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNodeByName = `-- name: GetNodeByName :one
select id, name, architecture, advertised_endpoint, migration_host, migration_port_range_start, migration_port_range_end, status, cordoned_at, cpu_cores_total, cpu_cores_available, cpu_model, cpu_flags, memory_total_mib, memory_available_mib, hugepages_2mib_total, hugepages_1gib_total, kernel_version, qemu_version, numa_topology, capabilities, last_heartbeat_at, agent_version, labels, memory_pressure_since, memory_pressure_count, system_disk_total_bytes, system_disk_available_bytes, system_disk_pressure_since, system_disk_pressure_count, created_at, updated_at, deleted_at
from nodes
where lower(name) = lower($1)
  and deleted_at is null
`

// Case-insensitive on lower(name) to match the uq_nodes_name functional
// index. Backs ResolveNode in the name-based resolver: every
// /v1/nodes/{id} read and every node referenced by name (cordon /
// uncordon, storage pool ?node= filter, etc.) routes through here when
// the identifier is not a UUID.
func (q *Queries) GetNodeByName(ctx context.Context, name string) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByName, name)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Architecture,
		&i.AdvertisedEndpoint,
		&i.MigrationHost,
		&i.MigrationPortRangeStart,
		&i.MigrationPortRangeEnd,
		&i.Status,
		&i.CordonedAt,
		&i.CPUCoresTotal,
		&i.CPUCoresAvailable,
		&i.CPUModel,
		&i.CpuFlags,
		&i.MemoryTotalMib,
		&i.MemoryAvailableMib,
		&i.Hugepages2mibTotal,
		&i.Hugepages1gibTotal,
		&i.KernelVersion,
		&i.QEMUVersion,
		&i.NumaTopology,
		&i.Capabilities,
		&i.LastHeartbeatAt,
		&i.AgentVersion,
		&i.Labels,
		&i.MemoryPressureSince,
		&i.MemoryPressureCount,
		&i.SystemDiskTotalBytes,
		&i.SystemDiskAvailableBytes,
		&i.SystemDiskPressureSince,
		&i.SystemDiskPressureCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNodeEffectiveByID = `-- name: GetNodeEffectiveByID :one
select id, name, architecture, advertised_endpoint, migration_host, migration_port_range_start, migration_port_range_end, status, cordoned_at, cpu_cores_total, cpu_cores_available, cpu_model, cpu_flags, memory_total_mib, memory_available_mib, hugepages_2mib_total, hugepages_1gib_total, kernel_version, qemu_version, numa_topology, capabilities, last_heartbeat_at, agent_version, labels, memory_pressure_since, memory_pressure_count, system_disk_total_bytes, system_disk_available_bytes, system_disk_pressure_since, system_disk_pressure_count, created_at, updated_at, deleted_at, cpu_cores_effective, memory_effective_mib
from node_effective_availability
where id = $1
  and deleted_at is null
`

// Reads from the node_effective_availability view (00001_init.sql) so
// callers see effective-availability columns alongside the raw
// heartbeat columns. Used by the GET /v1/nodes/{name} handler to
// render the full operator-facing projection. Soft-
// deleted rows are filtered same as GetNodeByID.
func (q *Queries) GetNodeEffectiveByID(ctx context.Context, id uuid.UUID) (NodeEffectiveAvailability, error) {
	row := q.db.QueryRow(ctx, getNodeEffectiveByID, id)
	var i NodeEffectiveAvailability
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Architecture,
		&i.AdvertisedEndpoint,
		&i.MigrationHost,
		&i.MigrationPortRangeStart,
		&i.MigrationPortRangeEnd,
		&i.Status,
		&i.CordonedAt,
		&i.CPUCoresTotal,
		&i.CPUCoresAvailable,
		&i.CPUModel,
		&i.CpuFlags,
		&i.MemoryTotalMib,
		&i.MemoryAvailableMib,
		&i.Hugepages2mibTotal,
		&i.Hugepages1gibTotal,
		&i.KernelVersion,
		&i.QEMUVersion,
		&i.NumaTopology,
		&i.Capabilities,
		&i.LastHeartbeatAt,
		&i.AgentVersion,
		&i.Labels,
		&i.MemoryPressureSince,
		&i.MemoryPressureCount,
		&i.SystemDiskTotalBytes,
		&i.SystemDiskAvailableBytes,
		&i.SystemDiskPressureSince,
		&i.SystemDiskPressureCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CPUCoresEffective,
		&i.MemoryEffectiveMib,
	)
	return i, err
}

const getNodeForHeartbeat = `-- name: GetNodeForHeartbeat :one
select
    id,
    architecture,
    status,
    memory_pressure_since,
    memory_pressure_count,
    system_disk_pressure_since,
    system_disk_pressure_count
from nodes
where id = $1
  and deleted_at is null
`

type GetNodeForHeartbeatRow struct {
	ID                      uuid.UUID
	Architecture            CPUArch
	Status                  NodeStatus
	MemoryPressureSince     *time.Time
	MemoryPressureCount     int32
	SystemDiskPressureSince *time.Time
	SystemDiskPressureCount int32
}

// Pre-flight read for the heartbeat receiver: fetches the immutable
// and policy-relevant fields needed for the architecture / status
// guards plus the current pressure state used by the transition logic.
// Both memory and system_disk pressure live на the row; the receiver
// reads both inside the same transaction as the metric writes.
// Excludes soft-deleted rows (deleted_at IS NOT NULL → 404, as opposed
// to status='gone' which surfaces as 409 node_gone).
func (q *Queries) GetNodeForHeartbeat(ctx context.Context, id uuid.UUID) (GetNodeForHeartbeatRow, error) {
	row := q.db.QueryRow(ctx, getNodeForHeartbeat, id)
	var i GetNodeForHeartbeatRow
	err := row.Scan(
		&i.ID,
		&i.Architecture,
		&i.Status,
		&i.MemoryPressureSince,
		&i.MemoryPressureCount,
		&i.SystemDiskPressureSince,
		&i.SystemDiskPressureCount,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
select id, name, architecture, advertised_endpoint, migration_host, migration_port_range_start, migration_port_range_end, status, cordoned_at, cpu_cores_total, cpu_cores_available, cpu_model, cpu_flags, memory_total_mib, memory_available_mib, hugepages_2mib_total, hugepages_1gib_total, kernel_version, qemu_version, numa_topology, capabilities, last_heartbeat_at, agent_version, labels, memory_pressure_since, memory_pressure_count, system_disk_total_bytes, system_disk_available_bytes, system_disk_pressure_since, system_disk_pressure_count, created_at, updated_at, deleted_at
from nodes
where deleted_at is null
  and ($1::cpu_arch   is null or architecture = $1::cpu_arch)
  and ($2::node_status      is null or status       = $2::node_status)
  and (
    $3::timestamptz is null
    or (created_at, id) > (
      $3::timestamptz,
      $4::uuid
    )
  )
order by created_at, id
limit $5
`

type ListNodesParams struct {
	Architecture    *CPUArch
	Status          *NodeStatus
	CursorCreatedAt *time.Time
	CursorID        *uuid.UUID
	LimitCount      int32
}

// Optional architecture / status filters. Cursor pagination.
func (q *Queries) ListNodes(ctx context.Context, arg ListNodesParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes,
		arg.Architecture,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Architecture,
			&i.AdvertisedEndpoint,
			&i.MigrationHost,
			&i.MigrationPortRangeStart,
			&i.MigrationPortRangeEnd,
			&i.Status,
			&i.CordonedAt,
			&i.CPUCoresTotal,
			&i.CPUCoresAvailable,
			&i.CPUModel,
			&i.CpuFlags,
			&i.MemoryTotalMib,
			&i.MemoryAvailableMib,
			&i.Hugepages2mibTotal,
			&i.Hugepages1gibTotal,
			&i.KernelVersion,
			&i.QEMUVersion,
			&i.NumaTopology,
			&i.Capabilities,
			&i.LastHeartbeatAt,
			&i.AgentVersion,
			&i.Labels,
			&i.MemoryPressureSince,
			&i.MemoryPressureCount,
			&i.SystemDiskTotalBytes,
			&i.SystemDiskAvailableBytes,
			&i.SystemDiskPressureSince,
			&i.SystemDiskPressureCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesEffective = `-- name: ListNodesEffective :many
select id, name, architecture, advertised_endpoint, migration_host, migration_port_range_start, migration_port_range_end, status, cordoned_at, cpu_cores_total, cpu_cores_available, cpu_model, cpu_flags, memory_total_mib, memory_available_mib, hugepages_2mib_total, hugepages_1gib_total, kernel_version, qemu_version, numa_topology, capabilities, last_heartbeat_at, agent_version, labels, memory_pressure_since, memory_pressure_count, system_disk_total_bytes, system_disk_available_bytes, system_disk_pressure_since, system_disk_pressure_count, created_at, updated_at, deleted_at, cpu_cores_effective, memory_effective_mib
from node_effective_availability
where deleted_at is null
  and ($1::cpu_arch   is null or architecture = $1::cpu_arch)
  and ($2::node_status      is null or status       = $2::node_status)
  and (
    $3::timestamptz is null
    or (created_at, id) > (
      $3::timestamptz,
      $4::uuid
    )
  )
order by created_at, id
limit $5
`

type ListNodesEffectiveParams struct {
	Architecture    *CPUArch
	Status          *NodeStatus
	CursorCreatedAt *time.Time
	CursorID        *uuid.UUID
	LimitCount      int32
}

// View-backed variant of ListNodes used by GET /v1/nodes. Returns the
// same row shape as ListNodes plus cpu_cores_effective /
// memory_effective_mib so the operator can compare raw heartbeat
// availability vs the scheduler's view in а single response.
// Filters / pagination semantics identical к ListNodes.
func (q *Queries) ListNodesEffective(ctx context.Context, arg ListNodesEffectiveParams) ([]NodeEffectiveAvailability, error) {
	rows, err := q.db.Query(ctx, listNodesEffective,
		arg.Architecture,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeEffectiveAvailability{}
	for rows.Next() {
		var i NodeEffectiveAvailability
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Architecture,
			&i.AdvertisedEndpoint,
			&i.MigrationHost,
			&i.MigrationPortRangeStart,
			&i.MigrationPortRangeEnd,
			&i.Status,
			&i.CordonedAt,
			&i.CPUCoresTotal,
			&i.CPUCoresAvailable,
			&i.CPUModel,
			&i.CpuFlags,
			&i.MemoryTotalMib,
			&i.MemoryAvailableMib,
			&i.Hugepages2mibTotal,
			&i.Hugepages1gibTotal,
			&i.KernelVersion,
			&i.QEMUVersion,
			&i.NumaTopology,
			&i.Capabilities,
			&i.LastHeartbeatAt,
			&i.AgentVersion,
			&i.Labels,
			&i.MemoryPressureSince,
			&i.MemoryPressureCount,
			&i.SystemDiskTotalBytes,
			&i.SystemDiskAvailableBytes,
			&i.SystemDiskPressureSince,
			&i.SystemDiskPressureCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CPUCoresEffective,
			&i.MemoryEffectiveMib,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleNodes = `-- name: ListStaleNodes :many
select id, name, architecture, advertised_endpoint, migration_host, migration_port_range_start, migration_port_range_end, status, cordoned_at, cpu_cores_total, cpu_cores_available, cpu_model, cpu_flags, memory_total_mib, memory_available_mib, hugepages_2mib_total, hugepages_1gib_total, kernel_version, qemu_version, numa_topology, capabilities, last_heartbeat_at, agent_version, labels, memory_pressure_since, memory_pressure_count, system_disk_total_bytes, system_disk_available_bytes, system_disk_pressure_since, system_disk_pressure_count, created_at, updated_at, deleted_at
from nodes
where deleted_at is null
  and status not in ('gone', 'unreachable')
  and (last_heartbeat_at is null or last_heartbeat_at < $1::timestamptz)
order by last_heartbeat_at nulls first, id
`

// Nodes whose last heartbeat is older than the supplied cutoff, or which
// never heartbeated. Used by the reconciler to flip nodes to 'unreachable'.
// Excludes terminal status 'gone' (post-mortem) and 'unreachable' (already
// flagged). Pending/ready/cordoned/draining nodes ARE candidates for stale
// detection. If node_status gains a new terminal status, update the NOT IN
// list below.
func (q *Queries) ListStaleNodes(ctx context.Context, staleBefore time.Time) ([]Node, error) {
	rows, err := q.db.Query(ctx, listStaleNodes, staleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Architecture,
			&i.AdvertisedEndpoint,
			&i.MigrationHost,
			&i.MigrationPortRangeStart,
			&i.MigrationPortRangeEnd,
			&i.Status,
			&i.CordonedAt,
			&i.CPUCoresTotal,
			&i.CPUCoresAvailable,
			&i.CPUModel,
			&i.CpuFlags,
			&i.MemoryTotalMib,
			&i.MemoryAvailableMib,
			&i.Hugepages2mibTotal,
			&i.Hugepages1gibTotal,
			&i.KernelVersion,
			&i.QEMUVersion,
			&i.NumaTopology,
			&i.Capabilities,
			&i.LastHeartbeatAt,
			&i.AgentVersion,
			&i.Labels,
			&i.MemoryPressureSince,
			&i.MemoryPressureCount,
			&i.SystemDiskTotalBytes,
			&i.SystemDiskAvailableBytes,
			&i.SystemDiskPressureSince,
			&i.SystemDiskPressureCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNodesUnreachable = `-- name: MarkNodesUnreachable :many
update nodes
set status = 'unreachable'
where deleted_at is null
  and status in ('ready', 'pending')
  and (last_heartbeat_at is null or last_heartbeat_at < $1::timestamptz)
returning id, name, last_heartbeat_at
`

type MarkNodesUnreachableRow struct {
	ID              uuid.UUID
	Name            string
	LastHeartbeatAt *time.Time
}

// Reconciler step that demotes stale 'ready' or 'pending' rows к
// 'unreachable'. 'cordoned' and 'draining' are operator-pinned states
// and stay put even when heartbeats lapse — the operator deliberately
// isolated the node, so liveness is not the signal that flips it.
// 'gone' and 'unreachable' are excluded as terminal / already-flagged.
// Returns the affected rows so callers can log id + name + the stale
// timestamp without an extra round-trip.
func (q *Queries) MarkNodesUnreachable(ctx context.Context, staleBefore time.Time) ([]MarkNodesUnreachableRow, error) {
	rows, err := q.db.Query(ctx, markNodesUnreachable, staleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarkNodesUnreachableRow{}
	for rows.Next() {
		var i MarkNodesUnreachableRow
		if err := rows.Scan(&i.ID, &i.Name, &i.LastHeartbeatAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orphanVMRuntimeOnNode = `-- name: OrphanVMRuntimeOnNode :execrows
update vm_runtime
set phase           = 'orphaned',
    current_node_id = null
where current_node_id = $1::uuid
`

// Force-delete step. Marks every vm_runtime row currently on the node
// as 'orphaned' and clears current_node_id. vms.desired_phase is
// intentionally NOT touched (migration 00003): the user still wants
// whatever they wanted before; only the observed runtime is affected.
func (q *Queries) OrphanVMRuntimeOnNode(ctx context.Context, nodeID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, orphanVMRuntimeOnNode, nodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const promoteHealthyNodes = `-- name: PromoteHealthyNodes :many
update nodes
set status = 'ready'
where deleted_at is null
  and status in ('pending', 'unreachable')
  and last_heartbeat_at is not null
  and last_heartbeat_at >= $1::timestamptz
returning id, name, status
`

type PromoteHealthyNodesRow struct {
	ID     uuid.UUID
	Name   string
	Status NodeStatus
}

// Reconciler step that promotes rows к 'ready' once a fresh heartbeat
// lands. Two source states qualify: 'pending' (first heartbeat after
// registration) and 'unreachable' (recovery after a network blip).
// 'cordoned' and 'draining' stay put — only the operator clears those.
// Returns the affected rows so callers can log the transition.
func (q *Queries) PromoteHealthyNodes(ctx context.Context, freshAfter time.Time) ([]PromoteHealthyNodesRow, error) {
	rows, err := q.db.Query(ctx, promoteHealthyNodes, freshAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromoteHealthyNodesRow{}
	for rows.Next() {
		var i PromoteHealthyNodesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNode = `-- name: SoftDeleteNode :exec
update nodes
set deleted_at = now()
where id = $1
  and deleted_at is null
`

func (q *Queries) SoftDeleteNode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteNode, id)
	return err
}

const uncordonNode = `-- name: UncordonNode :one
update nodes
set status      = 'ready',
    cordoned_at = null
where id = $1
  and deleted_at is null
returning id, name, architecture, advertised_endpoint, migration_host, migration_port_range_start, migration_port_range_end, status, cordoned_at, cpu_cores_total, cpu_cores_available, cpu_model, cpu_flags, memory_total_mib, memory_available_mib, hugepages_2mib_total, hugepages_1gib_total, kernel_version, qemu_version, numa_topology, capabilities, last_heartbeat_at, agent_version, labels, memory_pressure_since, memory_pressure_count, system_disk_total_bytes, system_disk_available_bytes, system_disk_pressure_since, system_disk_pressure_count, created_at, updated_at, deleted_at
`

// Returns the node to 'ready' and clears cordoned_at. Caller is expected
// to gate on valid transitions (idempotent no-op for already-ready, 409
// for pending/unreachable/draining/gone) before issuing this query.
func (q *Queries) UncordonNode(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, uncordonNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Architecture,
		&i.AdvertisedEndpoint,
		&i.MigrationHost,
		&i.MigrationPortRangeStart,
		&i.MigrationPortRangeEnd,
		&i.Status,
		&i.CordonedAt,
		&i.CPUCoresTotal,
		&i.CPUCoresAvailable,
		&i.CPUModel,
		&i.CpuFlags,
		&i.MemoryTotalMib,
		&i.MemoryAvailableMib,
		&i.Hugepages2mibTotal,
		&i.Hugepages1gibTotal,
		&i.KernelVersion,
		&i.QEMUVersion,
		&i.NumaTopology,
		&i.Capabilities,
		&i.LastHeartbeatAt,
		&i.AgentVersion,
		&i.Labels,
		&i.MemoryPressureSince,
		&i.MemoryPressureCount,
		&i.SystemDiskTotalBytes,
		&i.SystemDiskAvailableBytes,
		&i.SystemDiskPressureSince,
		&i.SystemDiskPressureCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateNodeHeartbeat = `-- name: UpdateNodeHeartbeat :exec
update nodes
set
    last_heartbeat_at           = now(),
    agent_version               = $1,
    migration_host              = $2,
    migration_port_range_start  = $3,
    migration_port_range_end    = $4,
    cpu_cores_total             = $5,
    cpu_cores_available         = $6,
    cpu_model                   = $7,
    cpu_flags                   = $8,
    memory_total_mib            = $9,
    memory_available_mib        = $10,
    hugepages_2mib_total        = $11,
    hugepages_1gib_total        = $12,
    kernel_version              = $13,
    qemu_version                = $14,
    numa_topology               = $15,
    capabilities                = $16,
    system_disk_total_bytes     = $17,
    system_disk_available_bytes = $18
where id = $19
  and deleted_at is null
`

type UpdateNodeHeartbeatParams struct {
	AgentVersion             *string
	MigrationHost            string
	MigrationPortRangeStart  int32
	MigrationPortRangeEnd    int32
	CPUCoresTotal            *int32
	CPUCoresAvailable        *int32
	CPUModel                 *string
	CpuFlags                 []string
	MemoryTotalMib           *int64
	MemoryAvailableMib       *int64
	Hugepages2mibTotal       *int32
	Hugepages1gibTotal       *int32
	KernelVersion            *string
	QEMUVersion              *string
	NumaTopology             []byte
	Capabilities             []byte
	SystemDiskTotalBytes     *int64
	SystemDiskAvailableBytes *int64
	ID                       uuid.UUID
}

// Called from the agent heartbeat path. Migration capability is included
// because an agent can reconfigure its migration network without rejoining.
// `architecture` is intentionally NOT mutated here — it is immutable
// after registration, and the handler rejects mismatches with 409
// before reaching this update. `labels` is also untouched: heartbeat
// does not carry labels (operator-managed). `status` stays unchanged —
// that is the reconciler's job.
//
// system_disk_{total,available}_bytes write
// raw root-filesystem capacity reported by the agent. Pressure detection
// happens via UpdateNodeSystemDiskPressure inside the same transaction.
func (q *Queries) UpdateNodeHeartbeat(ctx context.Context, arg UpdateNodeHeartbeatParams) error {
	_, err := q.db.Exec(ctx, updateNodeHeartbeat,
		arg.AgentVersion,
		arg.MigrationHost,
		arg.MigrationPortRangeStart,
		arg.MigrationPortRangeEnd,
		arg.CPUCoresTotal,
		arg.CPUCoresAvailable,
		arg.CPUModel,
		arg.CpuFlags,
		arg.MemoryTotalMib,
		arg.MemoryAvailableMib,
		arg.Hugepages2mibTotal,
		arg.Hugepages1gibTotal,
		arg.KernelVersion,
		arg.QEMUVersion,
		arg.NumaTopology,
		arg.Capabilities,
		arg.SystemDiskTotalBytes,
		arg.SystemDiskAvailableBytes,
		arg.ID,
	)
	return err
}

const updateNodeMemoryPressure = `-- name: UpdateNodeMemoryPressure :exec
update nodes
set
    memory_pressure_since = $1::timestamptz,
    memory_pressure_count = $2::int
where id = $3
  and deleted_at is null
`

type UpdateNodeMemoryPressureParams struct {
	MemoryPressureSince *time.Time
	MemoryPressureCount int32
	ID                  uuid.UUID
}

// Persists the memory-pressure transition computed by the heartbeat
// receiver. Memory_pressure_since is NULL
// when the condition is not active; the count increments on every
// below-threshold observation и resets к 0 on an at-or-above-threshold
// observation. Caller runs this inside the same transaction as
// UpdateNodeHeartbeat so the pressure state never drifts ahead of the
// raw metrics that determined it.
func (q *Queries) UpdateNodeMemoryPressure(ctx context.Context, arg UpdateNodeMemoryPressureParams) error {
	_, err := q.db.Exec(ctx, updateNodeMemoryPressure, arg.MemoryPressureSince, arg.MemoryPressureCount, arg.ID)
	return err
}

const updateNodeStatus = `-- name: UpdateNodeStatus :exec
update nodes
set status      = $1,
    cordoned_at = $2::timestamptz
where id = $3
  and deleted_at is null
`

type UpdateNodeStatusParams struct {
	Status     NodeStatus
	CordonedAt *time.Time
	ID         uuid.UUID
}

// Reconciler-driven status transitions. cordoned_at is bumped to now()
// when the new status is 'cordoned' and was previously something else;
// callers pass cordoned_at = NULL to clear it.
func (q *Queries) UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) error {
	_, err := q.db.Exec(ctx, updateNodeStatus, arg.Status, arg.CordonedAt, arg.ID)
	return err
}

const updateNodeSystemDiskPressure = `-- name: UpdateNodeSystemDiskPressure :exec
update nodes
set
    system_disk_pressure_since = $1::timestamptz,
    system_disk_pressure_count = $2::int
where id = $3
  and deleted_at is null
`

type UpdateNodeSystemDiskPressureParams struct {
	SystemDiskPressureSince *time.Time
	SystemDiskPressureCount int32
	ID                      uuid.UUID
}

// Persists the system-disk pressure transition.
// Mirror of UpdateNodeMemoryPressure: NULL pressure_since когда condition
// is not active; count increments on each below-threshold observation,
// resets к 0 on the first at-or-above observation. Runs inside the same
// transaction as UpdateNodeHeartbeat.
func (q *Queries) UpdateNodeSystemDiskPressure(ctx context.Context, arg UpdateNodeSystemDiskPressureParams) error {
	_, err := q.db.Exec(ctx, updateNodeSystemDiskPressure, arg.SystemDiskPressureSince, arg.SystemDiskPressureCount, arg.ID)
	return err
}
