// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_firmwares.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listNodeFirmwares = `-- name: ListNodeFirmwares :many
select
    nf.node_id, nf.firmware_id, nf.code_path, nf.vars_path, nf.available, nf.reported_at,
    f.id, f.name, f.architecture, f.type, f.version, f.secure_boot, f.is_default, f.created_at, f.updated_at
from node_firmwares nf
join firmwares f on f.id = nf.firmware_id
where nf.node_id = $1::uuid
  and (
    $2::timestamptz is null
    or (f.created_at, f.id) > (
      $2::timestamptz,
      $3::uuid
    )
  )
order by f.created_at, f.id
limit $4
`

type ListNodeFirmwaresParams struct {
	NodeID          uuid.UUID
	CursorCreatedAt *time.Time
	CursorID        *uuid.UUID
	LimitCount      int32
}

type ListNodeFirmwaresRow struct {
	NodeFirmware NodeFirmware
	Firmware     Firmware
}

// Backs GET /v1/nodes/{id}/firmwares. Returns one row per
// (node, firmware) pair recorded in node_firmwares, joined with the
// firmwares row so the API can project the nested Firmware view in
// one trip. Cursor pagination — the cursor is anchored
// on the firmwares.created_at + firmwares.id pair (stable across
// heartbeats), not on node_firmwares.reported_at, so a heartbeat
// bumping reported_at does not destabilise an in-flight pagination
// session.
//
// Until the heartbeat receiver lands node_firmwares is empty and
// this query always returns no rows; the endpoint stands so clients
// and tests can exercise the contract end-to-end ahead of the
// ingest path.
func (q *Queries) ListNodeFirmwares(ctx context.Context, arg ListNodeFirmwaresParams) ([]ListNodeFirmwaresRow, error) {
	rows, err := q.db.Query(ctx, listNodeFirmwares,
		arg.NodeID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodeFirmwaresRow{}
	for rows.Next() {
		var i ListNodeFirmwaresRow
		if err := rows.Scan(
			&i.NodeFirmware.NodeID,
			&i.NodeFirmware.FirmwareID,
			&i.NodeFirmware.CodePath,
			&i.NodeFirmware.VarsPath,
			&i.NodeFirmware.Available,
			&i.NodeFirmware.ReportedAt,
			&i.Firmware.ID,
			&i.Firmware.Name,
			&i.Firmware.Architecture,
			&i.Firmware.Type,
			&i.Firmware.Version,
			&i.Firmware.SecureBoot,
			&i.Firmware.IsDefault,
			&i.Firmware.CreatedAt,
			&i.Firmware.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNodeFirmware = `-- name: UpsertNodeFirmware :exec
insert into node_firmwares (
    node_id,
    firmware_id,
    code_path,
    vars_path,
    available,
    reported_at
)
values (
    $1,
    $2,
    $3,
    $4::text,
    $5,
    now()
)
on conflict (node_id, firmware_id) do update
set code_path   = excluded.code_path,
    vars_path   = excluded.vars_path,
    available   = excluded.available,
    reported_at = excluded.reported_at
`

type UpsertNodeFirmwareParams struct {
	NodeID     uuid.UUID
	FirmwareID uuid.UUID
	CodePath   string
	VarsPath   *string
	Available  bool
}

// Heartbeat-driven projection: refresh the (node_id, firmware_id) row
// with the agent-reported paths and bump reported_at. Conflict on the
// composite primary key resolves to UPDATE; this is the only writer
// so race-free.
func (q *Queries) UpsertNodeFirmware(ctx context.Context, arg UpsertNodeFirmwareParams) error {
	_, err := q.db.Exec(ctx, upsertNodeFirmware,
		arg.NodeID,
		arg.FirmwareID,
		arg.CodePath,
		arg.VarsPath,
		arg.Available,
	)
	return err
}
