// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	// Cluster-wide advisory locks. Keys are dispensed by internal/store/locks.go
	// so callers reference a typed constant rather than a raw integer. All
	// locks below are transaction-scoped (pg_advisory_xact_lock) — callers
	// MUST acquire them inside an InTxWithTx callback and MUST NOT use them
	// outside a transaction (autocommit acquires + releases on the same
	// statement, which serializes nothing). See locks.go for the namespace
	// contract.
	// Serializes VM placement decisions cluster-wide. Acquired inside the
	// vm.create transaction before SchedulePlacement reads candidate state;
	// released automatically on transaction commit/rollback. Caller passes
	// store.LockKeyPlacement as @lock_key.
	AcquirePlacementLock(ctx context.Context, lockKey int64) error
	// Inserts a fresh in_flight row. Returns pgx.ErrNoRows when another
	// caller has already inserted this key — the caller must re-issue
	// GetIdempotencyKey to read whatever they ended up with.
	BeginIdempotencyKey(ctx context.Context, arg BeginIdempotencyKeyParams) (IdempotencyKey, error)
	// Force-delete step. Cancels every active migration with the node as
	// source or target. error_message names the cause for audit clarity.
	CancelActiveMigrationsOnNode(ctx context.Context, arg CancelActiveMigrationsOnNodeParams) (int64, error)
	// Cancel a task only while it is still pending. Returns the updated
	// row when status was pending; returns pgx.ErrNoRows for any other
	// state — the caller maps that to a 409 (running cancel is deferred
	// to future work; terminal cancel is idempotent-409).
	CancelTaskIfPending(ctx context.Context, id uuid.UUID) (Task, error)
	// Clears the cluster default-pool reference. VM create without --pool
	// afterwards returns default_pool_not_set until a new default is set.
	ClearDefaultPoolName(ctx context.Context) error
	// INSERT-SELECT clone. The new row is owned by the caller, named by
	// the caller, and starts in visibility='private' (Variant C — same
	// invariant as CreateTemplate). Description falls through to the
	// source's description when the caller omits it. Image-source bundle
	// (url + checksum + format + size), sizing, capabilities, metadata,
	// firmware pin, os_variant, and architecture / os_family are copied
	// verbatim — clone is a metadata copy and does not re-fetch the image.
	//
	// Returns 0 rows when source is missing or soft-deleted (handler maps
	// to 404). uq_templates_name surfaces as 23505 → 409 with a neutral
	// "template with this name already exists" message.
	CloneTemplate(ctx context.Context, arg CloneTemplateParams) (Template, error)
	// Marks an in_flight row as completed and stores the cached response.
	// The state='in_flight' guard prevents a late-arriving Complete from
	// clobbering an already-completed (or reclaimed) row.
	CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error
	// Sets status to 'cordoned' and stamps cordoned_at. Caller is expected
	// to gate on valid transitions (idempotent no-op for already-cordoned,
	// 409 for gone/draining) before issuing this query.
	CordonNode(ctx context.Context, id uuid.UUID) (Node, error)
	// Active migrations involving the node as either source or target.
	// "Active" matches the partial-index predicate on migrations:
	// phase not in ('completed', 'failed', 'cancelled').
	CountActiveMigrationsOnNode(ctx context.Context, nodeID uuid.UUID) (int64, error)
	// Precheck before DELETE /v1/templates/{id}: counts active vms that
	// still reference the template. Soft-deleted vms are excluded — a
	// removed VM has no live consumption of the template's image rec.
	//
	// The vms.template_id FK is ON DELETE SET NULL by design — orphaned
	// VMs continue to run from the cached image blob, since the template
	// was only the recipe used to provision the disk, not a runtime
	// dependency. Hence the API-level policy: deleting a template should
	// be an explicit operator decision, not a silent reference-nulling.
	// This counter is the sole enforcement of that policy (soft-delete
	// bypasses the FK action; vm_disks.source_template_id RESTRICT and
	// node_image_cache CASCADE only fire on a hard delete that this
	// handler never issues).
	CountActiveVMsForTemplate(ctx context.Context, templateID uuid.UUID) (int64, error)
	// Used by the bootstrap-admin path to skip seeding when an admin
	// already exists. Counts non-deleted rows so a soft-deleted admin
	// does not satisfy the precondition.
	CountAdmins(ctx context.Context) (int64, error)
	// Used by Step 2 redemption to enforce max_uses + by the get handler
	// to surface consumption_count on a single-row lookup.
	CountJoinTokenConsumptions(ctx context.Context, joinTokenID uuid.UUID) (int64, error)
	// Counts VMs intended to run on the given node. Used by the placement
	// scheduler for Least-VM-count tie-breaking. Counted by
	// vms.pinned_node_id (intent) rather than vm_runtime.current_node_id
	// (observed) so a burst of concurrent creates targeting the same
	// least-loaded node spread out immediately; vm_runtime rows arrive
	// only after the agent reports them.
	CountRunningVMsByNode(ctx context.Context, nodeID *uuid.UUID) (int64, error)
	// Precheck before DELETE /v1/storage-pools/{id} (Step 6 extended-
	// delete refusal): if > 0, surface 409 pool_in_use.
	CountStorageImagesByPool(ctx context.Context, poolID uuid.UUID) (int64, error)
	// Refcount gate for storage_image:delete handler (Step 9 sync
	// delete). Counts other rows in the same pool that share the
	// checksum, excluding the row about to be deleted. Caller invokes
	// agent.deleteImage only when this returns 0; otherwise the
	// on-disk file stays alive for the surviving sibling rows
	// (content-addressable deduplication).
	CountStorageImagesBySHA256InPool(ctx context.Context, arg CountStorageImagesBySHA256InPoolParams) (int64, error)
	// Precheck before DELETE /v1/templates/{id} (Step 6 extended-delete
	// refusal): if > 0, surface 409 template_in_use.
	CountStorageImagesByTemplate(ctx context.Context, templateID uuid.UUID) (int64, error)
	// Precheck before DELETE /v1/firmwares/{id}: counts active templates
	// that pin the firmware. The FK uses ON DELETE SET NULL — at the DB
	// level the delete would succeed and silently null out the templates'
	// firmware_id. The CP-level policy is to require the operator to
	// explicitly clear the pin first, so we block the delete with a 409
	// whenever any active template still references the firmware.
	CountTemplatesForFirmware(ctx context.Context, firmwareID uuid.UUID) (int64, error)
	// Returns counts of resources owned by user, for the DELETE precheck
	// (cannot delete a user with owned VMs / templates / snapshots).
	// Counts exclude soft-deleted rows.
	// Aliased to silence sqlc 1.31.1 analyzer ambiguity warning. The three
	// subqueries are independent — column qualification is cosmetic.
	CountUserResources(ctx context.Context, userID uuid.UUID) (CountUserResourcesRow, error)
	// Precheck before DELETE /v1/storage-pools/{id}: counts active vm_disks
	// rows that still reference the pool. Soft-deleted disks are excluded
	// — a detached disk has no live attachment and does not block pool
	// deletion. The FK uses ON DELETE RESTRICT, so this check also avoids
	// the SQL-level error path; we surface 409 with a typed payload
	// instead.
	CountVMDisksOnStoragePool(ctx context.Context, storagePoolID uuid.UUID) (int64, error)
	// Precheck before DELETE /v1/networks/{id}: counts active vm_nics that
	// still reference the network. Soft-deleted NICs are excluded — a
	// detached NIC has no live attachment and does not block network
	// deletion. The FK uses ON DELETE RESTRICT, so this check also avoids
	// the SQL-level error path; we surface 409 with a typed payload
	// instead.
	CountVMNicsOnNetwork(ctx context.Context, networkID uuid.UUID) (int64, error)
	// VM runtime rows currently bound to the node via vm_runtime.current_node_id.
	// Used as a precheck before DELETE /v1/nodes/{id} (without ?force=true).
	CountVMRuntimeOnNode(ctx context.Context, nodeID uuid.UUID) (int64, error)
	// Distinct-VM count for a given storage_pool_id, used by
	// storage_pools.delete to refuse deletion of pools backing live VMs.
	// Counts via vm_disks (the only place pool_id lives for a vm) and
	// excludes soft-deleted disks AND soft-deleted VMs.
	CountVMsByPool(ctx context.Context, storagePoolID uuid.UUID) (int64, error)
	// Precheck before DELETE /v1/firmwares/{id}: counts active vms that
	// still reference the firmware. Soft-deleted vms are excluded — a
	// removed VM's firmware pin is no longer load-bearing. The FK uses
	// ON DELETE RESTRICT, so this check also avoids the SQL-level error
	// path; the handler surfaces 409 with a typed payload instead.
	CountVMsForFirmware(ctx context.Context, firmwareID uuid.UUID) (int64, error)
	// Inserts agent cert metadata after Step 2 redemption signs a CSR.
	// The cert PEM itself is NOT stored — returned to the agent in the
	// redemption response, agent persists locally on disk. CP keeps only
	// the metadata (serial, fingerprint, subject DN, validity) for
	// AgentMTLS fingerprint lookup and future revocation tracking. The
	// caller passes serial as DER big-endian bytes (big.Int.Bytes() of
	// the cert's SerialNumber).
	CreateAgentCert(ctx context.Context, arg CreateAgentCertParams) (AgentCert, error)
	CreateApiToken(ctx context.Context, arg CreateApiTokenParams) (ApiToken, error)
	// Idempotent at the row level via the uq_ca_certs_active partial
	// unique index — a second active row insert returns 23505, which the
	// CA bootstrap hook traps to fetch the winner race-
	// safety semantics.
	CreateCACert(ctx context.Context, arg CreateCACertParams) (CaCert, error)
	// Identity-and-flag columns only. The CP API treats firmwares as flat
	// metadata records — per-node availability lives in node_firmwares and
	// is populated by the future heartbeat receiver, not by this query.
	CreateFirmware(ctx context.Context, arg CreateFirmwareParams) (Firmware, error)
	// Persists a freshly minted join token. Plaintext is never stored —
	// the caller hashes via auth.HashToken before invoking this query.
	// intended_node_name + max_uses are validated at the API edge AND by
	// SQL CHECK constraints (defense-in-depth).
	CreateJoinToken(ctx context.Context, arg CreateJoinTokenParams) (JoinToken, error)
	// Step 2 dependency: redemption handler inserts a consumption row in
	// the same TX as agent_certs INSERT + optional node UPSERT. Pre-
	// declared in Step 1 so the signature locks early and Step 2 only
	// changes call sites.
	CreateJoinTokenConsumption(ctx context.Context, arg CreateJoinTokenConsumptionParams) (JoinTokenConsumption, error)
	// Caller materialises mtu to its API default (1500) when not supplied;
	// the column carries a DB-level DEFAULT 1500 since migration 00004 so
	// a row that bypasses sqlc still gets a sensible value, but we always
	// pass through the API surface explicitly to keep the audit trail
	// honest.
	CreateNetwork(ctx context.Context, arg CreateNetworkParams) (Network, error)
	// Used at agent join time. Capabilities and labels start empty; they are
	// filled by subsequent UpdateNodeHeartbeat calls once the agent connects.
	CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	// The storage_image.import worker calls this on terminal-success
	// to project the agent's import result into CP. ON CONFLICT
	// (template_id, pool_id) DO UPDATE: a re-import with
	// rotated content overwrites the row's checksum / size / format so
	// the row tracks the latest authoritative state. The handler's
	// atomic-enqueue tx creates the Task row first; the worker's success
	// projection commits this row in the same final tx as
	// UpdateTaskFinalized.
	CreateStorageImage(ctx context.Context, arg CreateStorageImageParams) (StorageImage, error)
	// Identity-and-config columns only. capacity_bytes / available_bytes /
	// reported_at are agent-reported and never accepted on
	// the API edge — they will be populated through the future heartbeat
	// and scan paths, both of which use UpsertStoragePoolUsage (deferred,
	// not implemented yet).
	CreateStoragePool(ctx context.Context, arg CreateStoragePoolParams) (StoragePool, error)
	// Inserts a fresh task row. The handler runs this in the same SQL
	// transaction as the river job enqueue; the river_job_id is stamped
	// onto the row via UpdateTaskRiverJobID after river.InsertTx returns.
	// result / error / progress / started_at / finished_at default to NULL.
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	// Templates are always created with visibility='private' (variant C of
	// the create-permission model — see CLAUDE.md "Authorization (RBAC)"
	// and ROADMAP). The literal is hard-coded in this INSERT rather than
	// accepted as a parameter so a future call site cannot opt out by
	// mistake; visibility moves only through SetTemplateVisibility, which
	// carries the dedicated `template:set_visibility` permission. Name
	// uniqueness is enforced by uq_templates_name (global, not per-owner)
	// and surfaces as 23505 → 409 in the handler with a neutral
	// "template with this name already exists" message.
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// VMs queries — foundations for the CP-side vm.create / vm.delete
	// vertical slice. Schema-aligned: cpu_cores not "vcpus", memory_mib not
	// "memory_mb", no pool_id/node_id columns on vms (pool comes through
	// vm_disks; current node comes through vm_runtime). The handler boundary
	// translates the simplified API wire shape to and from these column
	// names.
	// Inserts a new vms row. Caller supplies the id explicitly (unified
	// UUID, CP mints / agent uses). desired_phase defaults to 'running'
	// so the operator's "create" intent maps to "VM should run" without a
	// separate state transition.
	CreateVM(ctx context.Context, arg CreateVMParams) (VM, error)
	// vm_disks queries — Phase A foundations. The vms table itself does
	// not carry a pool_id / node_id column (per the original schema design
	// multi-disk VMs span pools and node placement is observed through
	// vm_runtime). Pool persistence lives on vm_disks.storage_pool_id.
	//
	// For MVP each VM has exactly one disk row, sourced from a template,
	// pinned to one storage_pool. CountVMsByPool joins through vm_disks
	// to support the storage_pools.delete extended-refusal check (Phase B).
	// Inserts a single disk row for a vm. Phase B vm.create handler invokes
	// this once per VM (single-disk MVP). Multi-disk callers loop with distinct
	// device_order values.
	CreateVMDisk(ctx context.Context, arg CreateVMDiskParams) (VMDisk, error)
	// Future rotation step (not invoked in Step 1). Marks every active row
	// inactive so a new active row can be inserted under the partial
	// unique index. Held in Step 1 as Step 2/3 dependency.
	DeactivateCACerts(ctx context.Context) error
	// Drops templates.derived_vm_count by one. Called from VMDeleteWorker's
	// success projection inside the same InTx as the soft-delete chain.
	// The decrement is a guarded UPDATE — `where deleted_at is null and
	// derived_vm_count > 0` — so a stale call against a soft-deleted
	// template OR a counter that has already drifted to zero is a silent
	// no-op rather than a 23514 check-constraint violation.
	DecrementTemplateDerivedVMCount(ctx context.Context, id uuid.UUID) error
	// Cleanup hook for the future maintenance loop. Not wired up yet.
	DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error)
	// Cleanup query for the (out-of-scope here) periodic cleanup job. Drops
	// every row whose expiry is older than @cutoff. Returns the number of
	// rows deleted so the job can log progress.
	DeleteExpiredRefreshTokens(ctx context.Context, cutoff time.Time) (int64, error)
	// State-aware retention. The two cutoffs are
	// independent: success rows past @completed_cutoff and failed /
	// cancelled rows past @failed_cutoff are removed in one DELETE. Only
	// finalized rows (finished_at IS NOT NULL) are eligible — the partial
	// index idx_tasks_finished_at supports the scan.
	DeleteExpiredTasks(ctx context.Context, arg DeleteExpiredTasksParams) (int64, error)
	// Hard delete (firmwares has no soft-delete column). Callers run the
	// vms / templates count prechecks inside the same transaction so a
	// delete that would orphan a template firmware reference (FK is SET
	// NULL) or fail with a 23503 from vms.firmware_id (FK is RESTRICT) is
	// surfaced as a 409 conflict instead.
	DeleteFirmware(ctx context.Context, id uuid.UUID) error
	// Removes an in_flight row when the wrapped handler returns a non-2xx
	// response. The state guard avoids racing with a Complete that already
	// landed (which would mean the row is no longer ours to delete).
	DeleteIdempotencyKey(ctx context.Context, key string) error
	DeleteStorageImage(ctx context.Context, id uuid.UUID) error
	// Removes the runtime snapshot. Called by the worker's vm.delete
	// cleanup phase after the agent confirms teardown.
	DeleteVMRuntime(ctx context.Context, vmID uuid.UUID) error
	// Pre-filter for the heartbeat receiver's VM-projection step. Returns
	// only the VM ids that exist in `vms` and are not soft-deleted, so
	// the handler can skip unknown vm_uuids with a WARN instead of taking
	// an FK violation on UpsertVMRuntime. One round-trip vs. N — the
	// heartbeat carries up to a node's worth of VMs.
	FilterExistingVMIDs(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error)
	// Returns the single active cluster CA row. /v1/ca handler uses this
	// to project to the public ClusterCA view (cert_pem + fingerprint
	// only — key_pem stays server-side). Step 2 CSR signing path uses
	// this to load the signer keypair into memory at request time.
	GetActiveCACert(ctx context.Context) (CaCert, error)
	// Used by the authn middleware on every API-token request. Excludes
	// revoked and expired tokens at the SQL layer — a hit means the token
	// is presently usable. The caller still type-checks pgx.ErrNoRows and
	// maps it to ErrInvalidToken.
	GetApiTokenByHash(ctx context.Context, tokenHash []byte) (ApiToken, error)
	// Includes revoked and expired rows; the caller decides what to do.
	// Used by the self-service DELETE handler to scope by id+owner.
	GetApiTokenByID(ctx context.Context, id uuid.UUID) (ApiToken, error)
	// Returns the singleton cluster_settings row. The migration seeds the
	// row at id=1 with NULL default_pool_name; this query never returns
	// pgx.ErrNoRows in a healthy schema.
	GetClusterSettings(ctx context.Context) (ClusterSetting, error)
	// Used by the Create / Update precheck when is_default=true: returns
	// the existing default firmware for an (architecture, type) pair, or
	// pgx.ErrNoRows when none exists. The unique partial index
	// uq_firmwares_default also enforces the invariant at the DB level,
	// but the precheck gives a nicer 409 path with
	// details.existing_firmware_id and avoids racing with the constraint
	// at handler-write time.
	GetDefaultFirmwareForArchAndType(ctx context.Context, arg GetDefaultFirmwareForArchAndTypeParams) (Firmware, error)
	// firmwares has no soft-delete column; rows are removed via
	// DeleteFirmware (hard delete). FK references in vms (RESTRICT) and
	// templates (SET NULL) keep dependent state consistent at the DB level;
	// the API blocks the operation up-front via DELETE prechecks.
	GetFirmwareByID(ctx context.Context, id uuid.UUID) (Firmware, error)
	// Idempotency-Key middleware queries against the idempotency_keys table
	// created in 00001_init.sql. The middleware contract:
	//
	//   1. Get → check for an existing row keyed by the client-supplied key.
	//   2. If absent, Begin atomically inserts an in_flight row. ON CONFLICT
	//      DO NOTHING returns no row when a concurrent caller already
	//      claimed the key; the middleware then re-runs Get and treats the
	//      existing row as authoritative.
	//   3. If present and expired, Reclaim overwrites the row in place under
	//      WHERE expires_at < now() so a row that just got refreshed by a
	//      concurrent caller is never clobbered.
	//   4. After the wrapped handler finishes, Complete records the cached
	//      response and flips state to 'completed'.
	GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error)
	// Non-locking read for callers that need a token row outside an
	// exclusive transaction. Filters expired tokens at SQL so a fresh
	// read never returns a usable-but-expired row. Step 2 redemption
	// uses GetJoinTokenByHashForUpdate instead (acquires a row lock for
	// race-safe max_uses enforcement). pgx.ErrNoRows ⇒ ErrTokenInvalid.
	GetJoinTokenByHash(ctx context.Context, tokenHash []byte) (JoinToken, error)
	// Row-locking variant used by the Step 2 redemption handler. Acquires
	// a FOR UPDATE lock so concurrent redemptions on the same token
	// queue, then race-fairly observe each other's consumption count.
	// Preserves the expires_at filter — an already-expired token surfaces
	// as ErrNoRows and no lock is held. pgx.ErrNoRows ⇒ ErrTokenInvalid.
	GetJoinTokenByHashForUpdate(ctx context.Context, tokenHash []byte) (JoinToken, error)
	// Includes expired rows; the caller (admin handler) decides what to do.
	GetJoinTokenByID(ctx context.Context, id uuid.UUID) (JoinToken, error)
	GetNetworkByID(ctx context.Context, id uuid.UUID) (Network, error)
	// Case-insensitive on lower(name) to match the uq_networks_name
	// functional index that backs the name-based resolver.
	// Used to detect rename collisions on PATCH before issuing the UPDATE
	// (handler-side dedup also covers it, but checking up front gives a
	// nicer 409 path with no half-applied state). Networks are not yet
	// wired into the resolver package, but the index and query are kept
	// consistent so a follow-up iteration can drop in ResolveNetwork
	// without a second schema pass.
	GetNetworkByName(ctx context.Context, name string) (Network, error)
	GetNodeByID(ctx context.Context, id uuid.UUID) (Node, error)
	// Case-insensitive on lower(name) to match the uq_nodes_name functional
	// index. Backs ResolveNode in the name-based resolver: every
	// /v1/nodes/{id} read and every node referenced by name (cordon /
	// uncordon, storage pool ?node= filter, etc.) routes through here when
	// the identifier is not a UUID.
	GetNodeByName(ctx context.Context, name string) (Node, error)
	// Reads from the node_effective_availability view (00001_init.sql) so
	// callers see effective-availability columns alongside the raw
	// heartbeat columns. Used by the GET /v1/nodes/{name} handler to
	// render the full operator-facing projection. Soft-
	// deleted rows are filtered same as GetNodeByID.
	GetNodeEffectiveByID(ctx context.Context, id uuid.UUID) (NodeEffectiveAvailability, error)
	// Pre-flight read for the heartbeat receiver: fetches the immutable
	// and policy-relevant fields needed for the architecture / status
	// guards plus the current pressure state used by the transition logic.
	// Both memory and system_disk pressure live on the row; the receiver
	// reads both inside the same transaction as the metric writes.
	// Excludes soft-deleted rows (deleted_at IS NOT NULL → 404, as opposed
	// to status='gone' which surfaces as 409 node_gone).
	GetNodeForHeartbeat(ctx context.Context, id uuid.UUID) (GetNodeForHeartbeatRow, error)
	// Pre-read for the scan worker's pool disk pressure transition.
	// Mirrors GetNodeForHeartbeat's pressure-state read on the node side.
	// Excludes soft-deleted rows — a scan that lands after the pool is
	// soft-deleted is a no-op overall.
	GetPoolDiskPressureState(ctx context.Context, id uuid.UUID) (GetPoolDiskPressureStateRow, error)
	// View-backed read returning every storage_pools column plus the
	// `available_bytes_effective` synthesized by pool_effective_capacity.
	// Consumed by the GET-by-id handler so operator-facing responses
	// surface both raw and effective bytes.
	GetPoolEffectiveByID(ctx context.Context, id uuid.UUID) (PoolEffectiveCapacity, error)
	// Returns the row regardless of revocation state. The caller inspects
	// revoked_at to detect replay (sentinel for token theft) and expires_at
	// to detect expiry; both are normal control-flow signals, not errors.
	GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	GetStorageImageByID(ctx context.Context, id uuid.UUID) (StorageImage, error)
	// Composite-key lookup. Useful for handlers that need to project the
	// (template, pool) → image relation without scanning the pool list.
	// Returns pgx.ErrNoRows when the image has not been imported yet.
	GetStorageImageByTemplateAndPool(ctx context.Context, arg GetStorageImageByTemplateAndPoolParams) (StorageImage, error)
	GetStoragePoolByID(ctx context.Context, id uuid.UUID) (StoragePool, error)
	GetTask(ctx context.Context, id uuid.UUID) (Task, error)
	// Soft-deleted rows are invisible to every read path; a Get that
	// targets a deleted template returns pgx.ErrNoRows and the handler
	// surfaces 404. The partial index uq_templates_name (where deleted_at
	// is null) means a freed name is reusable immediately after delete.
	GetTemplate(ctx context.Context, id uuid.UUID) (Template, error)
	// Backs ResolveTemplate in the name-based resolver. Case-insensitive
	// on lower(name) to match the uq_templates_name functional
	// index — every /v1/templates/{id} read and every POST body that
	// references a template by name routes through here when the
	// identifier is not a UUID. Visibility is NOT filtered at the SQL
	// layer: callers run their own RBAC / visibility checks after the
	// resolve (e.g. checkTemplateUseAccess) so the handler can return 404
	// not_found for both "missing" and "invisible to you" cases without
	// the resolver leaking the distinction.
	GetTemplateByName(ctx context.Context, name string) (Template, error)
	// Email uniqueness is case-insensitive (uq_users_email on lower(email)).
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetVMByID(ctx context.Context, id uuid.UUID) (VM, error)
	// Used by the create handler for globally-unique-name precheck before
	// the insert (the unique partial index would catch it as a 23505 too,
	// but a friendly 409 with the existing id is preferable). Also backs
	// ResolveVM in the name-based resolver (internal/api/handlers/internal/
	// resolver) — every GET / DELETE on /v1/vms/{id} folds to this query when
	// the identifier is not a UUID. The lookup is case-insensitive to match
	// uq_vms_name on lower(name); the row preserves the operator's chosen
	// casing.
	GetVMByName(ctx context.Context, name string) (VM, error)
	// Read the runtime snapshot for a VM, used by GET /v1/vms/{id} to
	// project a combined desired+observed status. Returns ErrNoRows when
	// the worker has not yet upserted (i.e. the VM is still in
	// desired_phase='running' but the agent hasn't acknowledged).
	GetVMRuntime(ctx context.Context, vmID uuid.UUID) (VMRuntime, error)
	// Bumps templates.derived_vm_count by one. Called from VMCreateWorker's
	// success projection inside the same InTx as UpdateTaskFinalized. The
	// column carries a check (derived_vm_count >= 0) at the schema level;
	// the increment cannot underflow.
	IncrementTemplateDerivedVMCount(ctx context.Context, id uuid.UUID) error
	// Cursor pagination. include_revoked toggles whether revoked
	// rows are surfaced (default false at the API edge); expired-but-not-revoked
	// rows are always included so the UI can explain why a token stopped
	// working. Both /v1/users/me/api-tokens and /v1/users/{id}/api-tokens use
	// this query.
	// Caller passes limit_count = clamp(limit, 1, 200).
	ListApiTokensByUser(ctx context.Context, arg ListApiTokensByUserParams) ([]ApiToken, error)
	// Diagnostic-only sibling for pool disk pressure. Returns pool
	// instances for the given name whose own disk_pressure flag is set —
	// independent of the owning node's pressure status. Pool-scoped
	// pressure is the only condition that excludes a pool independently
	// of its node.
	ListDiskPressuredPoolsByName(ctx context.Context, name string) ([]ListDiskPressuredPoolsByNameRow, error)
	// Joined query used by the scheduler at VM placement time: enumerates
	// pool instances for the given name on nodes that are ready and not
	// cordoned. Returns the pool's effective-capacity row plus the node's
	// effective-availability row in a single round-trip.
	//
	// Sources pool columns from pool_effective_capacity so the scheduler
	// reads `available_bytes_effective` — pool availability with pending-VM-
	// disk accounting. Node columns come from node_effective_availability so
	// `cpu_cores_effective` / `memory_effective_mib` are available with
	// pending-VM accounting too. Both views are supersets of their
	// underlying tables, so the eligibility filters
	// (status = 'ready', cordoned_at IS NULL, deleted_at IS NULL) hold
	// without change. Disk-aware Sub-iteration C consumes both effective
	// columns in `filterByResources` / `scoreResourceAware`.
	ListEligiblePoolsByName(ctx context.Context, name string) ([]ListEligiblePoolsByNameRow, error)
	// Optional ?architecture and ?type filters. Cursor pagination.
	ListFirmwares(ctx context.Context, arg ListFirmwaresParams) ([]Firmware, error)
	// Cursor pagination. Chronologically-ordered audit
	// entries for a single token. Empty until Step 2 ships redemption.
	ListJoinTokenConsumptions(ctx context.Context, arg ListJoinTokenConsumptionsParams) ([]JoinTokenConsumption, error)
	// Cursor pagination. include_expired toggles whether
	// expired rows surface (default false; UI / scripts opt in). The
	// consumption_count surfaces via correlated subquery — first slice
	// has low cardinality, no perf concern.
	ListJoinTokens(ctx context.Context, arg ListJoinTokensParams) ([]ListJoinTokensRow, error)
	// Diagnostic query consumed by the scheduler on the failure path
	// (`len(eligible) == 0` for a pool that does exist somewhere). Returns
	// pool instances for the given name whose owning node would have been
	// eligible except for an active **memory** pressure condition.
	// Same node-status / cordoned / deleted_at filters as
	// ListEligiblePoolsByName, but the memory pressure filter is inverted
	// (memory_pressure_since IS NOT NULL).
	ListMemoryPressuredCandidatesByName(ctx context.Context, name string) ([]ListMemoryPressuredCandidatesByNameRow, error)
	// Optional ?type filter (only 'bridge' is currently a meaningful value
	// but the column is open to future enum extensions). Cursor pagination.
	ListNetworks(ctx context.Context, arg ListNetworksParams) ([]Network, error)
	// Backs GET /v1/nodes/{id}/firmwares. Returns one row per
	// (node, firmware) pair recorded in node_firmwares, joined with the
	// firmwares row so the API can project the nested Firmware view in
	// one trip. Cursor pagination — the cursor is anchored
	// on the firmwares.created_at + firmwares.id pair (stable across
	// heartbeats), not on node_firmwares.reported_at, so a heartbeat
	// bumping reported_at does not destabilise an in-flight pagination
	// session.
	//
	// Until the heartbeat receiver lands node_firmwares is empty and
	// this query always returns no rows; the endpoint stands so clients
	// and tests can exercise the contract end-to-end ahead of the
	// ingest path.
	ListNodeFirmwares(ctx context.Context, arg ListNodeFirmwaresParams) ([]ListNodeFirmwaresRow, error)
	// Optional architecture / status filters. Cursor pagination.
	ListNodes(ctx context.Context, arg ListNodesParams) ([]Node, error)
	// View-backed variant of ListNodes used by GET /v1/nodes. Returns the
	// same row shape as ListNodes plus cpu_cores_effective /
	// memory_effective_mib so the operator can compare raw heartbeat
	// availability vs the scheduler's view in a single response.
	// Filters / pagination semantics identical to ListNodes.
	ListNodesEffective(ctx context.Context, arg ListNodesEffectiveParams) ([]NodeEffectiveAvailability, error)
	// View-backed parallel to ListStoragePools — same optional ?node_id /
	// ?type filters and (created_at, id) cursor pagination,
	// but every row carries `available_bytes_effective`. Soft-deleted rows
	// excluded by construction (view itself emits no rows when raw is
	// soft-deleted — see the WHERE clause on the view).
	ListPoolsEffective(ctx context.Context, arg ListPoolsEffectiveParams) ([]PoolEffectiveCapacity, error)
	// View-backed parallel to ListStoragePoolsByName. Drives the
	// name-aggregated `GET /v1/storage-pools/{name}` projection so each
	// per-node instance carries effective bytes.
	ListPoolsEffectiveByName(ctx context.Context, name string) ([]PoolEffectiveCapacity, error)
	// Returns active storage_pools whose owning node is in a scannable
	// status, excluding pools that already have an in-flight scan task
	// (a `tasks` row of type `storage_pool.scan` in status pending or
	// running referencing the pool). Drives the `storage_pool.scan_trigger`
	// periodic worker: each tick fans out fresh scan tasks only to pools
	// that need a refresh, leaving in-flight scans untouched. Ordering on
	// `p.id` is stable across ticks so log lines correlate predictably.
	ListPoolsNeedingScan(ctx context.Context) ([]ListPoolsNeedingScanRow, error)
	// Nodes whose last heartbeat is older than the supplied cutoff, or which
	// never heartbeated. Used by the reconciler to flip nodes to 'unreachable'.
	// Excludes terminal status 'gone' (post-mortem) and 'unreachable' (already
	// flagged). Pending/ready/cordoned/draining nodes ARE candidates for stale
	// detection. If node_status gains a new terminal status, update the NOT IN
	// list below.
	ListStaleNodes(ctx context.Context, staleBefore time.Time) ([]Node, error)
	// Backs the storageImages.list endpoint. Cursor pagination keyed on
	// (imported_at, id) DESC — the tasks-style direction (newest first).
	ListStorageImagesByPool(ctx context.Context, arg ListStorageImagesByPoolParams) ([]StorageImage, error)
	// Optional ?node_id and ?type filters. Cursor pagination.
	// Soft-deleted rows are excluded.
	ListStoragePools(ctx context.Context, arg ListStoragePoolsParams) ([]StoragePool, error)
	// Returns every instance of a pool name across the cluster. The
	// multi-instance model permits the same name on multiple nodes
	// simultaneously; bare-name resolution is therefore an aggregation, not a
	// single-row lookup. Case-folded match honours uq_storage_pools_name's
	// functional component.
	ListStoragePoolsByName(ctx context.Context, name string) ([]StoragePool, error)
	// Returns every active pool row owned by the given node, ordered for
	// stable heartbeat responses (operator-facing field order should not
	// jitter between heartbeats). Drives the heartbeat handler's
	// `declared_pools` response field — the agent reconciler
	// consumes this list as the desired-state cache.
	ListStoragePoolsByNode(ctx context.Context, nodeID uuid.UUID) ([]StoragePool, error)
	// Diagnostic-only sibling of ListMemoryPressuredCandidatesByName for
	// the system-disk pressure condition.
	// Returns pool instances on nodes flagged with system_disk_pressure_since
	// IS NOT NULL. Same eligibility predicates as the memory variant —
	// only the inverted pressure filter differs.
	ListSystemDiskPressuredCandidatesByName(ctx context.Context, name string) ([]ListSystemDiskPressuredCandidatesByNameRow, error)
	// Admin / operator scope: see all tasks. Filters compose with AND;
	// omitted filters pass NULL and are no-ops. Cursor pagination keyed on
	// (created_at, id) — DESC ordering means tuple comparison flows in
	// the < direction.
	ListTasksAny(ctx context.Context, arg ListTasksAnyParams) ([]Task, error)
	// Developer / viewer scope: only tasks created by the principal.
	// Same filter / cursor surface as ListTasksAny.
	ListTasksOwn(ctx context.Context, arg ListTasksOwnParams) ([]Task, error)
	// Visibility-aware listing for templates. The clamp is encoded as two
	// parameters:
	//
	//   - caller_can_see_any (bool) — true for admin/operator. When true,
	//     the visibility / ownership clause short-circuits and every active
	//     template (subject to the optional query filters) is returned.
	//   - caller_id (uuid, nullable) — for developer it is the caller's id
	//     (own private + public are visible); for viewer it is NULL (only
	//     public are visible).
	//
	// Optional query filters (?owner_id, ?visibility, ?architecture,
	// ?os_family) compose with the clamp via AND. A non-admin caller that
	// supplies ?owner_id pointing at another user therefore sees only that
	// user's public templates — their private set never leaks. Cursor
	// pagination.
	//
	// The WHERE-shape is intentionally aligned with idx_templates_visibility
	// (visibility, owner_id) — visibility is the leading filter on
	// non-admin callers, which lets the index do the heavy lifting.
	ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]Template, error)
	// Cursor pagination: (created_at, id) ordered, nullable cursor
	// params indicate "first page". Caller passes limit_count = clamp(limit, 1, 200).
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Returns every active (not soft-deleted) disk row for a vm, ordered
	// by device_order. Phase B's GET /v1/vms/{id} response projects the
	// pool_id from disk[0].storage_pool_id (single-disk MVP).
	ListVMDisksByVM(ctx context.Context, vmID uuid.UUID) ([]VMDisk, error)
	// Cursor pagination. First page passes nulls; subsequent
	// pages pass the previous page's last (created_at, id) tuple. Ordering
	// (created_at desc, id desc) matches every other paginated endpoint.
	//
	// Optional filters:
	//
	//   - pool_id_filter — only VMs whose vm_disks references the named
	//     pool. Resolved upstream from the wire `?pool=` query param,
	//     which accepts either a UUID literal or a pool name. Implemented
	//     as EXISTS rather than a JOIN to keep the row count stable for
	//     multi-disk VMs (the MVP is single-disk, but the query is
	//     correct for whatever future disk-fanout decisions land on).
	//
	//   - node_id_filter — only VMs currently located on the named node
	//     per vm_runtime.current_node_id (D6 — current location, not
	//     pinned intent). 'creating' VMs without a runtime row never
	//     match.
	ListVMs(ctx context.Context, arg ListVMsParams) ([]VM, error)
	// Same shape as ListVMs but filtered by owner_id. RBAC scope=own path —
	// currently inactive (vm:read=any for every role) but kept for future
	// restricted-role flows.
	ListVMsByOwner(ctx context.Context, arg ListVMsByOwnerParams) ([]VM, error)
	// Per-node VM desired-state inventory for HeartbeatResponse.declared_vms.
	// Joins vms × vm_runtime on the runtime's current_node_id (D6 — current
	// location, not pinned intent). Soft-deleted vms are excluded; runtime
	// rows whose phase has reached 'gone' are excluded too (the VM is no
	// longer materialised on this node). Output is sorted lower(name) asc
	// so the agent's diff against observed state stays deterministic across
	// heartbeats.
	ListVMsForNodeDeclared(ctx context.Context, nodeID uuid.UUID) ([]ListVMsForNodeDeclaredRow, error)
	// Backs the agentMTLS middleware's identity-binding step. Resolves a
	// SHA-256 fingerprint (32 raw bytes) to its bound node and revocation
	// status. The middleware enforces revocation policy in Go; this query
	// returns the row as recorded.
	LookupAgentCertByFingerprint(ctx context.Context, fingerprintSha256 []byte) (LookupAgentCertByFingerprintRow, error)
	// Backs the heartbeat receiver's firmware-projection step. Resolves a
	// (name, architecture, type) triple reported by the agent to a
	// firmware_id. ErrNoRows means the operator has not registered this
	// firmware in the catalogue; the handler then skips the entry with a
	// WARN log instead of auto-registering it.
	LookupFirmwareByCatalog(ctx context.Context, arg LookupFirmwareByCatalogParams) (uuid.UUID, error)
	// Reconciler step that demotes stale 'ready' or 'pending' rows to
	// 'unreachable'. 'cordoned' and 'draining' are operator-pinned states
	// and stay put even when heartbeats lapse — the operator deliberately
	// isolated the node, so liveness is not the signal that flips it.
	// 'gone' and 'unreachable' are excluded as terminal / already-flagged.
	// Returns the affected rows so callers can log id + name + the stale
	// timestamp without an extra round-trip.
	MarkNodesUnreachable(ctx context.Context, staleBefore time.Time) ([]MarkNodesUnreachableRow, error)
	// Used by the Step 2 redemption handler to detect node-name conflicts
	// before signing a fresh cert. "Active" means revoked_at IS NULL —
	// a revoked cert does NOT block reuse of the node row (the operator
	// already invalidated it, fresh bootstrap is the recovery path).
	// Returns false when either no cert row exists for the node OR all
	// existing certs have been revoked.
	NodeHasActiveCert(ctx context.Context, nodeID uuid.UUID) (bool, error)
	// Force-delete step. Marks every vm_runtime row currently on the node
	// as 'orphaned' and clears current_node_id. vms.desired_phase is
	// intentionally NOT touched (migration 00003): the user still wants
	// whatever they wanted before; only the observed runtime is affected.
	OrphanVMRuntimeOnNode(ctx context.Context, nodeID uuid.UUID) (int64, error)
	// Reconciler step that promotes rows to 'ready' once a fresh heartbeat
	// lands. Two source states qualify: 'pending' (first heartbeat after
	// registration) and 'unreachable' (recovery after a network blip).
	// 'cordoned' and 'draining' stay put — only the operator clears those.
	// Returns the affected rows so callers can log the transition.
	PromoteHealthyNodes(ctx context.Context, freshAfter time.Time) ([]PromoteHealthyNodesRow, error)
	// Overwrites an expired row in place. Returns pgx.ErrNoRows when a
	// concurrent caller already reclaimed (or the row no longer satisfies
	// expires_at < now()).
	ReclaimIdempotencyKey(ctx context.Context, arg ReclaimIdempotencyKeyParams) (IdempotencyKey, error)
	// Logout-from-all-sessions. Revokes every active token for the user.
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	// Idempotent: re-revoking a token is a no-op.
	RevokeApiToken(ctx context.Context, id uuid.UUID) error
	// Bulk-revokes every still-active token belonging to a user. Used by
	// the user-delete handler so a soft-deleted user cannot continue to
	// authenticate via a long-lived API token.
	RevokeApiTokensForUser(ctx context.Context, userID uuid.UUID) error
	// Sets expires_at to the lesser of its current value and now() — a
	// token already in the past stays where it is, a live token jumps to
	// the deadline. Idempotent; repeat calls produce no further effect.
	RevokeJoinToken(ctx context.Context, id uuid.UUID) error
	// Idempotent: re-revoking a token is a no-op.
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	// Revokes every active token in the family. Called when a revoked token
	// is presented at /v1/auth/refresh — the canonical signal of token theft.
	RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error
	// Sets the cluster's default pool name. The handler validates beforehand
	// that at least one pool instance with this name exists.
	SetDefaultPoolName(ctx context.Context, defaultPoolName *string) error
	// Updates only `visibility` (and `updated_at` via the existing trigger).
	// The handler runs a SELECT-then-conditional-UPDATE: when the requested
	// visibility equals the current visibility the UPDATE is skipped
	// entirely, so updated_at remains a meaningful change marker. Owner
	// never moves — publishing a private template does NOT transfer
	// ownership (see docs/rbac.md).
	SetTemplateVisibility(ctx context.Context, arg SetTemplateVisibilityParams) (Template, error)
	SoftDeleteNetwork(ctx context.Context, id uuid.UUID) error
	SoftDeleteNode(ctx context.Context, id uuid.UUID) error
	SoftDeleteStoragePool(ctx context.Context, id uuid.UUID) error
	// Soft-delete only. Three FKs reference templates:
	//
	//   - vms.template_id           ON DELETE SET NULL
	//   - vm_disks.source_template_id  ON DELETE RESTRICT
	//   - node_image_cache.template_id ON DELETE CASCADE
	//
	// Soft-delete bypasses all three (the row physically remains), so the
	// API-level CountActiveVMsForTemplate precheck is the SOLE enforcement
	// of "don't remove a template that's still in use". The partial unique
	// index uq_templates_name on (name) where deleted_at is null frees the
	// name for re-use the moment delete completes.
	SoftDeleteTemplate(ctx context.Context, id uuid.UUID) error
	// Sets deleted_at = now(); preserves the row for audit / FK integrity.
	// Hard delete is not exposed via the API (owned resources block
	// deletion entirely).
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	// Soft delete sets deleted_at; the unique partial index on (name) where
	// deleted_at is null releases the name immediately so a fresh create
	// with the same name can succeed. The vm_runtime row (if any) is
	// handled separately by DeleteVMRuntime in the worker's cleanup phase.
	SoftDeleteVM(ctx context.Context, id uuid.UUID) error
	// Bulk soft-delete every disk row attached to a VM. Called by the
	// worker's vm.delete cleanup phase together with SoftDeleteVM. The
	// per-row deleted_at stamp keeps the on delete cascade behaviour of
	// vm_disks.vm_id from removing rows that audit reads might still
	// need.
	SoftDeleteVMDisksByVM(ctx context.Context, vmID uuid.UUID) error
	TouchApiToken(ctx context.Context, id uuid.UUID) error
	TouchRefreshToken(ctx context.Context, id uuid.UUID) error
	// Records a successful login. Separate from UpdateUser because it's a hot
	// path (every login) and shouldn't go through the full row replacement.
	TouchUserLastLogin(ctx context.Context, id uuid.UUID) error
	// Returns the node to 'ready' and clears cordoned_at. Caller is expected
	// to gate on valid transitions (idempotent no-op for already-ready, 409
	// for pending/unreachable/draining/gone) before issuing this query.
	UncordonNode(ctx context.Context, id uuid.UUID) (Node, error)
	// Caller merges the patch with the current row before issuing this
	// query (the same pattern as UpdateNetwork / UpdateStoragePool). The
	// `architecture` and `type` columns are intentionally absent from the
	// SET list — they are API-immutable and changing them would invalidate
	// the (architecture, type) default-uniqueness invariant.
	UpdateFirmware(ctx context.Context, arg UpdateFirmwareParams) (Firmware, error)
	// Caller merges the patch with the current row before issuing this
	// query (the same pattern as UpdateUser). The `type` column is
	// intentionally absent from this query — it is API-immutable and
	// changing it would require schema-level coordination with vm_nics.
	UpdateNetwork(ctx context.Context, arg UpdateNetworkParams) (Network, error)
	// Called from the agent heartbeat path. Migration capability is included
	// because an agent can reconfigure its migration network without rejoining.
	// `architecture` is intentionally NOT mutated here — it is immutable
	// after registration, and the handler rejects mismatches with 409
	// before reaching this update. `labels` is also untouched: heartbeat
	// does not carry labels (operator-managed). `status` stays unchanged —
	// that is the reconciler's job.
	//
	// system_disk_{total,available}_bytes write
	// raw root-filesystem capacity reported by the agent. Pressure detection
	// happens via UpdateNodeSystemDiskPressure inside the same transaction.
	UpdateNodeHeartbeat(ctx context.Context, arg UpdateNodeHeartbeatParams) error
	// Persists the memory-pressure transition computed by the heartbeat
	// receiver. Memory_pressure_since is NULL
	// when the condition is not active; the count increments on every
	// below-threshold observation and resets to 0 on an at-or-above-threshold
	// observation. Caller runs this inside the same transaction as
	// UpdateNodeHeartbeat so the pressure state never drifts ahead of the
	// raw metrics that determined it.
	UpdateNodeMemoryPressure(ctx context.Context, arg UpdateNodeMemoryPressureParams) error
	// Reconciler-driven status transitions. cordoned_at is bumped to now()
	// when the new status is 'cordoned' and was previously something else;
	// callers pass cordoned_at = NULL to clear it.
	UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) error
	// Persists the system-disk pressure transition.
	// Mirror of UpdateNodeMemoryPressure: NULL pressure_since when condition
	// is not active; count increments on each below-threshold observation,
	// resets to 0 on the first at-or-above observation. Runs inside the same
	// transaction as UpdateNodeHeartbeat.
	UpdateNodeSystemDiskPressure(ctx context.Context, arg UpdateNodeSystemDiskPressureParams) error
	// Persists the pool disk pressure transition.
	// Caller runs this in the same transaction as UpsertStoragePoolUsage so
	// pressure state never drifts ahead of the scan that determined it.
	UpdatePoolDiskPressure(ctx context.Context, arg UpdatePoolDiskPressureParams) error
	// Caller merges the patch with the current row before issuing this
	// query (the same pattern as UpdateNetwork). The `node_id`, `type` and
	// `path` columns are intentionally absent from the SET list — they are
	// API-immutable. capacity_bytes / available_bytes / reported_at are
	// owned by the heartbeat / scan path and are never touched by this
	// handler-driven update.
	UpdateStoragePool(ctx context.Context, arg UpdateStoragePoolParams) (StoragePool, error)
	// Applies the agent's reconciliation report for a single pool. Called
	// by the heartbeat handler once per reported pool per heartbeat. The
	// match key is (node_id, lower(name)) — a pool name maps to multiple
	// rows cluster-wide, but only one per node. Soft-deleted rows are
	// skipped silently (no rows affected): operator deleted the pool
	// mid-tick; the agent will drop it from observed state on the next
	// reconciliation cycle. error is set to the empty string when the
	// agent reports success, NULL when the status itself is not 'failed'.
	UpdateStoragePoolReconciliation(ctx context.Context, arg UpdateStoragePoolReconciliationParams) error
	// Stamps the agent-side task id on the CP task row. Called by an
	// insert-driven agent-saga worker after the agent's 202 response
	// (storage_image.import is the first consumer). Persisting the id
	// makes a CP-side restart resume polling the existing agent task
	// instead of issuing a duplicate POST (worker resumption seam).
	// storage_pool.scan does NOT populate this column — its task surface
	// stays nil.
	UpdateTaskAgentTaskID(ctx context.Context, arg UpdateTaskAgentTaskIDParams) error
	// Worker exit: terminal status (success / failed / cancelled), the
	// result / error JSONB payloads, and finished_at. The caller passes
	// result and error; both nullable JSONB columns and either may be NULL
	// depending on the terminal branch.
	UpdateTaskFinalized(ctx context.Context, arg UpdateTaskFinalizedParams) error
	// Stamps the river job id onto the task row inside the atomic enqueue
	// transaction (after river.InsertTx returns). The column carries a
	// weak reference (no FK) used only for ops
	// drill-down.
	UpdateTaskRiverJobID(ctx context.Context, arg UpdateTaskRiverJobIDParams) error
	// Worker entry: pending → running. Increments the attempt counter and
	// stamps started_at on the first transition (idempotent across retries
	// thanks to COALESCE).
	UpdateTaskRunning(ctx context.Context, id uuid.UUID) error
	// Caller merges the patch with the current row before issuing this
	// query (same pattern as UpdateNetwork / UpdateFirmware). The columns
	// below are exactly the 11 mutable fields surfaced by TemplateUpdate
	// in api/openapi/control-plane.yaml. Identity / image-source fields
	// (architecture, os_family, owner_id, image_url, image_checksum_sha256,
	// image_format, image_size_bytes) are intentionally absent — they are
	// API-immutable. visibility is also absent: it moves only through
	// SetTemplateVisibility.
	UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error)
	// Back-propagates the agent-computed image_checksum_sha256 onto a
	// template row that was registered without one (compute mode).
	// The `image_checksum_sha256 is null` guard in the WHERE clause makes
	// this idempotent and race-safe:
	//
	//   - First successful compute-mode import for the template lands the
	//     hash; subsequent imports (to other pools, OR re-imports to the same
	//     pool) become no-ops because the column is no longer NULL.
	//   - Two concurrent compute-mode imports to different pools that happen
	//     to compute different bytes (corrupted download) cannot both win:
	//     whichever transaction commits first wins; the second's UPDATE
	//     affects 0 rows and is silently absorbed.
	//
	// The :exec return shape is acceptable because the worker treats a
	// failed update as a warning, not a terminal-fail signal — the
	// storage_images row is already authoritative for the (template, pool)
	// combination.
	UpdateTemplateImageChecksumIfNull(ctx context.Context, arg UpdateTemplateImageChecksumIfNullParams) error
	// Caller merges patch with current values; this query updates the lot.
	// updated_at is bumped by the trg_set_updated_at trigger.
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	// Used by the worker to flip desired_phase to 'deleted' as the user-visible
	// delete starts (before the agent acknowledges teardown). Clean read-side
	// semantics: desired_phase reflects user intent; vm_runtime.phase reflects
	// observed.
	UpdateVMDesiredPhase(ctx context.Context, arg UpdateVMDesiredPhaseParams) error
	// Single-field phase patch used by the synchronous VM lifecycle
	// handlers (pause / resume / reset). The CP-side handler invokes
	// this after the agent confirms a QMP-driven transition so the
	// next projected `status` reflects the new state without waiting
	// for the heartbeat reconciler to catch up. last_observed_at is
	// stamped to keep the wire's observed-state freshness signal
	// monotonic.
	UpdateVMRuntimePhase(ctx context.Context, arg UpdateVMRuntimePhaseParams) error
	// Heartbeat-driven projection: refresh the (node_id, firmware_id) row
	// with the agent-reported paths and bump reported_at. Conflict on the
	// composite primary key resolves to UPDATE; this is the only writer
	// so race-free.
	UpsertNodeFirmware(ctx context.Context, arg UpsertNodeFirmwareParams) error
	// Scan-result projection. Agent-reported capacity /
	// availability merge onto the row; handler-driven CRUD never not
	// writes these columns. The scan worker pairs this with
	// GetPoolDiskPressureState + UpdatePoolDiskPressure inside the same
	// transaction so pool disk pressure stays
	// consistent with the metrics that determined it.
	UpsertStoragePoolUsage(ctx context.Context, arg UpsertStoragePoolUsageParams) error
	// Heartbeat-driven projection of a per-VM runtime snapshot. Conflict
	// on the primary key (vm_id) resolves to UPDATE; the heartbeat is
	// the only writer of the agent-reported fields. observed_generation
	// is bumped when the agent reports a value; missing values pass
	// through nullable parameters. last_observed_at is stamped on every
	// upsert (separate from the trigger-managed updated_at, which fires
	// on UPDATE only).
	UpsertVMRuntime(ctx context.Context, arg UpsertVMRuntimeParams) error
}

var _ Querier = (*Queries)(nil)
