// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
insert into refresh_tokens (
    id, user_id, token_hash,
    family_id, parent_id,
    user_agent, ip_address,
    expires_at
)
values (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8
)
returning id, user_id, token_hash, family_id, parent_id, user_agent, ip_address, issued_at, expires_at, revoked_at, last_used_at
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	FamilyID  uuid.UUID
	ParentID  *uuid.UUID
	UserAgent *string
	IpAddress *netip.Addr
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ParentID,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ParentID,
		&i.UserAgent,
		&i.IpAddress,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
delete from refresh_tokens
where expires_at < $1
`

// Cleanup query for the (out-of-scope here) periodic cleanup job. Drops
// every row whose expiry is older than @cutoff. Returns the number of
// rows deleted so the job can log progress.
func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
select id, user_id, token_hash, family_id, parent_id, user_agent, ip_address, issued_at, expires_at, revoked_at, last_used_at
from refresh_tokens
where token_hash = $1
`

// Returns the row regardless of revocation state. The caller inspects
// revoked_at to detect replay (sentinel for token theft) and expires_at
// to detect expiry; both are normal control-flow signals, not errors.
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ParentID,
		&i.UserAgent,
		&i.IpAddress,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
update refresh_tokens
set revoked_at = now()
where user_id = $1
  and revoked_at is null
`

// Logout-from-all-sessions. Revokes every active token for the user.
func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
update refresh_tokens
set revoked_at = now()
where id = $1
  and revoked_at is null
`

// Idempotent: re-revoking a token is a no-op.
func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
update refresh_tokens
set revoked_at = now()
where family_id = $1
  and revoked_at is null
`

// Revokes every active token in the family. Called when a revoked token
// is presented at /v1/auth/refresh — the canonical signal of token theft.
func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	return err
}

const touchRefreshToken = `-- name: TouchRefreshToken :exec
update refresh_tokens
set last_used_at = now()
where id = $1
`

func (q *Queries) TouchRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchRefreshToken, id)
	return err
}
