// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage_images.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countStorageImagesByPool = `-- name: CountStorageImagesByPool :one
select count(*)::bigint as image_count
from storage_images
where pool_id = $1::uuid
`

// Precheck before DELETE /v1/storage-pools/{id} (Step 6 extended-
// delete refusal): if > 0, surface 409 pool_in_use.
func (q *Queries) CountStorageImagesByPool(ctx context.Context, poolID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStorageImagesByPool, poolID)
	var image_count int64
	err := row.Scan(&image_count)
	return image_count, err
}

const countStorageImagesBySHA256InPool = `-- name: CountStorageImagesBySHA256InPool :one
select count(*)::bigint as referent_count
from storage_images
where pool_id         = $1::uuid
  and checksum_sha256 = $2::text
  and id              != $3::uuid
`

type CountStorageImagesBySHA256InPoolParams struct {
	PoolID         uuid.UUID
	ChecksumSha256 string
	ExcludeID      uuid.UUID
}

// Refcount gate for storage_image:delete handler (Step 9 sync
// delete). Counts other rows in the same pool that share the
// checksum, excluding the row about to be deleted. Caller invokes
// agent.deleteImage only when this returns 0; otherwise the
// on-disk file stays alive for the surviving sibling rows
// (content-addressable deduplication).
func (q *Queries) CountStorageImagesBySHA256InPool(ctx context.Context, arg CountStorageImagesBySHA256InPoolParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStorageImagesBySHA256InPool, arg.PoolID, arg.ChecksumSha256, arg.ExcludeID)
	var referent_count int64
	err := row.Scan(&referent_count)
	return referent_count, err
}

const countStorageImagesByTemplate = `-- name: CountStorageImagesByTemplate :one
select count(*)::bigint as image_count
from storage_images
where template_id = $1::uuid
`

// Precheck before DELETE /v1/templates/{id} (Step 6 extended-delete
// refusal): if > 0, surface 409 template_in_use.
func (q *Queries) CountStorageImagesByTemplate(ctx context.Context, templateID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStorageImagesByTemplate, templateID)
	var image_count int64
	err := row.Scan(&image_count)
	return image_count, err
}

const createStorageImage = `-- name: CreateStorageImage :one
insert into storage_images (
    id,
    template_id,
    pool_id,
    checksum_sha256,
    size_bytes,
    format
)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
on conflict (template_id, pool_id) do update
    set checksum_sha256 = excluded.checksum_sha256,
        size_bytes      = excluded.size_bytes,
        format          = excluded.format
returning id, template_id, pool_id, checksum_sha256, size_bytes, format, imported_at
`

type CreateStorageImageParams struct {
	ID             uuid.UUID
	TemplateID     uuid.UUID
	PoolID         uuid.UUID
	ChecksumSha256 string
	SizeBytes      int64
	Format         string
}

// The storage_image.import worker calls this on terminal-success
// to project the agent's import result into CP. ON CONFLICT
// (template_id, pool_id) DO UPDATE: a re-import with
// rotated content overwrites the row's checksum / size / format so
// the row tracks the latest authoritative state. The handler's
// atomic-enqueue tx creates the Task row first; the worker's success
// projection commits this row in the same final tx as
// UpdateTaskFinalized.
func (q *Queries) CreateStorageImage(ctx context.Context, arg CreateStorageImageParams) (StorageImage, error) {
	row := q.db.QueryRow(ctx, createStorageImage,
		arg.ID,
		arg.TemplateID,
		arg.PoolID,
		arg.ChecksumSha256,
		arg.SizeBytes,
		arg.Format,
	)
	var i StorageImage
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.PoolID,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.Format,
		&i.ImportedAt,
	)
	return i, err
}

const deleteStorageImage = `-- name: DeleteStorageImage :exec
delete from storage_images
where id = $1
`

func (q *Queries) DeleteStorageImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStorageImage, id)
	return err
}

const getStorageImageByID = `-- name: GetStorageImageByID :one
select id, template_id, pool_id, checksum_sha256, size_bytes, format, imported_at
from storage_images
where id = $1
`

func (q *Queries) GetStorageImageByID(ctx context.Context, id uuid.UUID) (StorageImage, error) {
	row := q.db.QueryRow(ctx, getStorageImageByID, id)
	var i StorageImage
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.PoolID,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.Format,
		&i.ImportedAt,
	)
	return i, err
}

const getStorageImageByTemplateAndPool = `-- name: GetStorageImageByTemplateAndPool :one
select id, template_id, pool_id, checksum_sha256, size_bytes, format, imported_at
from storage_images
where template_id = $1
  and pool_id     = $2
`

type GetStorageImageByTemplateAndPoolParams struct {
	TemplateID uuid.UUID
	PoolID     uuid.UUID
}

// Composite-key lookup. Useful for handlers that need to project the
// (template, pool) → image relation without scanning the pool list.
// Returns pgx.ErrNoRows when the image has not been imported yet.
func (q *Queries) GetStorageImageByTemplateAndPool(ctx context.Context, arg GetStorageImageByTemplateAndPoolParams) (StorageImage, error) {
	row := q.db.QueryRow(ctx, getStorageImageByTemplateAndPool, arg.TemplateID, arg.PoolID)
	var i StorageImage
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.PoolID,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.Format,
		&i.ImportedAt,
	)
	return i, err
}

const listStorageImagesByPool = `-- name: ListStorageImagesByPool :many
select id, template_id, pool_id, checksum_sha256, size_bytes, format, imported_at
from storage_images
where pool_id = $1
  and (
    $2::timestamptz is null
    or (imported_at, id) < (
      $2::timestamptz,
      $3::uuid
    )
  )
order by imported_at desc, id desc
limit $4
`

type ListStorageImagesByPoolParams struct {
	PoolID           uuid.UUID
	CursorImportedAt *time.Time
	CursorID         *uuid.UUID
	LimitCount       int32
}

// Backs the storageImages.list endpoint. Cursor pagination keyed on
// (imported_at, id) DESC — the tasks-style direction (newest first).
func (q *Queries) ListStorageImagesByPool(ctx context.Context, arg ListStorageImagesByPoolParams) ([]StorageImage, error) {
	rows, err := q.db.Query(ctx, listStorageImagesByPool,
		arg.PoolID,
		arg.CursorImportedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageImage{}
	for rows.Next() {
		var i StorageImage
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.PoolID,
			&i.ChecksumSha256,
			&i.SizeBytes,
			&i.Format,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
