// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage_pools.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countVMDisksOnStoragePool = `-- name: CountVMDisksOnStoragePool :one
select count(*)::bigint as disk_count
from vm_disks
where storage_pool_id = $1::uuid
  and deleted_at is null
`

// Precheck before DELETE /v1/storage-pools/{id}: counts active vm_disks
// rows that still reference the pool. Soft-deleted disks are excluded
// — a detached disk has no live attachment and does not block pool
// deletion. The FK uses ON DELETE RESTRICT, so this check also avoids
// the SQL-level error path; we surface 409 with a typed payload
// instead.
func (q *Queries) CountVMDisksOnStoragePool(ctx context.Context, storagePoolID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVMDisksOnStoragePool, storagePoolID)
	var disk_count int64
	err := row.Scan(&disk_count)
	return disk_count, err
}

const createStoragePool = `-- name: CreateStoragePool :one
insert into storage_pools (
    id,
    node_id,
    name,
    type,
    path,
    config
)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
returning id, node_id, name, type, path, capacity_bytes, available_bytes, reported_at, config, disk_pressure_since, disk_pressure_count, reconciliation_status, last_reconciled_at, reconciliation_error, created_at, updated_at, deleted_at
`

type CreateStoragePoolParams struct {
	ID     uuid.UUID
	NodeID uuid.UUID
	Name   string
	Type   string
	Path   string
	Config []byte
}

// Identity-and-config columns only. capacity_bytes / available_bytes /
// reported_at are agent-reported and never accepted on
// the API edge — they will be populated through the future heartbeat
// and scan paths, both of which use UpsertStoragePoolUsage (deferred,
// not implemented yet).
func (q *Queries) CreateStoragePool(ctx context.Context, arg CreateStoragePoolParams) (StoragePool, error) {
	row := q.db.QueryRow(ctx, createStoragePool,
		arg.ID,
		arg.NodeID,
		arg.Name,
		arg.Type,
		arg.Path,
		arg.Config,
	)
	var i StoragePool
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Type,
		&i.Path,
		&i.CapacityBytes,
		&i.AvailableBytes,
		&i.ReportedAt,
		&i.Config,
		&i.DiskPressureSince,
		&i.DiskPressureCount,
		&i.ReconciliationStatus,
		&i.LastReconciledAt,
		&i.ReconciliationError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPoolDiskPressureState = `-- name: GetPoolDiskPressureState :one
select disk_pressure_since, disk_pressure_count
from storage_pools
where id = $1
  and deleted_at is null
`

type GetPoolDiskPressureStateRow struct {
	DiskPressureSince *time.Time
	DiskPressureCount int32
}

// Pre-read for the scan worker's pool disk pressure transition.
// Mirrors GetNodeForHeartbeat's pressure-state read on the node side.
// Excludes soft-deleted rows — а scan that lands после the pool is
// soft-deleted is а no-op overall.
func (q *Queries) GetPoolDiskPressureState(ctx context.Context, id uuid.UUID) (GetPoolDiskPressureStateRow, error) {
	row := q.db.QueryRow(ctx, getPoolDiskPressureState, id)
	var i GetPoolDiskPressureStateRow
	err := row.Scan(&i.DiskPressureSince, &i.DiskPressureCount)
	return i, err
}

const getPoolEffectiveByID = `-- name: GetPoolEffectiveByID :one
select id, node_id, name, type, path, capacity_bytes, available_bytes, reported_at, config, disk_pressure_since, disk_pressure_count, reconciliation_status, last_reconciled_at, reconciliation_error, created_at, updated_at, deleted_at, available_bytes_effective from pool_effective_capacity
where id = $1
  and deleted_at is null
`

// View-backed read returning every storage_pools column plus the
// `available_bytes_effective` synthesized by pool_effective_capacity.
// Consumed by the GET-by-id handler so operator-facing responses
// surface both raw и effective bytes.
func (q *Queries) GetPoolEffectiveByID(ctx context.Context, id uuid.UUID) (PoolEffectiveCapacity, error) {
	row := q.db.QueryRow(ctx, getPoolEffectiveByID, id)
	var i PoolEffectiveCapacity
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Type,
		&i.Path,
		&i.CapacityBytes,
		&i.AvailableBytes,
		&i.ReportedAt,
		&i.Config,
		&i.DiskPressureSince,
		&i.DiskPressureCount,
		&i.ReconciliationStatus,
		&i.LastReconciledAt,
		&i.ReconciliationError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AvailableBytesEffective,
	)
	return i, err
}

const getStoragePoolByID = `-- name: GetStoragePoolByID :one
select id, node_id, name, type, path, capacity_bytes, available_bytes, reported_at, config, disk_pressure_since, disk_pressure_count, reconciliation_status, last_reconciled_at, reconciliation_error, created_at, updated_at, deleted_at
from storage_pools
where id = $1
  and deleted_at is null
`

func (q *Queries) GetStoragePoolByID(ctx context.Context, id uuid.UUID) (StoragePool, error) {
	row := q.db.QueryRow(ctx, getStoragePoolByID, id)
	var i StoragePool
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Type,
		&i.Path,
		&i.CapacityBytes,
		&i.AvailableBytes,
		&i.ReportedAt,
		&i.Config,
		&i.DiskPressureSince,
		&i.DiskPressureCount,
		&i.ReconciliationStatus,
		&i.LastReconciledAt,
		&i.ReconciliationError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDiskPressuredPoolsByName = `-- name: ListDiskPressuredPoolsByName :many
select p.id, p.node_id, p.name, p.type, p.path, p.capacity_bytes, p.available_bytes, p.reported_at, p.config, p.disk_pressure_since, p.disk_pressure_count, p.reconciliation_status, p.last_reconciled_at, p.reconciliation_error, p.created_at, p.updated_at, p.deleted_at, p.available_bytes_effective, n.id, n.name, n.architecture, n.advertised_endpoint, n.migration_host, n.migration_port_range_start, n.migration_port_range_end, n.status, n.cordoned_at, n.cpu_cores_total, n.cpu_cores_available, n.cpu_model, n.cpu_flags, n.memory_total_mib, n.memory_available_mib, n.hugepages_2mib_total, n.hugepages_1gib_total, n.kernel_version, n.qemu_version, n.numa_topology, n.capabilities, n.last_heartbeat_at, n.agent_version, n.labels, n.memory_pressure_since, n.memory_pressure_count, n.system_disk_total_bytes, n.system_disk_available_bytes, n.system_disk_pressure_since, n.system_disk_pressure_count, n.created_at, n.updated_at, n.deleted_at, n.cpu_cores_effective, n.memory_effective_mib
from pool_effective_capacity p
join node_effective_availability n on n.id = p.node_id
where lower(p.name) = lower($1)
  and p.deleted_at is null
  and n.deleted_at is null
  and n.status = 'ready'
  and n.cordoned_at is null
  and p.disk_pressure_since is not null
order by n.id
`

type ListDiskPressuredPoolsByNameRow struct {
	PoolEffectiveCapacity     PoolEffectiveCapacity
	NodeEffectiveAvailability NodeEffectiveAvailability
}

// Diagnostic-only sibling for pool disk pressure. Returns pool
// instances для the given name whose own disk_pressure flag is set —
// independent of the owning node's pressure status. Pool-scoped
// pressure is the only condition that excludes а pool independently
// of its node.
func (q *Queries) ListDiskPressuredPoolsByName(ctx context.Context, name string) ([]ListDiskPressuredPoolsByNameRow, error) {
	rows, err := q.db.Query(ctx, listDiskPressuredPoolsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiskPressuredPoolsByNameRow{}
	for rows.Next() {
		var i ListDiskPressuredPoolsByNameRow
		if err := rows.Scan(
			&i.PoolEffectiveCapacity.ID,
			&i.PoolEffectiveCapacity.NodeID,
			&i.PoolEffectiveCapacity.Name,
			&i.PoolEffectiveCapacity.Type,
			&i.PoolEffectiveCapacity.Path,
			&i.PoolEffectiveCapacity.CapacityBytes,
			&i.PoolEffectiveCapacity.AvailableBytes,
			&i.PoolEffectiveCapacity.ReportedAt,
			&i.PoolEffectiveCapacity.Config,
			&i.PoolEffectiveCapacity.DiskPressureSince,
			&i.PoolEffectiveCapacity.DiskPressureCount,
			&i.PoolEffectiveCapacity.ReconciliationStatus,
			&i.PoolEffectiveCapacity.LastReconciledAt,
			&i.PoolEffectiveCapacity.ReconciliationError,
			&i.PoolEffectiveCapacity.CreatedAt,
			&i.PoolEffectiveCapacity.UpdatedAt,
			&i.PoolEffectiveCapacity.DeletedAt,
			&i.PoolEffectiveCapacity.AvailableBytesEffective,
			&i.NodeEffectiveAvailability.ID,
			&i.NodeEffectiveAvailability.Name,
			&i.NodeEffectiveAvailability.Architecture,
			&i.NodeEffectiveAvailability.AdvertisedEndpoint,
			&i.NodeEffectiveAvailability.MigrationHost,
			&i.NodeEffectiveAvailability.MigrationPortRangeStart,
			&i.NodeEffectiveAvailability.MigrationPortRangeEnd,
			&i.NodeEffectiveAvailability.Status,
			&i.NodeEffectiveAvailability.CordonedAt,
			&i.NodeEffectiveAvailability.CPUCoresTotal,
			&i.NodeEffectiveAvailability.CPUCoresAvailable,
			&i.NodeEffectiveAvailability.CPUModel,
			&i.NodeEffectiveAvailability.CpuFlags,
			&i.NodeEffectiveAvailability.MemoryTotalMib,
			&i.NodeEffectiveAvailability.MemoryAvailableMib,
			&i.NodeEffectiveAvailability.Hugepages2mibTotal,
			&i.NodeEffectiveAvailability.Hugepages1gibTotal,
			&i.NodeEffectiveAvailability.KernelVersion,
			&i.NodeEffectiveAvailability.QEMUVersion,
			&i.NodeEffectiveAvailability.NumaTopology,
			&i.NodeEffectiveAvailability.Capabilities,
			&i.NodeEffectiveAvailability.LastHeartbeatAt,
			&i.NodeEffectiveAvailability.AgentVersion,
			&i.NodeEffectiveAvailability.Labels,
			&i.NodeEffectiveAvailability.MemoryPressureSince,
			&i.NodeEffectiveAvailability.MemoryPressureCount,
			&i.NodeEffectiveAvailability.SystemDiskTotalBytes,
			&i.NodeEffectiveAvailability.SystemDiskAvailableBytes,
			&i.NodeEffectiveAvailability.SystemDiskPressureSince,
			&i.NodeEffectiveAvailability.SystemDiskPressureCount,
			&i.NodeEffectiveAvailability.CreatedAt,
			&i.NodeEffectiveAvailability.UpdatedAt,
			&i.NodeEffectiveAvailability.DeletedAt,
			&i.NodeEffectiveAvailability.CPUCoresEffective,
			&i.NodeEffectiveAvailability.MemoryEffectiveMib,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligiblePoolsByName = `-- name: ListEligiblePoolsByName :many
select p.id, p.node_id, p.name, p.type, p.path, p.capacity_bytes, p.available_bytes, p.reported_at, p.config, p.disk_pressure_since, p.disk_pressure_count, p.reconciliation_status, p.last_reconciled_at, p.reconciliation_error, p.created_at, p.updated_at, p.deleted_at, p.available_bytes_effective, n.id, n.name, n.architecture, n.advertised_endpoint, n.migration_host, n.migration_port_range_start, n.migration_port_range_end, n.status, n.cordoned_at, n.cpu_cores_total, n.cpu_cores_available, n.cpu_model, n.cpu_flags, n.memory_total_mib, n.memory_available_mib, n.hugepages_2mib_total, n.hugepages_1gib_total, n.kernel_version, n.qemu_version, n.numa_topology, n.capabilities, n.last_heartbeat_at, n.agent_version, n.labels, n.memory_pressure_since, n.memory_pressure_count, n.system_disk_total_bytes, n.system_disk_available_bytes, n.system_disk_pressure_since, n.system_disk_pressure_count, n.created_at, n.updated_at, n.deleted_at, n.cpu_cores_effective, n.memory_effective_mib
from pool_effective_capacity p
join node_effective_availability n on n.id = p.node_id
where lower(p.name) = lower($1)
  and p.deleted_at is null
  and n.deleted_at is null
  and n.status = 'ready'
  and n.cordoned_at is null
  and n.memory_pressure_since is null
  and n.system_disk_pressure_since is null
  and p.disk_pressure_since is null
order by n.id
`

type ListEligiblePoolsByNameRow struct {
	PoolEffectiveCapacity     PoolEffectiveCapacity
	NodeEffectiveAvailability NodeEffectiveAvailability
}

// Joined query used by the scheduler at VM placement time: enumerates
// pool instances for the given name on nodes that are ready and not
// cordoned. Returns the pool's effective-capacity row plus the node's
// effective-availability row in a single round-trip.
//
// Sources pool columns from pool_effective_capacity so the scheduler
// reads `available_bytes_effective` — pool availability с pending-VM-
// disk accounting. Node columns come от node_effective_availability so
// `cpu_cores_effective` / `memory_effective_mib` are available with
// pending-VM accounting too. Both views are supersets of their
// underlying tables, so the eligibility filters
// (status = 'ready', cordoned_at IS NULL, deleted_at IS NULL) hold
// without change. Disk-aware Sub-iteration C consumes both effective
// columns in `filterByResources` / `scoreResourceAware`.
func (q *Queries) ListEligiblePoolsByName(ctx context.Context, name string) ([]ListEligiblePoolsByNameRow, error) {
	rows, err := q.db.Query(ctx, listEligiblePoolsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEligiblePoolsByNameRow{}
	for rows.Next() {
		var i ListEligiblePoolsByNameRow
		if err := rows.Scan(
			&i.PoolEffectiveCapacity.ID,
			&i.PoolEffectiveCapacity.NodeID,
			&i.PoolEffectiveCapacity.Name,
			&i.PoolEffectiveCapacity.Type,
			&i.PoolEffectiveCapacity.Path,
			&i.PoolEffectiveCapacity.CapacityBytes,
			&i.PoolEffectiveCapacity.AvailableBytes,
			&i.PoolEffectiveCapacity.ReportedAt,
			&i.PoolEffectiveCapacity.Config,
			&i.PoolEffectiveCapacity.DiskPressureSince,
			&i.PoolEffectiveCapacity.DiskPressureCount,
			&i.PoolEffectiveCapacity.ReconciliationStatus,
			&i.PoolEffectiveCapacity.LastReconciledAt,
			&i.PoolEffectiveCapacity.ReconciliationError,
			&i.PoolEffectiveCapacity.CreatedAt,
			&i.PoolEffectiveCapacity.UpdatedAt,
			&i.PoolEffectiveCapacity.DeletedAt,
			&i.PoolEffectiveCapacity.AvailableBytesEffective,
			&i.NodeEffectiveAvailability.ID,
			&i.NodeEffectiveAvailability.Name,
			&i.NodeEffectiveAvailability.Architecture,
			&i.NodeEffectiveAvailability.AdvertisedEndpoint,
			&i.NodeEffectiveAvailability.MigrationHost,
			&i.NodeEffectiveAvailability.MigrationPortRangeStart,
			&i.NodeEffectiveAvailability.MigrationPortRangeEnd,
			&i.NodeEffectiveAvailability.Status,
			&i.NodeEffectiveAvailability.CordonedAt,
			&i.NodeEffectiveAvailability.CPUCoresTotal,
			&i.NodeEffectiveAvailability.CPUCoresAvailable,
			&i.NodeEffectiveAvailability.CPUModel,
			&i.NodeEffectiveAvailability.CpuFlags,
			&i.NodeEffectiveAvailability.MemoryTotalMib,
			&i.NodeEffectiveAvailability.MemoryAvailableMib,
			&i.NodeEffectiveAvailability.Hugepages2mibTotal,
			&i.NodeEffectiveAvailability.Hugepages1gibTotal,
			&i.NodeEffectiveAvailability.KernelVersion,
			&i.NodeEffectiveAvailability.QEMUVersion,
			&i.NodeEffectiveAvailability.NumaTopology,
			&i.NodeEffectiveAvailability.Capabilities,
			&i.NodeEffectiveAvailability.LastHeartbeatAt,
			&i.NodeEffectiveAvailability.AgentVersion,
			&i.NodeEffectiveAvailability.Labels,
			&i.NodeEffectiveAvailability.MemoryPressureSince,
			&i.NodeEffectiveAvailability.MemoryPressureCount,
			&i.NodeEffectiveAvailability.SystemDiskTotalBytes,
			&i.NodeEffectiveAvailability.SystemDiskAvailableBytes,
			&i.NodeEffectiveAvailability.SystemDiskPressureSince,
			&i.NodeEffectiveAvailability.SystemDiskPressureCount,
			&i.NodeEffectiveAvailability.CreatedAt,
			&i.NodeEffectiveAvailability.UpdatedAt,
			&i.NodeEffectiveAvailability.DeletedAt,
			&i.NodeEffectiveAvailability.CPUCoresEffective,
			&i.NodeEffectiveAvailability.MemoryEffectiveMib,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryPressuredCandidatesByName = `-- name: ListMemoryPressuredCandidatesByName :many
select p.id, p.node_id, p.name, p.type, p.path, p.capacity_bytes, p.available_bytes, p.reported_at, p.config, p.disk_pressure_since, p.disk_pressure_count, p.reconciliation_status, p.last_reconciled_at, p.reconciliation_error, p.created_at, p.updated_at, p.deleted_at, p.available_bytes_effective, n.id, n.name, n.architecture, n.advertised_endpoint, n.migration_host, n.migration_port_range_start, n.migration_port_range_end, n.status, n.cordoned_at, n.cpu_cores_total, n.cpu_cores_available, n.cpu_model, n.cpu_flags, n.memory_total_mib, n.memory_available_mib, n.hugepages_2mib_total, n.hugepages_1gib_total, n.kernel_version, n.qemu_version, n.numa_topology, n.capabilities, n.last_heartbeat_at, n.agent_version, n.labels, n.memory_pressure_since, n.memory_pressure_count, n.system_disk_total_bytes, n.system_disk_available_bytes, n.system_disk_pressure_since, n.system_disk_pressure_count, n.created_at, n.updated_at, n.deleted_at, n.cpu_cores_effective, n.memory_effective_mib
from pool_effective_capacity p
join node_effective_availability n on n.id = p.node_id
where lower(p.name) = lower($1)
  and p.deleted_at is null
  and n.deleted_at is null
  and n.status = 'ready'
  and n.cordoned_at is null
  and n.memory_pressure_since is not null
order by n.id
`

type ListMemoryPressuredCandidatesByNameRow struct {
	PoolEffectiveCapacity     PoolEffectiveCapacity
	NodeEffectiveAvailability NodeEffectiveAvailability
}

// Diagnostic query consumed by the scheduler on the failure path
// (`len(eligible) == 0` for а pool that does exist somewhere). Returns
// pool instances for the given name whose owning node would have been
// eligible except for an active **memory** pressure condition.
// Same node-status / cordoned / deleted_at filters as
// ListEligiblePoolsByName, но the memory pressure filter is inverted
// (memory_pressure_since IS NOT NULL).
func (q *Queries) ListMemoryPressuredCandidatesByName(ctx context.Context, name string) ([]ListMemoryPressuredCandidatesByNameRow, error) {
	rows, err := q.db.Query(ctx, listMemoryPressuredCandidatesByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemoryPressuredCandidatesByNameRow{}
	for rows.Next() {
		var i ListMemoryPressuredCandidatesByNameRow
		if err := rows.Scan(
			&i.PoolEffectiveCapacity.ID,
			&i.PoolEffectiveCapacity.NodeID,
			&i.PoolEffectiveCapacity.Name,
			&i.PoolEffectiveCapacity.Type,
			&i.PoolEffectiveCapacity.Path,
			&i.PoolEffectiveCapacity.CapacityBytes,
			&i.PoolEffectiveCapacity.AvailableBytes,
			&i.PoolEffectiveCapacity.ReportedAt,
			&i.PoolEffectiveCapacity.Config,
			&i.PoolEffectiveCapacity.DiskPressureSince,
			&i.PoolEffectiveCapacity.DiskPressureCount,
			&i.PoolEffectiveCapacity.ReconciliationStatus,
			&i.PoolEffectiveCapacity.LastReconciledAt,
			&i.PoolEffectiveCapacity.ReconciliationError,
			&i.PoolEffectiveCapacity.CreatedAt,
			&i.PoolEffectiveCapacity.UpdatedAt,
			&i.PoolEffectiveCapacity.DeletedAt,
			&i.PoolEffectiveCapacity.AvailableBytesEffective,
			&i.NodeEffectiveAvailability.ID,
			&i.NodeEffectiveAvailability.Name,
			&i.NodeEffectiveAvailability.Architecture,
			&i.NodeEffectiveAvailability.AdvertisedEndpoint,
			&i.NodeEffectiveAvailability.MigrationHost,
			&i.NodeEffectiveAvailability.MigrationPortRangeStart,
			&i.NodeEffectiveAvailability.MigrationPortRangeEnd,
			&i.NodeEffectiveAvailability.Status,
			&i.NodeEffectiveAvailability.CordonedAt,
			&i.NodeEffectiveAvailability.CPUCoresTotal,
			&i.NodeEffectiveAvailability.CPUCoresAvailable,
			&i.NodeEffectiveAvailability.CPUModel,
			&i.NodeEffectiveAvailability.CpuFlags,
			&i.NodeEffectiveAvailability.MemoryTotalMib,
			&i.NodeEffectiveAvailability.MemoryAvailableMib,
			&i.NodeEffectiveAvailability.Hugepages2mibTotal,
			&i.NodeEffectiveAvailability.Hugepages1gibTotal,
			&i.NodeEffectiveAvailability.KernelVersion,
			&i.NodeEffectiveAvailability.QEMUVersion,
			&i.NodeEffectiveAvailability.NumaTopology,
			&i.NodeEffectiveAvailability.Capabilities,
			&i.NodeEffectiveAvailability.LastHeartbeatAt,
			&i.NodeEffectiveAvailability.AgentVersion,
			&i.NodeEffectiveAvailability.Labels,
			&i.NodeEffectiveAvailability.MemoryPressureSince,
			&i.NodeEffectiveAvailability.MemoryPressureCount,
			&i.NodeEffectiveAvailability.SystemDiskTotalBytes,
			&i.NodeEffectiveAvailability.SystemDiskAvailableBytes,
			&i.NodeEffectiveAvailability.SystemDiskPressureSince,
			&i.NodeEffectiveAvailability.SystemDiskPressureCount,
			&i.NodeEffectiveAvailability.CreatedAt,
			&i.NodeEffectiveAvailability.UpdatedAt,
			&i.NodeEffectiveAvailability.DeletedAt,
			&i.NodeEffectiveAvailability.CPUCoresEffective,
			&i.NodeEffectiveAvailability.MemoryEffectiveMib,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolsEffective = `-- name: ListPoolsEffective :many
select id, node_id, name, type, path, capacity_bytes, available_bytes, reported_at, config, disk_pressure_since, disk_pressure_count, reconciliation_status, last_reconciled_at, reconciliation_error, created_at, updated_at, deleted_at, available_bytes_effective from pool_effective_capacity
where deleted_at is null
  and ($1::uuid is null or node_id = $1::uuid)
  and ($2::text is null or type = $2::text)
  and (
    $3::timestamptz is null
    or (created_at, id) > (
      $3::timestamptz,
      $4::uuid
    )
  )
order by created_at, id
limit $5
`

type ListPoolsEffectiveParams struct {
	NodeID          *uuid.UUID
	Type            *string
	CursorCreatedAt *time.Time
	CursorID        *uuid.UUID
	LimitCount      int32
}

// View-backed parallel к ListStoragePools — same optional ?node_id /
// ?type filters и (created_at, id) cursor pagination,
// но every row carries `available_bytes_effective`. Soft-deleted rows
// excluded by construction (view itself emits no rows when raw is
// soft-deleted — see the WHERE clause on the view).
func (q *Queries) ListPoolsEffective(ctx context.Context, arg ListPoolsEffectiveParams) ([]PoolEffectiveCapacity, error) {
	rows, err := q.db.Query(ctx, listPoolsEffective,
		arg.NodeID,
		arg.Type,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoolEffectiveCapacity{}
	for rows.Next() {
		var i PoolEffectiveCapacity
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.Type,
			&i.Path,
			&i.CapacityBytes,
			&i.AvailableBytes,
			&i.ReportedAt,
			&i.Config,
			&i.DiskPressureSince,
			&i.DiskPressureCount,
			&i.ReconciliationStatus,
			&i.LastReconciledAt,
			&i.ReconciliationError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AvailableBytesEffective,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolsEffectiveByName = `-- name: ListPoolsEffectiveByName :many
select id, node_id, name, type, path, capacity_bytes, available_bytes, reported_at, config, disk_pressure_since, disk_pressure_count, reconciliation_status, last_reconciled_at, reconciliation_error, created_at, updated_at, deleted_at, available_bytes_effective from pool_effective_capacity
where lower(name) = lower($1)
  and deleted_at is null
order by node_id
`

// View-backed parallel к ListStoragePoolsByName. Drives the
// name-aggregated `GET /v1/storage-pools/{name}` projection so each
// per-node instance carries effective bytes.
func (q *Queries) ListPoolsEffectiveByName(ctx context.Context, name string) ([]PoolEffectiveCapacity, error) {
	rows, err := q.db.Query(ctx, listPoolsEffectiveByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoolEffectiveCapacity{}
	for rows.Next() {
		var i PoolEffectiveCapacity
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.Type,
			&i.Path,
			&i.CapacityBytes,
			&i.AvailableBytes,
			&i.ReportedAt,
			&i.Config,
			&i.DiskPressureSince,
			&i.DiskPressureCount,
			&i.ReconciliationStatus,
			&i.LastReconciledAt,
			&i.ReconciliationError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AvailableBytesEffective,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolsNeedingScan = `-- name: ListPoolsNeedingScan :many
select p.id, p.name, p.node_id
from storage_pools p
join nodes n on n.id = p.node_id
where p.deleted_at is null
  and n.deleted_at is null
  and n.status in ('pending', 'ready', 'cordoned')
  and not exists (
    select 1
    from tasks t
    where t.type = 'storage_pool.scan'
      and t.status in ('pending', 'running')
      and t.resource_id = p.id
  )
order by p.id
`

type ListPoolsNeedingScanRow struct {
	ID     uuid.UUID
	Name   string
	NodeID uuid.UUID
}

// Returns active storage_pools whose owning node is in a scannable
// status, excluding pools that already have an in-flight scan task
// (a `tasks` row of type `storage_pool.scan` in status pending or
// running referencing the pool). Drives the `storage_pool.scan_trigger`
// periodic worker: each tick fans out fresh scan tasks only к pools
// that need а refresh, leaving in-flight scans untouched. Ordering on
// `p.id` is stable across ticks so log lines correlate predictably.
func (q *Queries) ListPoolsNeedingScan(ctx context.Context) ([]ListPoolsNeedingScanRow, error) {
	rows, err := q.db.Query(ctx, listPoolsNeedingScan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPoolsNeedingScanRow{}
	for rows.Next() {
		var i ListPoolsNeedingScanRow
		if err := rows.Scan(&i.ID, &i.Name, &i.NodeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoragePools = `-- name: ListStoragePools :many
select id, node_id, name, type, path, capacity_bytes, available_bytes, reported_at, config, disk_pressure_since, disk_pressure_count, reconciliation_status, last_reconciled_at, reconciliation_error, created_at, updated_at, deleted_at
from storage_pools
where deleted_at is null
  and ($1::uuid is null or node_id = $1::uuid)
  and ($2::text is null or type = $2::text)
  and (
    $3::timestamptz is null
    or (created_at, id) > (
      $3::timestamptz,
      $4::uuid
    )
  )
order by created_at, id
limit $5
`

type ListStoragePoolsParams struct {
	NodeID          *uuid.UUID
	Type            *string
	CursorCreatedAt *time.Time
	CursorID        *uuid.UUID
	LimitCount      int32
}

// Optional ?node_id and ?type filters. Cursor pagination.
// Soft-deleted rows are excluded.
func (q *Queries) ListStoragePools(ctx context.Context, arg ListStoragePoolsParams) ([]StoragePool, error) {
	rows, err := q.db.Query(ctx, listStoragePools,
		arg.NodeID,
		arg.Type,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoragePool{}
	for rows.Next() {
		var i StoragePool
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.Type,
			&i.Path,
			&i.CapacityBytes,
			&i.AvailableBytes,
			&i.ReportedAt,
			&i.Config,
			&i.DiskPressureSince,
			&i.DiskPressureCount,
			&i.ReconciliationStatus,
			&i.LastReconciledAt,
			&i.ReconciliationError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoragePoolsByName = `-- name: ListStoragePoolsByName :many
select id, node_id, name, type, path, capacity_bytes, available_bytes, reported_at, config, disk_pressure_since, disk_pressure_count, reconciliation_status, last_reconciled_at, reconciliation_error, created_at, updated_at, deleted_at
from storage_pools
where lower(name) = lower($1)
  and deleted_at is null
order by node_id
`

// Returns every instance of a pool name across the cluster. The
// multi-instance model permits the same name on multiple nodes
// simultaneously; bare-name resolution is therefore an aggregation, not a
// single-row lookup. Case-folded match honours uq_storage_pools_name's
// functional component.
func (q *Queries) ListStoragePoolsByName(ctx context.Context, name string) ([]StoragePool, error) {
	rows, err := q.db.Query(ctx, listStoragePoolsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoragePool{}
	for rows.Next() {
		var i StoragePool
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.Type,
			&i.Path,
			&i.CapacityBytes,
			&i.AvailableBytes,
			&i.ReportedAt,
			&i.Config,
			&i.DiskPressureSince,
			&i.DiskPressureCount,
			&i.ReconciliationStatus,
			&i.LastReconciledAt,
			&i.ReconciliationError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoragePoolsByNode = `-- name: ListStoragePoolsByNode :many
select id, node_id, name, type, path, capacity_bytes, available_bytes, reported_at, config, disk_pressure_since, disk_pressure_count, reconciliation_status, last_reconciled_at, reconciliation_error, created_at, updated_at, deleted_at
from storage_pools
where node_id = $1
  and deleted_at is null
order by lower(name)
`

// Returns every active pool row owned by the given node, ordered for
// stable heartbeat responses (operator-facing field order should not
// jitter between heartbeats). Drives the heartbeat handler's
// `declared_pools` response field — the agent reconciler
// consumes this list as the desired-state cache.
func (q *Queries) ListStoragePoolsByNode(ctx context.Context, nodeID uuid.UUID) ([]StoragePool, error) {
	rows, err := q.db.Query(ctx, listStoragePoolsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoragePool{}
	for rows.Next() {
		var i StoragePool
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.Type,
			&i.Path,
			&i.CapacityBytes,
			&i.AvailableBytes,
			&i.ReportedAt,
			&i.Config,
			&i.DiskPressureSince,
			&i.DiskPressureCount,
			&i.ReconciliationStatus,
			&i.LastReconciledAt,
			&i.ReconciliationError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemDiskPressuredCandidatesByName = `-- name: ListSystemDiskPressuredCandidatesByName :many
select p.id, p.node_id, p.name, p.type, p.path, p.capacity_bytes, p.available_bytes, p.reported_at, p.config, p.disk_pressure_since, p.disk_pressure_count, p.reconciliation_status, p.last_reconciled_at, p.reconciliation_error, p.created_at, p.updated_at, p.deleted_at, p.available_bytes_effective, n.id, n.name, n.architecture, n.advertised_endpoint, n.migration_host, n.migration_port_range_start, n.migration_port_range_end, n.status, n.cordoned_at, n.cpu_cores_total, n.cpu_cores_available, n.cpu_model, n.cpu_flags, n.memory_total_mib, n.memory_available_mib, n.hugepages_2mib_total, n.hugepages_1gib_total, n.kernel_version, n.qemu_version, n.numa_topology, n.capabilities, n.last_heartbeat_at, n.agent_version, n.labels, n.memory_pressure_since, n.memory_pressure_count, n.system_disk_total_bytes, n.system_disk_available_bytes, n.system_disk_pressure_since, n.system_disk_pressure_count, n.created_at, n.updated_at, n.deleted_at, n.cpu_cores_effective, n.memory_effective_mib
from pool_effective_capacity p
join node_effective_availability n on n.id = p.node_id
where lower(p.name) = lower($1)
  and p.deleted_at is null
  and n.deleted_at is null
  and n.status = 'ready'
  and n.cordoned_at is null
  and n.system_disk_pressure_since is not null
order by n.id
`

type ListSystemDiskPressuredCandidatesByNameRow struct {
	PoolEffectiveCapacity     PoolEffectiveCapacity
	NodeEffectiveAvailability NodeEffectiveAvailability
}

// Diagnostic-only sibling of ListMemoryPressuredCandidatesByName for
// the system-disk pressure condition.
// Returns pool instances on nodes flagged с system_disk_pressure_since
// IS NOT NULL. Same eligibility predicates as the memory variant —
// only the inverted pressure filter differs.
func (q *Queries) ListSystemDiskPressuredCandidatesByName(ctx context.Context, name string) ([]ListSystemDiskPressuredCandidatesByNameRow, error) {
	rows, err := q.db.Query(ctx, listSystemDiskPressuredCandidatesByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSystemDiskPressuredCandidatesByNameRow{}
	for rows.Next() {
		var i ListSystemDiskPressuredCandidatesByNameRow
		if err := rows.Scan(
			&i.PoolEffectiveCapacity.ID,
			&i.PoolEffectiveCapacity.NodeID,
			&i.PoolEffectiveCapacity.Name,
			&i.PoolEffectiveCapacity.Type,
			&i.PoolEffectiveCapacity.Path,
			&i.PoolEffectiveCapacity.CapacityBytes,
			&i.PoolEffectiveCapacity.AvailableBytes,
			&i.PoolEffectiveCapacity.ReportedAt,
			&i.PoolEffectiveCapacity.Config,
			&i.PoolEffectiveCapacity.DiskPressureSince,
			&i.PoolEffectiveCapacity.DiskPressureCount,
			&i.PoolEffectiveCapacity.ReconciliationStatus,
			&i.PoolEffectiveCapacity.LastReconciledAt,
			&i.PoolEffectiveCapacity.ReconciliationError,
			&i.PoolEffectiveCapacity.CreatedAt,
			&i.PoolEffectiveCapacity.UpdatedAt,
			&i.PoolEffectiveCapacity.DeletedAt,
			&i.PoolEffectiveCapacity.AvailableBytesEffective,
			&i.NodeEffectiveAvailability.ID,
			&i.NodeEffectiveAvailability.Name,
			&i.NodeEffectiveAvailability.Architecture,
			&i.NodeEffectiveAvailability.AdvertisedEndpoint,
			&i.NodeEffectiveAvailability.MigrationHost,
			&i.NodeEffectiveAvailability.MigrationPortRangeStart,
			&i.NodeEffectiveAvailability.MigrationPortRangeEnd,
			&i.NodeEffectiveAvailability.Status,
			&i.NodeEffectiveAvailability.CordonedAt,
			&i.NodeEffectiveAvailability.CPUCoresTotal,
			&i.NodeEffectiveAvailability.CPUCoresAvailable,
			&i.NodeEffectiveAvailability.CPUModel,
			&i.NodeEffectiveAvailability.CpuFlags,
			&i.NodeEffectiveAvailability.MemoryTotalMib,
			&i.NodeEffectiveAvailability.MemoryAvailableMib,
			&i.NodeEffectiveAvailability.Hugepages2mibTotal,
			&i.NodeEffectiveAvailability.Hugepages1gibTotal,
			&i.NodeEffectiveAvailability.KernelVersion,
			&i.NodeEffectiveAvailability.QEMUVersion,
			&i.NodeEffectiveAvailability.NumaTopology,
			&i.NodeEffectiveAvailability.Capabilities,
			&i.NodeEffectiveAvailability.LastHeartbeatAt,
			&i.NodeEffectiveAvailability.AgentVersion,
			&i.NodeEffectiveAvailability.Labels,
			&i.NodeEffectiveAvailability.MemoryPressureSince,
			&i.NodeEffectiveAvailability.MemoryPressureCount,
			&i.NodeEffectiveAvailability.SystemDiskTotalBytes,
			&i.NodeEffectiveAvailability.SystemDiskAvailableBytes,
			&i.NodeEffectiveAvailability.SystemDiskPressureSince,
			&i.NodeEffectiveAvailability.SystemDiskPressureCount,
			&i.NodeEffectiveAvailability.CreatedAt,
			&i.NodeEffectiveAvailability.UpdatedAt,
			&i.NodeEffectiveAvailability.DeletedAt,
			&i.NodeEffectiveAvailability.CPUCoresEffective,
			&i.NodeEffectiveAvailability.MemoryEffectiveMib,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteStoragePool = `-- name: SoftDeleteStoragePool :exec
update storage_pools
set deleted_at = now()
where id = $1
  and deleted_at is null
`

func (q *Queries) SoftDeleteStoragePool(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteStoragePool, id)
	return err
}

const updatePoolDiskPressure = `-- name: UpdatePoolDiskPressure :exec
update storage_pools
set
    disk_pressure_since = $1::timestamptz,
    disk_pressure_count = $2::int
where id = $3
  and deleted_at is null
`

type UpdatePoolDiskPressureParams struct {
	DiskPressureSince *time.Time
	DiskPressureCount int32
	ID                uuid.UUID
}

// Persists the pool disk pressure transition.
// Caller runs this in the same transaction as UpsertStoragePoolUsage so
// pressure state never drifts ahead of the scan that determined it.
func (q *Queries) UpdatePoolDiskPressure(ctx context.Context, arg UpdatePoolDiskPressureParams) error {
	_, err := q.db.Exec(ctx, updatePoolDiskPressure, arg.DiskPressureSince, arg.DiskPressureCount, arg.ID)
	return err
}

const updateStoragePool = `-- name: UpdateStoragePool :one
update storage_pools
set name   = $1,
    config = $2
where id = $3
  and deleted_at is null
returning id, node_id, name, type, path, capacity_bytes, available_bytes, reported_at, config, disk_pressure_since, disk_pressure_count, reconciliation_status, last_reconciled_at, reconciliation_error, created_at, updated_at, deleted_at
`

type UpdateStoragePoolParams struct {
	Name   string
	Config []byte
	ID     uuid.UUID
}

// Caller merges the patch with the current row before issuing this
// query (the same pattern as UpdateNetwork). The `node_id`, `type` and
// `path` columns are intentionally absent from the SET list — they are
// API-immutable. capacity_bytes / available_bytes / reported_at are
// owned by the heartbeat / scan path and are never touched by this
// handler-driven update.
func (q *Queries) UpdateStoragePool(ctx context.Context, arg UpdateStoragePoolParams) (StoragePool, error) {
	row := q.db.QueryRow(ctx, updateStoragePool, arg.Name, arg.Config, arg.ID)
	var i StoragePool
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Type,
		&i.Path,
		&i.CapacityBytes,
		&i.AvailableBytes,
		&i.ReportedAt,
		&i.Config,
		&i.DiskPressureSince,
		&i.DiskPressureCount,
		&i.ReconciliationStatus,
		&i.LastReconciledAt,
		&i.ReconciliationError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateStoragePoolReconciliation = `-- name: UpdateStoragePoolReconciliation :exec
update storage_pools
set
    reconciliation_status = $1::text,
    reconciliation_error  = $2::text,
    last_reconciled_at    = now()
where node_id = $3
  and lower(name) = lower($4)
  and deleted_at is null
`

type UpdateStoragePoolReconciliationParams struct {
	ReconciliationStatus string
	ReconciliationError  *string
	NodeID               uuid.UUID
	Name                 string
}

// Applies the agent's reconciliation report for a single pool. Called
// by the heartbeat handler once per reported pool per heartbeat. The
// match key is (node_id, lower(name)) — а pool name maps к multiple
// rows cluster-wide, but only one per node. Soft-deleted rows are
// skipped silently (no rows affected): operator deleted the pool
// mid-tick; the agent will drop it от observed state on the next
// reconciliation cycle. error is set к the empty string когда the
// agent reports success, NULL когда the status itself is not 'failed'.
func (q *Queries) UpdateStoragePoolReconciliation(ctx context.Context, arg UpdateStoragePoolReconciliationParams) error {
	_, err := q.db.Exec(ctx, updateStoragePoolReconciliation,
		arg.ReconciliationStatus,
		arg.ReconciliationError,
		arg.NodeID,
		arg.Name,
	)
	return err
}

const upsertStoragePoolUsage = `-- name: UpsertStoragePoolUsage :exec
update storage_pools
set capacity_bytes  = $1,
    available_bytes = $2,
    reported_at     = now()
where id = $3
  and deleted_at is null
`

type UpsertStoragePoolUsageParams struct {
	CapacityBytes  *int64
	AvailableBytes *int64
	ID             uuid.UUID
}

// Scan-result projection. Agent-reported capacity /
// availability merge onto the row; handler-driven CRUD никогда не
// writes these columns. The scan worker pairs this с
// GetPoolDiskPressureState + UpdatePoolDiskPressure inside the same
// transaction so pool disk pressure stays
// consistent с the metrics that determined it.
func (q *Queries) UpsertStoragePoolUsage(ctx context.Context, arg UpsertStoragePoolUsageParams) error {
	_, err := q.db.Exec(ctx, upsertStoragePoolUsage, arg.CapacityBytes, arg.AvailableBytes, arg.ID)
	return err
}
