// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelTaskIfPending = `-- name: CancelTaskIfPending :one
update tasks
set status      = 'cancelled',
    finished_at = now()
where id = $1
  and status = 'pending'
returning id, type, status, resource_type, resource_id, progress, args, result, error, attempts, max_attempts, river_job_id, agent_task_id, created_by, created_at, started_at, finished_at
`

// Cancel a task only while it is still pending. Returns the updated
// row when status was pending; returns pgx.ErrNoRows for any other
// state — the caller maps that to a 409 (running cancel is deferred
// to future work; terminal cancel is idempotent-409).
func (q *Queries) CancelTaskIfPending(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, cancelTaskIfPending, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.ResourceType,
		&i.ResourceID,
		&i.Progress,
		&i.Args,
		&i.Result,
		&i.Error,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RiverJobID,
		&i.AgentTaskID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
insert into tasks (
    id,
    type,
    status,
    resource_type,
    resource_id,
    args,
    max_attempts,
    created_by
)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
returning id, type, status, resource_type, resource_id, progress, args, result, error, attempts, max_attempts, river_job_id, agent_task_id, created_by, created_at, started_at, finished_at
`

type CreateTaskParams struct {
	ID           uuid.UUID
	Type         string
	Status       TaskStatus
	ResourceType string
	ResourceID   *uuid.UUID
	Args         []byte
	MaxAttempts  int32
	CreatedBy    *uuid.UUID
}

// Inserts a fresh task row. The handler runs this in the same SQL
// transaction as the river job enqueue; the river_job_id is stamped
// onto the row via UpdateTaskRiverJobID after river.InsertTx returns.
// result / error / progress / started_at / finished_at default to NULL.
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.Type,
		arg.Status,
		arg.ResourceType,
		arg.ResourceID,
		arg.Args,
		arg.MaxAttempts,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.ResourceType,
		&i.ResourceID,
		&i.Progress,
		&i.Args,
		&i.Result,
		&i.Error,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RiverJobID,
		&i.AgentTaskID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteExpiredTasks = `-- name: DeleteExpiredTasks :execrows
delete from tasks
where finished_at is not null
  and (
    (status = 'success'                  and finished_at < $1::timestamptz)
    or
    (status in ('failed', 'cancelled')   and finished_at < $2::timestamptz)
  )
`

type DeleteExpiredTasksParams struct {
	CompletedCutoff time.Time
	FailedCutoff    time.Time
}

// State-aware retention. The two cutoffs are
// independent: success rows past @completed_cutoff and failed /
// cancelled rows past @failed_cutoff are removed in one DELETE. Only
// finalized rows (finished_at IS NOT NULL) are eligible — the partial
// index idx_tasks_finished_at supports the scan.
func (q *Queries) DeleteExpiredTasks(ctx context.Context, arg DeleteExpiredTasksParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredTasks, arg.CompletedCutoff, arg.FailedCutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTask = `-- name: GetTask :one
select id, type, status, resource_type, resource_id, progress, args, result, error, attempts, max_attempts, river_job_id, agent_task_id, created_by, created_at, started_at, finished_at
from tasks
where id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.ResourceType,
		&i.ResourceID,
		&i.Progress,
		&i.Args,
		&i.Result,
		&i.Error,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RiverJobID,
		&i.AgentTaskID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listTasksAny = `-- name: ListTasksAny :many
select id, type, status, resource_type, resource_id, progress, args, result, error, attempts, max_attempts, river_job_id, agent_task_id, created_by, created_at, started_at, finished_at
from tasks
where ($1::text is null or status::text = $1::text)
  and ($2::text is null or type = $2::text)
  and ($3::text is null or resource_type = $3::text)
  and ($4::uuid is null or resource_id = $4::uuid)
  and (
    $5::timestamptz is null
    or (created_at, id) < (
      $5::timestamptz,
      $6::uuid
    )
  )
order by created_at desc, id desc
limit $7
`

type ListTasksAnyParams struct {
	StatusFilter       *string
	TypeFilter         *string
	ResourceTypeFilter *string
	ResourceIDFilter   *uuid.UUID
	CursorCreatedAt    *time.Time
	CursorID           *uuid.UUID
	LimitCount         int32
}

// Admin / operator scope: see all tasks. Filters compose with AND;
// omitted filters pass NULL and are no-ops. Cursor pagination keyed on
// (created_at, id) — DESC ordering means tuple comparison flows in
// the < direction.
func (q *Queries) ListTasksAny(ctx context.Context, arg ListTasksAnyParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksAny,
		arg.StatusFilter,
		arg.TypeFilter,
		arg.ResourceTypeFilter,
		arg.ResourceIDFilter,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.ResourceType,
			&i.ResourceID,
			&i.Progress,
			&i.Args,
			&i.Result,
			&i.Error,
			&i.Attempts,
			&i.MaxAttempts,
			&i.RiverJobID,
			&i.AgentTaskID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksOwn = `-- name: ListTasksOwn :many
select id, type, status, resource_type, resource_id, progress, args, result, error, attempts, max_attempts, river_job_id, agent_task_id, created_by, created_at, started_at, finished_at
from tasks
where created_by = $1
  and ($2::text is null or status::text = $2::text)
  and ($3::text is null or type = $3::text)
  and ($4::text is null or resource_type = $4::text)
  and ($5::uuid is null or resource_id = $5::uuid)
  and (
    $6::timestamptz is null
    or (created_at, id) < (
      $6::timestamptz,
      $7::uuid
    )
  )
order by created_at desc, id desc
limit $8
`

type ListTasksOwnParams struct {
	CreatedBy          *uuid.UUID
	StatusFilter       *string
	TypeFilter         *string
	ResourceTypeFilter *string
	ResourceIDFilter   *uuid.UUID
	CursorCreatedAt    *time.Time
	CursorID           *uuid.UUID
	LimitCount         int32
}

// Developer / viewer scope: only tasks created by the principal.
// Same filter / cursor surface as ListTasksAny.
func (q *Queries) ListTasksOwn(ctx context.Context, arg ListTasksOwnParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksOwn,
		arg.CreatedBy,
		arg.StatusFilter,
		arg.TypeFilter,
		arg.ResourceTypeFilter,
		arg.ResourceIDFilter,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.ResourceType,
			&i.ResourceID,
			&i.Progress,
			&i.Args,
			&i.Result,
			&i.Error,
			&i.Attempts,
			&i.MaxAttempts,
			&i.RiverJobID,
			&i.AgentTaskID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskAgentTaskID = `-- name: UpdateTaskAgentTaskID :exec
update tasks
set agent_task_id = $1
where id = $2
`

type UpdateTaskAgentTaskIDParams struct {
	AgentTaskID *uuid.UUID
	ID          uuid.UUID
}

// Stamps the agent-side task id on the CP task row. Called by an
// insert-driven agent-saga worker after the agent's 202 response
// (storage_image.import is the first consumer). Persisting the id
// makes a CP-side restart resume polling the existing agent task
// instead of issuing a duplicate POST (worker resumption seam).
// storage_pool.scan does NOT populate this column — its task surface
// stays nil.
func (q *Queries) UpdateTaskAgentTaskID(ctx context.Context, arg UpdateTaskAgentTaskIDParams) error {
	_, err := q.db.Exec(ctx, updateTaskAgentTaskID, arg.AgentTaskID, arg.ID)
	return err
}

const updateTaskFinalized = `-- name: UpdateTaskFinalized :exec
update tasks
set status      = $1,
    result      = $2,
    error       = $3,
    finished_at = now()
where id = $4
`

type UpdateTaskFinalizedParams struct {
	Status TaskStatus
	Result []byte
	Error  []byte
	ID     uuid.UUID
}

// Worker exit: terminal status (success / failed / cancelled), the
// result / error JSONB payloads, and finished_at. The caller passes
// result and error; both nullable JSONB columns and either may be NULL
// depending on the terminal branch.
func (q *Queries) UpdateTaskFinalized(ctx context.Context, arg UpdateTaskFinalizedParams) error {
	_, err := q.db.Exec(ctx, updateTaskFinalized,
		arg.Status,
		arg.Result,
		arg.Error,
		arg.ID,
	)
	return err
}

const updateTaskRiverJobID = `-- name: UpdateTaskRiverJobID :exec
update tasks
set river_job_id = $1
where id = $2
`

type UpdateTaskRiverJobIDParams struct {
	RiverJobID *int64
	ID         uuid.UUID
}

// Stamps the river job id onto the task row inside the atomic enqueue
// transaction (after river.InsertTx returns). The column carries a
// weak reference (no FK) used only for ops
// drill-down.
func (q *Queries) UpdateTaskRiverJobID(ctx context.Context, arg UpdateTaskRiverJobIDParams) error {
	_, err := q.db.Exec(ctx, updateTaskRiverJobID, arg.RiverJobID, arg.ID)
	return err
}

const updateTaskRunning = `-- name: UpdateTaskRunning :exec
update tasks
set status     = 'running',
    started_at = coalesce(started_at, now()),
    attempts   = attempts + 1
where id = $1
`

// Worker entry: pending → running. Increments the attempt counter and
// stamps started_at on the first transition (idempotent across retries
// thanks to COALESCE).
func (q *Queries) UpdateTaskRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateTaskRunning, id)
	return err
}
