// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cloneTemplate = `-- name: CloneTemplate :one
insert into templates (
    id,
    owner_id,
    name,
    description,
    visibility,
    architecture,
    os_family,
    os_variant,
    image_url,
    image_checksum_sha256,
    image_format,
    image_size_bytes,
    firmware_type,
    firmware_id,
    default_cpu_cores,
    default_memory_mib,
    default_disk_gib,
    cloud_init_supported,
    cloud_init_user_data,
    qemu_guest_agent_expected,
    metadata
)
select
    $1::uuid,
    $2::uuid,
    $3::text,
    coalesce($4::text, description),
    'private',
    architecture,
    os_family,
    os_variant,
    image_url,
    image_checksum_sha256,
    image_format,
    image_size_bytes,
    firmware_type,
    firmware_id,
    default_cpu_cores,
    default_memory_mib,
    default_disk_gib,
    cloud_init_supported,
    cloud_init_user_data,
    qemu_guest_agent_expected,
    metadata
from templates
where id = $5::uuid
  and deleted_at is null
returning id, owner_id, name, description, visibility, architecture, os_family, os_variant, image_url, image_checksum_sha256, image_format, image_size_bytes, firmware_type, firmware_id, default_cpu_cores, default_memory_mib, default_disk_gib, cloud_init_supported, cloud_init_user_data, qemu_guest_agent_expected, metadata, derived_vm_count, created_at, updated_at, deleted_at
`

type CloneTemplateParams struct {
	NewID          uuid.UUID
	NewOwnerID     uuid.UUID
	NewName        string
	NewDescription *string
	SourceID       uuid.UUID
}

// INSERT-SELECT clone. The new row is owned by the caller, named by
// the caller, and starts in visibility='private' (Variant C — same
// invariant as CreateTemplate). Description falls through to the
// source's description when the caller omits it. Image-source bundle
// (url + checksum + format + size), sizing, capabilities, metadata,
// firmware pin, os_variant, and architecture / os_family are copied
// verbatim — clone is a metadata copy and does not re-fetch the image.
//
// Returns 0 rows when source is missing or soft-deleted (handler maps
// to 404). uq_templates_name surfaces as 23505 → 409 with a neutral
// "template with this name already exists" message.
func (q *Queries) CloneTemplate(ctx context.Context, arg CloneTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, cloneTemplate,
		arg.NewID,
		arg.NewOwnerID,
		arg.NewName,
		arg.NewDescription,
		arg.SourceID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.Architecture,
		&i.OsFamily,
		&i.OsVariant,
		&i.ImageUrl,
		&i.ImageChecksumSha256,
		&i.ImageFormat,
		&i.ImageSizeBytes,
		&i.FirmwareType,
		&i.FirmwareID,
		&i.DefaultCpuCores,
		&i.DefaultMemoryMib,
		&i.DefaultDiskGib,
		&i.CloudInitSupported,
		&i.CloudInitUserData,
		&i.QemuGuestAgentExpected,
		&i.Metadata,
		&i.DerivedVmCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countActiveVMsForTemplate = `-- name: CountActiveVMsForTemplate :one
select count(*)::bigint as vm_count
from vms
where template_id = $1::uuid
  and deleted_at is null
`

// Precheck before DELETE /v1/templates/{id}: counts active vms that
// still reference the template. Soft-deleted vms are excluded — a
// removed VM has no live consumption of the template's image rec.
//
// The vms.template_id FK is ON DELETE SET NULL by design — orphaned
// VMs continue to run from the cached image blob, since the template
// was only the recipe used to provision the disk, not a runtime
// dependency. Hence the API-level policy: deleting a template should
// be an explicit operator decision, not a silent reference-nulling.
// This counter is the sole enforcement of that policy (soft-delete
// bypasses the FK action; vm_disks.source_template_id RESTRICT and
// node_image_cache CASCADE only fire on a hard delete that this
// handler never issues).
func (q *Queries) CountActiveVMsForTemplate(ctx context.Context, templateID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveVMsForTemplate, templateID)
	var vm_count int64
	err := row.Scan(&vm_count)
	return vm_count, err
}

const createTemplate = `-- name: CreateTemplate :one
insert into templates (
    id,
    owner_id,
    name,
    description,
    visibility,
    architecture,
    os_family,
    os_variant,
    image_url,
    image_checksum_sha256,
    image_format,
    image_size_bytes,
    firmware_type,
    firmware_id,
    default_cpu_cores,
    default_memory_mib,
    default_disk_gib,
    cloud_init_supported,
    cloud_init_user_data,
    qemu_guest_agent_expected,
    metadata
)
values (
    $1,
    $2,
    $3,
    $4,
    'private',
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11::bigint,
    $12,
    $13::uuid,
    $14,
    $15,
    $16,
    $17,
    $18::text,
    $19,
    $20
)
returning id, owner_id, name, description, visibility, architecture, os_family, os_variant, image_url, image_checksum_sha256, image_format, image_size_bytes, firmware_type, firmware_id, default_cpu_cores, default_memory_mib, default_disk_gib, cloud_init_supported, cloud_init_user_data, qemu_guest_agent_expected, metadata, derived_vm_count, created_at, updated_at, deleted_at
`

type CreateTemplateParams struct {
	ID                     uuid.UUID
	OwnerID                uuid.UUID
	Name                   string
	Description            string
	Architecture           CpuArch
	OsFamily               OsFamily
	OsVariant              string
	ImageUrl               string
	ImageChecksumSha256    []byte
	ImageFormat            ImageFormat
	ImageSizeBytes         *int64
	FirmwareType           FirmwareType
	FirmwareID             *uuid.UUID
	DefaultCpuCores        int32
	DefaultMemoryMib       int32
	DefaultDiskGib         int32
	CloudInitSupported     bool
	CloudInitUserData      *string
	QemuGuestAgentExpected bool
	Metadata               []byte
}

// Templates are always created with visibility='private' (variant C of
// the create-permission model — see CLAUDE.md "Authorization (RBAC)"
// and ROADMAP). The literal is hard-coded in this INSERT rather than
// accepted as a parameter so a future call site cannot opt out by
// mistake; visibility moves only through SetTemplateVisibility, which
// carries the dedicated `template:set_visibility` permission. Name
// uniqueness is enforced by uq_templates_name (global, not per-owner)
// and surfaces as 23505 → 409 in the handler with a neutral
// "template with this name already exists" message.
func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Architecture,
		arg.OsFamily,
		arg.OsVariant,
		arg.ImageUrl,
		arg.ImageChecksumSha256,
		arg.ImageFormat,
		arg.ImageSizeBytes,
		arg.FirmwareType,
		arg.FirmwareID,
		arg.DefaultCpuCores,
		arg.DefaultMemoryMib,
		arg.DefaultDiskGib,
		arg.CloudInitSupported,
		arg.CloudInitUserData,
		arg.QemuGuestAgentExpected,
		arg.Metadata,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.Architecture,
		&i.OsFamily,
		&i.OsVariant,
		&i.ImageUrl,
		&i.ImageChecksumSha256,
		&i.ImageFormat,
		&i.ImageSizeBytes,
		&i.FirmwareType,
		&i.FirmwareID,
		&i.DefaultCpuCores,
		&i.DefaultMemoryMib,
		&i.DefaultDiskGib,
		&i.CloudInitSupported,
		&i.CloudInitUserData,
		&i.QemuGuestAgentExpected,
		&i.Metadata,
		&i.DerivedVmCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const decrementTemplateDerivedVMCount = `-- name: DecrementTemplateDerivedVMCount :exec
update templates
set derived_vm_count = derived_vm_count - 1
where id = $1
  and deleted_at is null
  and derived_vm_count > 0
`

// Drops templates.derived_vm_count by one. Called from VMDeleteWorker's
// success projection inside the same InTx as the soft-delete chain.
// The decrement is a guarded UPDATE — `where deleted_at is null and
// derived_vm_count > 0` — so a stale call against a soft-deleted
// template OR a counter that has already drifted к zero is a silent
// no-op rather than a 23514 check-constraint violation.
func (q *Queries) DecrementTemplateDerivedVMCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementTemplateDerivedVMCount, id)
	return err
}

const getTemplate = `-- name: GetTemplate :one
select id, owner_id, name, description, visibility, architecture, os_family, os_variant, image_url, image_checksum_sha256, image_format, image_size_bytes, firmware_type, firmware_id, default_cpu_cores, default_memory_mib, default_disk_gib, cloud_init_supported, cloud_init_user_data, qemu_guest_agent_expected, metadata, derived_vm_count, created_at, updated_at, deleted_at
from templates
where id = $1
  and deleted_at is null
`

// Soft-deleted rows are invisible to every read path; a Get that
// targets a deleted template returns pgx.ErrNoRows and the handler
// surfaces 404. The partial index uq_templates_name (where deleted_at
// is null) means a freed name is reusable immediately after delete.
func (q *Queries) GetTemplate(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.Architecture,
		&i.OsFamily,
		&i.OsVariant,
		&i.ImageUrl,
		&i.ImageChecksumSha256,
		&i.ImageFormat,
		&i.ImageSizeBytes,
		&i.FirmwareType,
		&i.FirmwareID,
		&i.DefaultCpuCores,
		&i.DefaultMemoryMib,
		&i.DefaultDiskGib,
		&i.CloudInitSupported,
		&i.CloudInitUserData,
		&i.QemuGuestAgentExpected,
		&i.Metadata,
		&i.DerivedVmCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTemplateByName = `-- name: GetTemplateByName :one
select id, owner_id, name, description, visibility, architecture, os_family, os_variant, image_url, image_checksum_sha256, image_format, image_size_bytes, firmware_type, firmware_id, default_cpu_cores, default_memory_mib, default_disk_gib, cloud_init_supported, cloud_init_user_data, qemu_guest_agent_expected, metadata, derived_vm_count, created_at, updated_at, deleted_at
from templates
where lower(name) = lower($1)
  and deleted_at is null
`

// Backs ResolveTemplate in the name-based resolver. Case-insensitive
// on lower(name) to match the uq_templates_name functional
// index — every /v1/templates/{id} read and every POST body that
// references a template by name routes through here when the
// identifier is not a UUID. Visibility is NOT filtered at the SQL
// layer: callers run their own RBAC / visibility checks after the
// resolve (e.g. checkTemplateUseAccess) so the handler can return 404
// not_found for both "missing" and "invisible to you" cases without
// the resolver leaking the distinction.
func (q *Queries) GetTemplateByName(ctx context.Context, name string) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByName, name)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.Architecture,
		&i.OsFamily,
		&i.OsVariant,
		&i.ImageUrl,
		&i.ImageChecksumSha256,
		&i.ImageFormat,
		&i.ImageSizeBytes,
		&i.FirmwareType,
		&i.FirmwareID,
		&i.DefaultCpuCores,
		&i.DefaultMemoryMib,
		&i.DefaultDiskGib,
		&i.CloudInitSupported,
		&i.CloudInitUserData,
		&i.QemuGuestAgentExpected,
		&i.Metadata,
		&i.DerivedVmCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementTemplateDerivedVMCount = `-- name: IncrementTemplateDerivedVMCount :exec
update templates
set derived_vm_count = derived_vm_count + 1
where id = $1
  and deleted_at is null
`

// Bumps templates.derived_vm_count by one. Called from VMCreateWorker's
// success projection inside the same InTx as UpdateTaskFinalized. The
// column carries a check (derived_vm_count >= 0) at the schema level;
// the increment cannot underflow.
func (q *Queries) IncrementTemplateDerivedVMCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementTemplateDerivedVMCount, id)
	return err
}

const listTemplates = `-- name: ListTemplates :many
select id, owner_id, name, description, visibility, architecture, os_family, os_variant, image_url, image_checksum_sha256, image_format, image_size_bytes, firmware_type, firmware_id, default_cpu_cores, default_memory_mib, default_disk_gib, cloud_init_supported, cloud_init_user_data, qemu_guest_agent_expected, metadata, derived_vm_count, created_at, updated_at, deleted_at
from templates
where deleted_at is null
  and (
       $1::boolean
    or visibility = 'public'
    or ($2::uuid is not null and owner_id = $2::uuid)
  )
  and ($3::uuid is null    or owner_id     = $3::uuid)
  and ($4::text is null  or visibility   = $4::text)
  and ($5::cpu_arch is null or architecture = $5::cpu_arch)
  and ($6::os_family is null   or os_family    = $6::os_family)
  and (
    $7::timestamptz is null
    or (created_at, id) > (
      $7::timestamptz,
      $8::uuid
    )
  )
order by created_at, id
limit $9
`

type ListTemplatesParams struct {
	CallerCanSeeAny    bool
	CallerID           *uuid.UUID
	OwnerIDFilter      *uuid.UUID
	VisibilityFilter   *string
	ArchitectureFilter *CpuArch
	OsFamilyFilter     *OsFamily
	CursorCreatedAt    *time.Time
	CursorID           *uuid.UUID
	LimitCount         int32
}

// Visibility-aware listing for templates. The clamp is encoded as two
// parameters:
//
//   - caller_can_see_any (bool) — true for admin/operator. When true,
//     the visibility / ownership clause short-circuits and every active
//     template (subject to the optional query filters) is returned.
//   - caller_id (uuid, nullable) — for developer it is the caller's id
//     (own private + public are visible); for viewer it is NULL (only
//     public are visible).
//
// Optional query filters (?owner_id, ?visibility, ?architecture,
// ?os_family) compose with the clamp via AND. A non-admin caller that
// supplies ?owner_id pointing at another user therefore sees only that
// user's public templates — their private set never leaks. Cursor
// pagination.
//
// The WHERE-shape is intentionally aligned with idx_templates_visibility
// (visibility, owner_id) — visibility is the leading filter on
// non-admin callers, which lets the index do the heavy lifting.
func (q *Queries) ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates,
		arg.CallerCanSeeAny,
		arg.CallerID,
		arg.OwnerIDFilter,
		arg.VisibilityFilter,
		arg.ArchitectureFilter,
		arg.OsFamilyFilter,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.Architecture,
			&i.OsFamily,
			&i.OsVariant,
			&i.ImageUrl,
			&i.ImageChecksumSha256,
			&i.ImageFormat,
			&i.ImageSizeBytes,
			&i.FirmwareType,
			&i.FirmwareID,
			&i.DefaultCpuCores,
			&i.DefaultMemoryMib,
			&i.DefaultDiskGib,
			&i.CloudInitSupported,
			&i.CloudInitUserData,
			&i.QemuGuestAgentExpected,
			&i.Metadata,
			&i.DerivedVmCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTemplateVisibility = `-- name: SetTemplateVisibility :one
update templates
set visibility = $1::text
where id = $2
  and deleted_at is null
returning id, owner_id, name, description, visibility, architecture, os_family, os_variant, image_url, image_checksum_sha256, image_format, image_size_bytes, firmware_type, firmware_id, default_cpu_cores, default_memory_mib, default_disk_gib, cloud_init_supported, cloud_init_user_data, qemu_guest_agent_expected, metadata, derived_vm_count, created_at, updated_at, deleted_at
`

type SetTemplateVisibilityParams struct {
	Visibility string
	ID         uuid.UUID
}

// Updates only `visibility` (and `updated_at` via the existing trigger).
// The handler runs a SELECT-then-conditional-UPDATE: when the requested
// visibility equals the current visibility the UPDATE is skipped
// entirely, so updated_at remains a meaningful change marker. Owner
// never moves — publishing a private template does NOT transfer
// ownership (see docs/rbac.md).
func (q *Queries) SetTemplateVisibility(ctx context.Context, arg SetTemplateVisibilityParams) (Template, error) {
	row := q.db.QueryRow(ctx, setTemplateVisibility, arg.Visibility, arg.ID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.Architecture,
		&i.OsFamily,
		&i.OsVariant,
		&i.ImageUrl,
		&i.ImageChecksumSha256,
		&i.ImageFormat,
		&i.ImageSizeBytes,
		&i.FirmwareType,
		&i.FirmwareID,
		&i.DefaultCpuCores,
		&i.DefaultMemoryMib,
		&i.DefaultDiskGib,
		&i.CloudInitSupported,
		&i.CloudInitUserData,
		&i.QemuGuestAgentExpected,
		&i.Metadata,
		&i.DerivedVmCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteTemplate = `-- name: SoftDeleteTemplate :exec
update templates
set deleted_at = now()
where id = $1
  and deleted_at is null
`

// Soft-delete only. Three FKs reference templates:
//
//   - vms.template_id           ON DELETE SET NULL
//   - vm_disks.source_template_id  ON DELETE RESTRICT
//   - node_image_cache.template_id ON DELETE CASCADE
//
// Soft-delete bypasses all three (the row physically remains), so the
// API-level CountActiveVMsForTemplate precheck is the SOLE enforcement
// of "don't remove a template that's still in use". The partial unique
// index uq_templates_name on (name) where deleted_at is null frees the
// name for re-use the moment delete completes.
func (q *Queries) SoftDeleteTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTemplate, id)
	return err
}

const updateTemplate = `-- name: UpdateTemplate :one
update templates
set name                      = $1,
    description               = $2,
    os_variant                = $3,
    firmware_type             = $4,
    firmware_id               = $5::uuid,
    default_cpu_cores         = $6,
    default_memory_mib        = $7,
    default_disk_gib          = $8,
    cloud_init_supported      = $9,
    cloud_init_user_data      = $10::text,
    qemu_guest_agent_expected = $11,
    metadata                  = $12
where id = $13
  and deleted_at is null
returning id, owner_id, name, description, visibility, architecture, os_family, os_variant, image_url, image_checksum_sha256, image_format, image_size_bytes, firmware_type, firmware_id, default_cpu_cores, default_memory_mib, default_disk_gib, cloud_init_supported, cloud_init_user_data, qemu_guest_agent_expected, metadata, derived_vm_count, created_at, updated_at, deleted_at
`

type UpdateTemplateParams struct {
	Name                   string
	Description            string
	OsVariant              string
	FirmwareType           FirmwareType
	FirmwareID             *uuid.UUID
	DefaultCpuCores        int32
	DefaultMemoryMib       int32
	DefaultDiskGib         int32
	CloudInitSupported     bool
	CloudInitUserData      *string
	QemuGuestAgentExpected bool
	Metadata               []byte
	ID                     uuid.UUID
}

// Caller merges the patch with the current row before issuing this
// query (same pattern as UpdateNetwork / UpdateFirmware). The columns
// below are exactly the 11 mutable fields surfaced by TemplateUpdate
// in api/openapi/control-plane.yaml. Identity / image-source fields
// (architecture, os_family, owner_id, image_url, image_checksum_sha256,
// image_format, image_size_bytes) are intentionally absent — they are
// API-immutable. visibility is also absent: it moves only through
// SetTemplateVisibility.
func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.Name,
		arg.Description,
		arg.OsVariant,
		arg.FirmwareType,
		arg.FirmwareID,
		arg.DefaultCpuCores,
		arg.DefaultMemoryMib,
		arg.DefaultDiskGib,
		arg.CloudInitSupported,
		arg.CloudInitUserData,
		arg.QemuGuestAgentExpected,
		arg.Metadata,
		arg.ID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.Architecture,
		&i.OsFamily,
		&i.OsVariant,
		&i.ImageUrl,
		&i.ImageChecksumSha256,
		&i.ImageFormat,
		&i.ImageSizeBytes,
		&i.FirmwareType,
		&i.FirmwareID,
		&i.DefaultCpuCores,
		&i.DefaultMemoryMib,
		&i.DefaultDiskGib,
		&i.CloudInitSupported,
		&i.CloudInitUserData,
		&i.QemuGuestAgentExpected,
		&i.Metadata,
		&i.DerivedVmCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTemplateImageChecksumIfNull = `-- name: UpdateTemplateImageChecksumIfNull :exec
update templates
set image_checksum_sha256 = $1
where id = $2
  and image_checksum_sha256 is null
  and deleted_at is null
`

type UpdateTemplateImageChecksumIfNullParams struct {
	ImageChecksumSha256 []byte
	ID                  uuid.UUID
}

// Back-propagates the agent-computed image_checksum_sha256 onto а
// template row that was registered without one (compute mode).
// The `image_checksum_sha256 is null` guard в the WHERE clause makes
// this idempotent and race-safe:
//
//   - First successful compute-mode import for the template lands the
//     hash; subsequent imports (к other pools, OR re-imports к the same
//     pool) become no-ops because the column is no longer NULL.
//   - Two concurrent compute-mode imports к different pools that happen
//     к compute different bytes (corrupted download) cannot both win:
//     whichever transaction commits first wins; the second's UPDATE
//     affects 0 rows и is silently absorbed.
//
// The :exec return shape is acceptable because the worker treats а
// failed update as а warning, not а terminal-fail signal — the
// storage_images row is already authoritative for the (template, pool)
// combination.
func (q *Queries) UpdateTemplateImageChecksumIfNull(ctx context.Context, arg UpdateTemplateImageChecksumIfNullParams) error {
	_, err := q.db.Exec(ctx, updateTemplateImageChecksumIfNull, arg.ImageChecksumSha256, arg.ID)
	return err
}
