// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAdmins = `-- name: CountAdmins :one
select count(*)::bigint as admin_count
from users
where role = 'admin'
  and deleted_at is null
`

// Used by the bootstrap-admin path to skip seeding when an admin
// already exists. Counts non-deleted rows so a soft-deleted admin
// does not satisfy the precondition.
func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var admin_count int64
	err := row.Scan(&admin_count)
	return admin_count, err
}

const countUserResources = `-- name: CountUserResources :one
select
    (select count(*)::bigint from vms       v where v.owner_id = $1 and v.deleted_at is null) as vms,
    (select count(*)::bigint from templates t where t.owner_id = $1 and t.deleted_at is null) as templates,
    (select count(*)::bigint from snapshots s where s.owner_id = $1 and s.deleted_at is null) as snapshots
`

type CountUserResourcesRow struct {
	Vms       int64
	Templates int64
	Snapshots int64
}

// Returns counts of resources owned by user, for the DELETE precheck
// (cannot delete a user with owned VMs / templates / snapshots).
// Counts exclude soft-deleted rows.
// Aliased to silence sqlc 1.31.1 analyzer ambiguity warning. The three
// subqueries are independent — column qualification is cosmetic.
func (q *Queries) CountUserResources(ctx context.Context, userID uuid.UUID) (CountUserResourcesRow, error) {
	row := q.db.QueryRow(ctx, countUserResources, userID)
	var i CountUserResourcesRow
	err := row.Scan(&i.Vms, &i.Templates, &i.Snapshots)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into users (id, email, password_hash, display_name, role)
values (
    $1,
    $2,
    $3,
    $4,
    $5
)
returning id, email, password_hash, display_name, role, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	DisplayName  string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, display_name, role, last_login_at, created_at, updated_at, deleted_at
from users
where lower(email) = lower($1)
  and deleted_at is null
`

// Email uniqueness is case-insensitive (uq_users_email on lower(email)).
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, password_hash, display_name, role, last_login_at, created_at, updated_at, deleted_at
from users
where id = $1
  and deleted_at is null
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
select id, email, password_hash, display_name, role, last_login_at, created_at, updated_at, deleted_at
from users
where deleted_at is null
  and (
    $1::timestamptz is null
    or (created_at, id) > (
      $1::timestamptz,
      $2::uuid
    )
  )
order by created_at, id
limit $3
`

type ListUsersParams struct {
	CursorCreatedAt *time.Time
	CursorID        *uuid.UUID
	LimitCount      int32
}

// Cursor pagination: (created_at, id) ordered, nullable cursor
// params indicate "first page". Caller passes limit_count = clamp(limit, 1, 200).
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.CursorCreatedAt, arg.CursorID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.DisplayName,
			&i.Role,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
update users
set deleted_at = now()
where id = $1
  and deleted_at is null
`

// Sets deleted_at = now(); preserves the row for audit / FK integrity.
// Hard delete is not exposed via the API (owned resources block
// deletion entirely).
func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const touchUserLastLogin = `-- name: TouchUserLastLogin :exec
update users
set last_login_at = now()
where id = $1
  and deleted_at is null
`

// Records a successful login. Separate from UpdateUser because it's a hot
// path (every login) and shouldn't go through the full row replacement.
func (q *Queries) TouchUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLastLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
update users
set email         = $1,
    password_hash = $2,
    display_name  = $3,
    role          = $4
where id = $5
  and deleted_at is null
returning id, email, password_hash, display_name, role, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	Email        string
	PasswordHash string
	DisplayName  string
	Role         string
	ID           uuid.UUID
}

// Caller merges patch with current values; this query updates the lot.
// updated_at is bumped by the trg_set_updated_at trigger.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Role,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
