// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vm_disks.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countVMsByPool = `-- name: CountVMsByPool :one
select count(distinct d.vm_id)::bigint
from vm_disks d
join vms v on v.id = d.vm_id
where d.storage_pool_id = $1
  and d.deleted_at is null
  and v.deleted_at is null
`

// Distinct-VM count for a given storage_pool_id, used by
// storage_pools.delete to refuse deletion of pools backing live VMs.
// Counts via vm_disks (the only place pool_id lives для a vm) and
// excludes soft-deleted disks AND soft-deleted VMs.
func (q *Queries) CountVMsByPool(ctx context.Context, storagePoolID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVMsByPool, storagePoolID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createVMDisk = `-- name: CreateVMDisk :one

insert into vm_disks (
    vm_id,
    storage_pool_id,
    device_order,
    bus,
    size_gib,
    source_kind,
    source_template_id,
    format,
    read_only,
    cache_mode,
    discard,
    boot_order
)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7::uuid,
    $8,
    $9,
    $10,
    $11,
    $12::int
)
returning id, vm_id, storage_pool_id, device_order, bus, size_gib, source_kind, source_template_id, format, read_only, cache_mode, discard, boot_order, generation, created_at, updated_at, deleted_at
`

type CreateVMDiskParams struct {
	VmID             uuid.UUID
	StoragePoolID    uuid.UUID
	DeviceOrder      int32
	Bus              DiskBus
	SizeGib          int32
	SourceKind       string
	SourceTemplateID *uuid.UUID
	Format           ImageFormat
	ReadOnly         bool
	CacheMode        DiskCacheMode
	Discard          DiskDiscard
	BootOrder        *int32
}

// vm_disks queries — Phase A foundations. The vms table itself does
// not carry a pool_id / node_id column (per the original schema design
// multi-disk VMs span pools and node placement is observed through
// vm_runtime). Pool persistence lives on vm_disks.storage_pool_id.
//
// For MVP each VM has exactly one disk row, sourced from a template,
// pinned to one storage_pool. CountVMsByPool joins through vm_disks
// to support the storage_pools.delete extended-refusal check (Phase B).
// Inserts a single disk row for a vm. Phase B vm.create handler invokes
// this once per VM (single-disk MVP). Multi-disk callers loop с distinct
// device_order values.
func (q *Queries) CreateVMDisk(ctx context.Context, arg CreateVMDiskParams) (VMDisk, error) {
	row := q.db.QueryRow(ctx, createVMDisk,
		arg.VmID,
		arg.StoragePoolID,
		arg.DeviceOrder,
		arg.Bus,
		arg.SizeGib,
		arg.SourceKind,
		arg.SourceTemplateID,
		arg.Format,
		arg.ReadOnly,
		arg.CacheMode,
		arg.Discard,
		arg.BootOrder,
	)
	var i VMDisk
	err := row.Scan(
		&i.ID,
		&i.VmID,
		&i.StoragePoolID,
		&i.DeviceOrder,
		&i.Bus,
		&i.SizeGib,
		&i.SourceKind,
		&i.SourceTemplateID,
		&i.Format,
		&i.ReadOnly,
		&i.CacheMode,
		&i.Discard,
		&i.BootOrder,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listVMDisksByVM = `-- name: ListVMDisksByVM :many
select id, vm_id, storage_pool_id, device_order, bus, size_gib, source_kind, source_template_id, format, read_only, cache_mode, discard, boot_order, generation, created_at, updated_at, deleted_at
from vm_disks
where vm_id = $1
  and deleted_at is null
order by device_order asc
`

// Returns every active (not soft-deleted) disk row for a vm, ordered
// by device_order. Phase B's GET /v1/vms/{id} response projects the
// pool_id from disk[0].storage_pool_id (single-disk MVP).
func (q *Queries) ListVMDisksByVM(ctx context.Context, vmID uuid.UUID) ([]VMDisk, error) {
	rows, err := q.db.Query(ctx, listVMDisksByVM, vmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VMDisk{}
	for rows.Next() {
		var i VMDisk
		if err := rows.Scan(
			&i.ID,
			&i.VmID,
			&i.StoragePoolID,
			&i.DeviceOrder,
			&i.Bus,
			&i.SizeGib,
			&i.SourceKind,
			&i.SourceTemplateID,
			&i.Format,
			&i.ReadOnly,
			&i.CacheMode,
			&i.Discard,
			&i.BootOrder,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVMDisksByVM = `-- name: SoftDeleteVMDisksByVM :exec
update vm_disks
set deleted_at = now()
where vm_id = $1
  and deleted_at is null
`

// Bulk soft-delete every disk row attached к a VM. Called by the
// worker's vm.delete cleanup phase together с SoftDeleteVM. The
// per-row deleted_at stamp keeps the on delete cascade behaviour of
// vm_disks.vm_id from removing rows that audit reads might still
// need.
func (q *Queries) SoftDeleteVMDisksByVM(ctx context.Context, vmID uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteVMDisksByVM, vmID)
	return err
}
