// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vm_runtime.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteVMRuntime = `-- name: DeleteVMRuntime :exec
delete from vm_runtime
where vm_id = $1
`

// Removes the runtime snapshot. Called by the worker's vm.delete
// cleanup phase after the agent confirms teardown.
func (q *Queries) DeleteVMRuntime(ctx context.Context, vmID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVMRuntime, vmID)
	return err
}

const filterExistingVMIDs = `-- name: FilterExistingVMIDs :many
select id
from vms
where id = any($1::uuid[])
  and deleted_at is null
`

// Pre-filter for the heartbeat receiver's VM-projection step. Returns
// only the VM ids that exist in `vms` and are not soft-deleted, so
// the handler can skip unknown vm_uuids with a WARN instead of taking
// an FK violation on UpsertVMRuntime. One round-trip vs. N — the
// heartbeat carries up to a node's worth of VMs.
func (q *Queries) FilterExistingVMIDs(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, filterExistingVMIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVMRuntime = `-- name: GetVMRuntime :one
select vm_id, current_node_id, phase, conditions, observed_generation, qemu_pid, qmp_socket_path, vnc_port, spice_port, serial_console_path, guest_os, guest_hostname, guest_ip_addresses, cpu_usage_percent, memory_used_mib, last_started_at, last_stopped_at, last_error_at, last_error_message, last_observed_at, updated_at
from vm_runtime
where vm_id = $1
`

// Read the runtime snapshot for a VM, used by GET /v1/vms/{id} to
// project a combined desired+observed status. Returns ErrNoRows when
// the worker has not yet upserted (i.e. the VM is still в
// desired_phase='running' but the agent hasn't acknowledged).
func (q *Queries) GetVMRuntime(ctx context.Context, vmID uuid.UUID) (VMRuntime, error) {
	row := q.db.QueryRow(ctx, getVMRuntime, vmID)
	var i VMRuntime
	err := row.Scan(
		&i.VmID,
		&i.CurrentNodeID,
		&i.Phase,
		&i.Conditions,
		&i.ObservedGeneration,
		&i.QEMUPID,
		&i.QmpSocketPath,
		&i.VncPort,
		&i.SpicePort,
		&i.SerialConsolePath,
		&i.GuestOs,
		&i.GuestHostname,
		&i.GuestIpAddresses,
		&i.CpuUsagePercent,
		&i.MemoryUsedMib,
		&i.LastStartedAt,
		&i.LastStoppedAt,
		&i.LastErrorAt,
		&i.LastErrorMessage,
		&i.LastObservedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVMRuntimePhase = `-- name: UpdateVMRuntimePhase :exec
update vm_runtime
set phase = $1,
    last_observed_at = now()
where vm_id = $2
`

type UpdateVMRuntimePhaseParams struct {
	Phase VMPhase
	VmID  uuid.UUID
}

// Single-field phase patch used by the synchronous VM lifecycle
// handlers (pause / resume / reset). The CP-side handler invokes
// this after the agent confirms а QMP-driven transition so the
// next projected `status` reflects the new state without waiting
// for the heartbeat reconciler to catch up. last_observed_at is
// stamped to keep the wire's observed-state freshness signal
// monotonic.
func (q *Queries) UpdateVMRuntimePhase(ctx context.Context, arg UpdateVMRuntimePhaseParams) error {
	_, err := q.db.Exec(ctx, updateVMRuntimePhase, arg.Phase, arg.VmID)
	return err
}

const upsertVMRuntime = `-- name: UpsertVMRuntime :exec
insert into vm_runtime (
    vm_id,
    current_node_id,
    phase,
    observed_generation,
    qemu_pid,
    last_started_at,
    last_error_message,
    last_observed_at
)
values (
    $1,
    $2,
    $3,
    $4,
    $5::int,
    $6::timestamptz,
    $7::text,
    now()
)
on conflict (vm_id) do update
set current_node_id     = excluded.current_node_id,
    phase               = excluded.phase,
    observed_generation = excluded.observed_generation,
    qemu_pid            = excluded.qemu_pid,
    last_started_at     = excluded.last_started_at,
    last_error_message  = excluded.last_error_message,
    last_observed_at    = excluded.last_observed_at
`

type UpsertVMRuntimeParams struct {
	VmID               uuid.UUID
	CurrentNodeID      *uuid.UUID
	Phase              VMPhase
	ObservedGeneration int64
	QEMUPID            *int32
	LastStartedAt      *time.Time
	LastErrorMessage   *string
}

// Heartbeat-driven projection of a per-VM runtime snapshot. Conflict
// on the primary key (vm_id) resolves to UPDATE; the heartbeat is
// the only writer of the agent-reported fields. observed_generation
// is bumped when the agent reports a value; missing values pass
// through nullable parameters. last_observed_at is stamped on every
// upsert (separate from the trigger-managed updated_at, which fires
// on UPDATE only).
func (q *Queries) UpsertVMRuntime(ctx context.Context, arg UpsertVMRuntimeParams) error {
	_, err := q.db.Exec(ctx, upsertVMRuntime,
		arg.VmID,
		arg.CurrentNodeID,
		arg.Phase,
		arg.ObservedGeneration,
		arg.QEMUPID,
		arg.LastStartedAt,
		arg.LastErrorMessage,
	)
	return err
}
