// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vms.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRunningVMsByNode = `-- name: CountRunningVMsByNode :one
select count(*)::bigint
from vms
where pinned_node_id = $1
  and deleted_at is null
  and desired_phase != 'deleted'
`

// Counts VMs intended to run on the given node. Used by the placement
// scheduler for Least-VM-count tie-breaking. Counted by
// vms.pinned_node_id (intent) rather than vm_runtime.current_node_id
// (observed) so a burst of concurrent creates targeting the same
// least-loaded node spread out immediately; vm_runtime rows arrive
// only after the agent reports them.
func (q *Queries) CountRunningVMsByNode(ctx context.Context, nodeID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningVMsByNode, nodeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createVM = `-- name: CreateVM :one

insert into vms (
    id,
    owner_id,
    name,
    description,
    template_id,
    architecture,
    cpu_cores,
    memory_mib,
    cpu_model,
    machine_type,
    firmware_id,
    pinned_node_id,
    user_data,
    cloud_init_disabled,
    labels
)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11::uuid,
    $12::uuid,
    $13::text,
    $14,
    $15
)
returning id, owner_id, name, description, desired_phase, template_id, architecture, cpu_cores, memory_mib, cpu_model, machine_type, firmware_id, pinned_node_id, scheduler_hints, user_data, cloud_init_disabled, meta_data, network_config, ssh_authorized_keys, labels, generation, created_at, updated_at, deleted_at
`

type CreateVMParams struct {
	ID                uuid.UUID
	OwnerID           uuid.UUID
	Name              string
	Description       string
	TemplateID        *uuid.UUID
	Architecture      CPUArch
	CpuCores          int32
	MemoryMib         int32
	CPUModel          string
	MachineType       string
	FirmwareID        *uuid.UUID
	PinnedNodeID      *uuid.UUID
	UserData          *string
	CloudInitDisabled bool
	Labels            []byte
}

// VMs queries — foundations for the CP-side vm.create / vm.delete
// vertical slice. Schema-aligned: cpu_cores not "vcpus", memory_mib not
// "memory_mb", no pool_id/node_id columns on vms (pool comes through
// vm_disks; current node comes through vm_runtime). The handler boundary
// translates the simplified API wire shape to and from these column
// names.
// Inserts a new vms row. Caller supplies the id explicitly (unified
// UUID, CP mints / agent uses). desired_phase defaults to 'running'
// so the operator's "create" intent maps to "VM should run" without a
// separate state transition.
func (q *Queries) CreateVM(ctx context.Context, arg CreateVMParams) (VM, error) {
	row := q.db.QueryRow(ctx, createVM,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.TemplateID,
		arg.Architecture,
		arg.CpuCores,
		arg.MemoryMib,
		arg.CPUModel,
		arg.MachineType,
		arg.FirmwareID,
		arg.PinnedNodeID,
		arg.UserData,
		arg.CloudInitDisabled,
		arg.Labels,
	)
	var i VM
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.DesiredPhase,
		&i.TemplateID,
		&i.Architecture,
		&i.CpuCores,
		&i.MemoryMib,
		&i.CPUModel,
		&i.MachineType,
		&i.FirmwareID,
		&i.PinnedNodeID,
		&i.SchedulerHints,
		&i.UserData,
		&i.CloudInitDisabled,
		&i.MetaData,
		&i.NetworkConfig,
		&i.SshAuthorizedKeys,
		&i.Labels,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVMByID = `-- name: GetVMByID :one
select id, owner_id, name, description, desired_phase, template_id, architecture, cpu_cores, memory_mib, cpu_model, machine_type, firmware_id, pinned_node_id, scheduler_hints, user_data, cloud_init_disabled, meta_data, network_config, ssh_authorized_keys, labels, generation, created_at, updated_at, deleted_at
from vms
where id = $1
  and deleted_at is null
`

func (q *Queries) GetVMByID(ctx context.Context, id uuid.UUID) (VM, error) {
	row := q.db.QueryRow(ctx, getVMByID, id)
	var i VM
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.DesiredPhase,
		&i.TemplateID,
		&i.Architecture,
		&i.CpuCores,
		&i.MemoryMib,
		&i.CPUModel,
		&i.MachineType,
		&i.FirmwareID,
		&i.PinnedNodeID,
		&i.SchedulerHints,
		&i.UserData,
		&i.CloudInitDisabled,
		&i.MetaData,
		&i.NetworkConfig,
		&i.SshAuthorizedKeys,
		&i.Labels,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVMByName = `-- name: GetVMByName :one
select id, owner_id, name, description, desired_phase, template_id, architecture, cpu_cores, memory_mib, cpu_model, machine_type, firmware_id, pinned_node_id, scheduler_hints, user_data, cloud_init_disabled, meta_data, network_config, ssh_authorized_keys, labels, generation, created_at, updated_at, deleted_at
from vms
where lower(name) = lower($1)
  and deleted_at is null
`

// Used by the create handler for globally-unique-name precheck before
// the insert (the unique partial index would catch it as a 23505 too,
// but a friendly 409 with the existing id is preferable). Also backs
// ResolveVM in the name-based resolver (internal/api/handlers/internal/
// resolver) — every GET / DELETE on /v1/vms/{id} folds to this query when
// the identifier is not a UUID. The lookup is case-insensitive to match
// uq_vms_name on lower(name); the row preserves the operator's chosen
// casing.
func (q *Queries) GetVMByName(ctx context.Context, name string) (VM, error) {
	row := q.db.QueryRow(ctx, getVMByName, name)
	var i VM
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.DesiredPhase,
		&i.TemplateID,
		&i.Architecture,
		&i.CpuCores,
		&i.MemoryMib,
		&i.CPUModel,
		&i.MachineType,
		&i.FirmwareID,
		&i.PinnedNodeID,
		&i.SchedulerHints,
		&i.UserData,
		&i.CloudInitDisabled,
		&i.MetaData,
		&i.NetworkConfig,
		&i.SshAuthorizedKeys,
		&i.Labels,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listVMs = `-- name: ListVMs :many
select id, owner_id, name, description, desired_phase, template_id, architecture, cpu_cores, memory_mib, cpu_model, machine_type, firmware_id, pinned_node_id, scheduler_hints, user_data, cloud_init_disabled, meta_data, network_config, ssh_authorized_keys, labels, generation, created_at, updated_at, deleted_at
from vms
where deleted_at is null
  and (
    $1::uuid is null
    or exists (
      select 1 from vm_disks
      where vm_disks.vm_id = vms.id
        and vm_disks.storage_pool_id = $1::uuid
        and vm_disks.deleted_at is null
    )
  )
  and (
    $2::uuid is null
    or exists (
      select 1 from vm_runtime
      where vm_runtime.vm_id = vms.id
        and vm_runtime.current_node_id = $2::uuid
    )
  )
  and (
    $3::timestamptz is null
    or (created_at, id) < (
      $3::timestamptz,
      $4::uuid
    )
  )
order by created_at desc, id desc
limit $5
`

type ListVMsParams struct {
	PoolIDFilter    *uuid.UUID
	NodeIDFilter    *uuid.UUID
	CursorCreatedAt *time.Time
	CursorID        *uuid.UUID
	LimitCount      int32
}

// Cursor pagination. First page passes nulls; subsequent
// pages pass the previous page's last (created_at, id) tuple. Ordering
// (created_at desc, id desc) matches every other paginated endpoint.
//
// Optional filters:
//
//   - pool_id_filter — only VMs whose vm_disks references the named
//     pool. Resolved upstream from the wire `?pool=` query param,
//     which accepts either a UUID literal or a pool name. Implemented
//     as EXISTS rather than a JOIN to keep the row count stable for
//     multi-disk VMs (the MVP is single-disk, but the query is
//     correct for whatever future disk-fanout decisions land on).
//
//   - node_id_filter — only VMs currently located on the named node
//     per vm_runtime.current_node_id (D6 — current location, not
//     pinned intent). 'creating' VMs without a runtime row never
//     match.
func (q *Queries) ListVMs(ctx context.Context, arg ListVMsParams) ([]VM, error) {
	rows, err := q.db.Query(ctx, listVMs,
		arg.PoolIDFilter,
		arg.NodeIDFilter,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VM{}
	for rows.Next() {
		var i VM
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.DesiredPhase,
			&i.TemplateID,
			&i.Architecture,
			&i.CpuCores,
			&i.MemoryMib,
			&i.CPUModel,
			&i.MachineType,
			&i.FirmwareID,
			&i.PinnedNodeID,
			&i.SchedulerHints,
			&i.UserData,
			&i.CloudInitDisabled,
			&i.MetaData,
			&i.NetworkConfig,
			&i.SshAuthorizedKeys,
			&i.Labels,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMsByOwner = `-- name: ListVMsByOwner :many
select id, owner_id, name, description, desired_phase, template_id, architecture, cpu_cores, memory_mib, cpu_model, machine_type, firmware_id, pinned_node_id, scheduler_hints, user_data, cloud_init_disabled, meta_data, network_config, ssh_authorized_keys, labels, generation, created_at, updated_at, deleted_at
from vms
where owner_id = $1
  and deleted_at is null
  and (
    $2::timestamptz is null
    or (created_at, id) < (
      $2::timestamptz,
      $3::uuid
    )
  )
order by created_at desc, id desc
limit $4
`

type ListVMsByOwnerParams struct {
	OwnerID         uuid.UUID
	CursorCreatedAt *time.Time
	CursorID        *uuid.UUID
	LimitCount      int32
}

// Same shape as ListVMs but filtered by owner_id. RBAC scope=own path —
// currently inactive (vm:read=any for every role) but kept for future
// restricted-role flows.
func (q *Queries) ListVMsByOwner(ctx context.Context, arg ListVMsByOwnerParams) ([]VM, error) {
	rows, err := q.db.Query(ctx, listVMsByOwner,
		arg.OwnerID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VM{}
	for rows.Next() {
		var i VM
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.DesiredPhase,
			&i.TemplateID,
			&i.Architecture,
			&i.CpuCores,
			&i.MemoryMib,
			&i.CPUModel,
			&i.MachineType,
			&i.FirmwareID,
			&i.PinnedNodeID,
			&i.SchedulerHints,
			&i.UserData,
			&i.CloudInitDisabled,
			&i.MetaData,
			&i.NetworkConfig,
			&i.SshAuthorizedKeys,
			&i.Labels,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMsForNodeDeclared = `-- name: ListVMsForNodeDeclared :many
select
    vms.name::text         as name,
    vms.desired_phase      as desired_phase,
    vms.generation::bigint as generation
from vms
join vm_runtime on vm_runtime.vm_id = vms.id
where vm_runtime.current_node_id = $1::uuid
  and vms.deleted_at is null
  and vm_runtime.phase != 'gone'
order by lower(vms.name) asc
`

type ListVMsForNodeDeclaredRow struct {
	Name         string
	DesiredPhase VMDesiredPhase
	Generation   int64
}

// Per-node VM desired-state inventory for HeartbeatResponse.declared_vms.
// Joins vms × vm_runtime on the runtime's current_node_id (D6 — current
// location, not pinned intent). Soft-deleted vms are excluded; runtime
// rows whose phase has reached 'gone' are excluded too (the VM is no
// longer materialised on this node). Output is sorted lower(name) asc
// so the agent's diff against observed state stays deterministic across
// heartbeats.
func (q *Queries) ListVMsForNodeDeclared(ctx context.Context, nodeID uuid.UUID) ([]ListVMsForNodeDeclaredRow, error) {
	rows, err := q.db.Query(ctx, listVMsForNodeDeclared, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVMsForNodeDeclaredRow{}
	for rows.Next() {
		var i ListVMsForNodeDeclaredRow
		if err := rows.Scan(&i.Name, &i.DesiredPhase, &i.Generation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVM = `-- name: SoftDeleteVM :exec
update vms
set deleted_at = now()
where id = $1
  and deleted_at is null
`

// Soft delete sets deleted_at; the unique partial index on (name) where
// deleted_at is null releases the name immediately so a fresh create
// with the same name can succeed. The vm_runtime row (if any) is
// handled separately by DeleteVMRuntime in the worker's cleanup phase.
func (q *Queries) SoftDeleteVM(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteVM, id)
	return err
}

const updateVMDesiredPhase = `-- name: UpdateVMDesiredPhase :exec
update vms
set desired_phase = $1,
    updated_at    = now()
where id = $2
  and deleted_at is null
`

type UpdateVMDesiredPhaseParams struct {
	DesiredPhase VMDesiredPhase
	ID           uuid.UUID
}

// Used by the worker to flip desired_phase to 'deleted' as the user-visible
// delete starts (before the agent acknowledges teardown). Clean read-side
// semantics: desired_phase reflects user intent; vm_runtime.phase reflects
// observed.
func (q *Queries) UpdateVMDesiredPhase(ctx context.Context, arg UpdateVMDesiredPhaseParams) error {
	_, err := q.db.Exec(ctx, updateVMDesiredPhase, arg.DesiredPhase, arg.ID)
	return err
}
