// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Andrei Taranik

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
	"time"
)

// gatewayConfigTemplateText is the generated gateway runtime config:
// operator inputs + auto-detected values written explicitly, tunables
// left as commented hints. text/template (not yaml.Marshal) preserves the
// comments across regeneration. The VM-specific blocks (state_path, qemu,
// migration) are absent — a gateway hosts no VMs.
const gatewayConfigTemplateText = `# Otherix gateway configuration — generated by ` + "`otherix-gateway bootstrap`" + `.
# DO NOT hand-edit. Re-run ` + "`otherix-gateway bootstrap --force`" + ` to regenerate
# cert material; delete this file first to regenerate the config itself.

server:
  listen: "{{.ListenAddr}}"            # bootstrap --listen
  # read_timeout: 30s                   # uncomment to override default
  # write_timeout: 30s
  # shutdown_grace: 30s

logger:
  level: "info"                        # default; "debug" for local debugging
  format: "json"

control_plane:
  url: "{{.CPURL}}"                    # bootstrap --cp-url
  heartbeat_interval: "{{.HeartbeatInterval}}"

tls:
  ca_cert_path: "{{.CAPath}}"          # written by bootstrap.Persist
  cert_path:    "{{.CertPath}}"
  key_path:     "{{.KeyPath}}"

# The gateway joins the WireGuard mesh to reach guest VMs over the overlay.
# Its key is dedicated (never shared with a co-located agent identity), and
# the advertised endpoint is the UDP host:port peers dial for the handshake.
wireguard:
  private_key_path: "/var/lib/otherix/wg-gateway/private.key"
  listen_port: {{.WireguardListenPort}}
  persistent_keepalive: 25s
  advertised_endpoint: "{{.WireguardEndpoint}}"

# A gateway hosts no VMs and never migrates, so this block is inert. It is
# present only because the shared runtime config requires a migration host;
# the gateway never advertises a migration capability in its heartbeat.
migration:
  host: "0.0.0.0"
  port_range_start: 49152
  port_range_end:   49251
`

// gatewayConfigTemplate is parsed once at process startup.
var gatewayConfigTemplate = template.Must(template.New("gateway-config").Parse(gatewayConfigTemplateText))

// gatewayConfigInputs is the data the gateway.yaml template needs.
type gatewayConfigInputs struct {
	CPURL             string
	HeartbeatInterval time.Duration
	ListenAddr        string
	CertPath          string
	KeyPath           string
	CAPath            string
	// WireguardEndpoint is the UDP host:port peers dial to complete the
	// WireGuard handshake to the gateway; required for mesh reachability.
	WireguardEndpoint string
	// WireguardListenPort is the UDP port the gateway's WG interface binds.
	WireguardListenPort int
}

// writeGatewayConfig renders gatewayConfigTemplate against in and writes
// the result atomically (tempfile + rename in the destination directory)
// at mode 0644. The parent directory is created with mode 0750 if absent.
func writeGatewayConfig(destPath string, in gatewayConfigInputs) error {
	var buf bytes.Buffer
	if err := gatewayConfigTemplate.Execute(&buf, in); err != nil {
		return fmt.Errorf("render gateway-config template: %v", err)
	}

	dir := filepath.Dir(destPath)
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return fmt.Errorf("ensure parent dir %s: %v", dir, err)
	}

	tmp, err := os.CreateTemp(dir, ".gateway-config-*.tmp")
	if err != nil {
		return fmt.Errorf("create temp file in %s: %v", dir, err)
	}
	tmpName := tmp.Name()
	cleanup := func() { _ = os.Remove(tmpName) }

	if err := tmp.Chmod(0o644); err != nil {
		_ = tmp.Close()
		cleanup()
		return fmt.Errorf("chmod temp: %v", err)
	}
	if _, err := tmp.Write(buf.Bytes()); err != nil {
		_ = tmp.Close()
		cleanup()
		return fmt.Errorf("write temp: %v", err)
	}
	if err := tmp.Close(); err != nil {
		cleanup()
		return fmt.Errorf("close temp: %v", err)
	}
	if err := os.Rename(tmpName, destPath); err != nil {
		cleanup()
		return fmt.Errorf("rename %s -> %s: %v", tmpName, destPath, err)
	}
	return nil
}
